import { ApprovalsService } from './approvals.service';
import { CreateApprovalDto } from './dto/create-approval.dto';
import { ApproveDto, RejectDto, DiscussDto, SignatureDto } from './dto/approval-action.dto';
import { Request } from 'express';
export declare class ApprovalsController {
    private readonly approvalsService;
    constructor(approvalsService: ApprovalsService);
    create(projectId: string, createDto: CreateApprovalDto, userId: string): Promise<{
        status: string;
        title: string;
        id: string;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        priority: string;
        comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
        description: string | null;
        updatedAt: Date;
        documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
        projectId: string;
        dueDate: Date | null;
        rejectionReason: string | null;
        segmentId: string | null;
        approvalType: string;
        requestedBy: string;
        assignedTo: string;
        approvedAt: Date | null;
        approvedBy: string | null;
        rejectedAt: Date | null;
        rejectedBy: string | null;
    }>;
    findAll(projectId: string, status?: string): Promise<{
        status: string;
        title: string;
        id: string;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        priority: string;
        comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
        description: string | null;
        updatedAt: Date;
        documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
        projectId: string;
        dueDate: Date | null;
        rejectionReason: string | null;
        segmentId: string | null;
        approvalType: string;
        requestedBy: string;
        assignedTo: string;
        approvedAt: Date | null;
        approvedBy: string | null;
        rejectedAt: Date | null;
        rejectedBy: string | null;
    }[]>;
    getPending(projectId: string): Promise<{
        status: string;
        title: string;
        id: string;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        priority: string;
        comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
        description: string | null;
        updatedAt: Date;
        documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
        projectId: string;
        dueDate: Date | null;
        rejectionReason: string | null;
        segmentId: string | null;
        approvalType: string;
        requestedBy: string;
        assignedTo: string;
        approvedAt: Date | null;
        approvedBy: string | null;
        rejectedAt: Date | null;
        rejectedBy: string | null;
    }[]>;
    getMetrics(projectId: string): Promise<{
        total: number;
        approved: number;
        rejected: number;
        pending: number;
        overdue: number;
        approvalRate: number;
        avgApprovalTimeDays: number;
    }>;
    findOne(projectId: string, approvalId: string): Promise<{
        status: string;
        title: string;
        id: string;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        priority: string;
        comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
        description: string | null;
        updatedAt: Date;
        documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
        projectId: string;
        dueDate: Date | null;
        rejectionReason: string | null;
        segmentId: string | null;
        approvalType: string;
        requestedBy: string;
        assignedTo: string;
        approvedAt: Date | null;
        approvedBy: string | null;
        rejectedAt: Date | null;
        rejectedBy: string | null;
    }>;
    approve(projectId: string, approvalId: string, approveDto: ApproveDto, userId: string, req: Request): Promise<{
        status: string;
        title: string;
        id: string;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        priority: string;
        comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
        description: string | null;
        updatedAt: Date;
        documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
        projectId: string;
        dueDate: Date | null;
        rejectionReason: string | null;
        segmentId: string | null;
        approvalType: string;
        requestedBy: string;
        assignedTo: string;
        approvedAt: Date | null;
        approvedBy: string | null;
        rejectedAt: Date | null;
        rejectedBy: string | null;
    }>;
    reject(projectId: string, approvalId: string, rejectDto: RejectDto, userId: string): Promise<{
        status: string;
        title: string;
        id: string;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        priority: string;
        comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
        description: string | null;
        updatedAt: Date;
        documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
        projectId: string;
        dueDate: Date | null;
        rejectionReason: string | null;
        segmentId: string | null;
        approvalType: string;
        requestedBy: string;
        assignedTo: string;
        approvedAt: Date | null;
        approvedBy: string | null;
        rejectedAt: Date | null;
        rejectedBy: string | null;
    }>;
    discuss(projectId: string, approvalId: string, discussDto: DiscussDto, userId: string): Promise<{
        status: string;
        title: string;
        id: string;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        priority: string;
        comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
        description: string | null;
        updatedAt: Date;
        documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
        projectId: string;
        dueDate: Date | null;
        rejectionReason: string | null;
        segmentId: string | null;
        approvalType: string;
        requestedBy: string;
        assignedTo: string;
        approvedAt: Date | null;
        approvedBy: string | null;
        rejectedAt: Date | null;
        rejectedBy: string | null;
    }>;
    addSignature(projectId: string, approvalId: string, signatureDto: SignatureDto, userId: string, req: Request): Promise<{
        status: string;
        title: string;
        id: string;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        priority: string;
        comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
        description: string | null;
        updatedAt: Date;
        documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
        projectId: string;
        dueDate: Date | null;
        rejectionReason: string | null;
        segmentId: string | null;
        approvalType: string;
        requestedBy: string;
        assignedTo: string;
        approvedAt: Date | null;
        approvedBy: string | null;
        rejectedAt: Date | null;
        rejectedBy: string | null;
    }>;
}
//# sourceMappingURL=approvals.controller.d.ts.map