import { useState } from 'react'
import { AlertTriangle, ArrowDown, ArrowRight, Check, ChevronRight, Circle } from 'lucide-react'
import './App.css'
import existingProject from 'data-url:../public/evidence/01-existing-project-top.jpg'
import leadCapture from 'data-url:../public/evidence/02-lead-capture.jpg'
import projectSchedule from 'data-url:../public/evidence/04-project-schedule.jpg'
import closeout from 'data-url:../public/evidence/05-closeout.jpg'

type Phase = 'Project' | 'Install' | 'Care'
type LayoutKey = 'chapters' | 'runway' | 'rooms'

const findings = [
  { n:'01', severity:'Critical', title:'Install is present, but operationally understructured', body:'The live project can contain an “Installation & Styling” schedule phase while the document spine still reads “Install —”. Install has a body, but the schedule, room, and chapter models do not hand off to it coherently.', evidence:'Observed in production · Aug 12' },
  { n:'02', severity:'Critical', title:'Schedule controls can become silently inert', body:'The Schedule Rule remains visible in Install and Care, but the detailed Schedule Spine that handles its clicks only mounts in Project. A designer can click an apparent phase or milestone control and get no response.', evidence:'Source-backed interaction failure' },
  { n:'03', severity:'High', title:'Project is a scroll, not a workspace', body:'Approvals, communication, schedule, FF&E, billing authority, commercial planning, closeout, mood boards, drawings, and team controls all sit in one continuous column. The ordering is fixed even as the designer’s job changes.', evidence:'Live walk + source order' },
  { n:'04', severity:'High', title:'The transition to Install removes structure at the moment it matters most', body:'Project groups FF&E by room and carries rich coordination. Install flattens the list and drops the same coordination surface, just when the designer needs placement, delivery, damage, punch, and site status.', evidence:'Source-backed · FF&E / doc route' },
  { n:'05', severity:'High', title:'“Next up” competes with a dozen other visible acts', body:'The guide promises one next action, while the opening stack also exposes messaging, preview, scan, sharing, call sheet, folio, approvals, schedule controls, handoffs, and margin actions.', evidence:'Observed in production' },
  { n:'06', severity:'High', title:'Closeout arrives early—and does not remember partial progress', body:'During installation, a large Care checklist and portfolio form can dominate the page. Its manual progress is local component state until final submission, so leaving or refreshing can erase an unfinished closeout session.', evidence:'Live walk + source-backed' },
  { n:'07', severity:'High', title:'There are too many answers to “where am I?”', body:'The seven-section spine, phase estimates, canonical workflow stage, schedule phases, and active-work guide all describe position using different vocabularies. None is individually wrong; together they create translation work.', evidence:'Live walk + source-backed' },
  { n:'08', severity:'Medium', title:'Supporting records are buried in a permanent long tail', body:'Drawings, mood boards, accounts, roster, and files stay far below active work regardless of phase. During install, a plan detail can be more urgent than an approval history—but layout priority never changes.', evidence:'Source order' },
  { n:'09', severity:'High', title:'Past Project becomes a dead-end when Install begins', body:'Once Project is settled, its spine row remains clickable, but only Brief through Proposal have review bodies. Installers can jump to Project history and land on an inert settled bar.', evidence:'Source-backed interaction failure' },
  { n:'10', severity:'High', title:'Quiet typography crosses into illegibility', body:'Important metadata is repeatedly rendered below the documented 12px floor. Low contrast, all-caps microcopy, and dense inline controls feel elegant at rest but expensive under field pressure.', evidence:'Source-backed + visual review' },
  { n:'11', severity:'High', title:'The handoff invites a completion it already knows is blocked', body:'Phase Handoffs can list unresolved blockers while leaving “Complete phase” enabled. The expected designer journey is to click a primary action and receive a server rejection instead of being guided to the blocking work.', evidence:'Source-backed · phase advance control' },
  { n:'12', severity:'High', title:'Mobile navigation points to work that is not there', body:'Room jump controls remain visible in Install and Care even though their room targets only exist in Project. Mobile handoff chips can also describe the next act without providing a way to perform it.', evidence:'Source-backed · mobile document shell' },
  { n:'13', severity:'High', title:'Operational closeout is gated by portfolio production', body:'Photography, final portfolio images, and a written case study are treated as equal prerequisites alongside walkthrough, punch, and payment. A finished client engagement cannot settle until optional marketing work is also complete.', evidence:'Source-backed · closure derivation' },
]

const principles = [
  ['Preserve the shell','Keep the full-bleed paper, spine, margin, and one-document focus. Those are the product’s strongest ideas.'],
  ['One lifecycle, three emphases','Project, Install, and Care should keep the same architecture; only default expansion and emphasis should change.'],
  ['One place for status','Spine = chapters. Masthead = current stage and next act. Schedule = time and dependency. No overlap.'],
  ['Progressive disclosure','Show one expanded work module. Reduce every other module to a scored summary with status and one doorway.'],
  ['Rooms survive the handoff','The room structure should become more important in Install, never disappear.'],
  ['No new data required','These proposals reorganize existing facts and actions. They do not depend on a schema or workflow rewrite.'],
]

const layoutMeta:Record<LayoutKey,{name:string;strap:string;fit:string}> = {
  chapters:{name:'A · The Chaptered Worktable',strap:'Recommended',fit:'Best all-around evolution of the current Document'},
  runway:{name:'B · The Studio Runway',strap:'Operations-forward',fit:'Best for multi-party projects with a heavy weekly cadence'},
  rooms:{name:'C · The Room Folios',strap:'Install-first',fit:'Best for furnishing-heavy work and install days'},
}
const phaseCopy:Record<Phase,{stage:string;next:string;meta:string}> = {
  Project:{stage:'Design Development · FF&E · stage 06',next:'Resolve the dining table finish before releasing A3',meta:'4 rooms · 18 pieces · $47,680 scheduled'},
  Install:{stage:'Installation & Styling · week 1 of 3',next:'Confirm receiving for 3 pieces arriving tomorrow',meta:'12 of 18 installed · 2 blockers · 1 site day'},
  Care:{stage:'Completion · closeout in progress',next:'Settle the living-room punch list with Kody',meta:'4 of 6 closeout items · balance clear'},
}

function Severity({children}:{children:string}) { return <span className={`severity severity-${children.toLowerCase()}`}>{children}</span> }
function Mark(){return <span className="brand-mark" aria-hidden="true"><i/><i/><i/></span>}
function PhaseSwitch({phase,setPhase}:{phase:Phase;setPhase:(p:Phase)=>void}){return <div className="phase-switch" role="group" aria-label="Mockup phase">{(['Project','Install','Care'] as Phase[]).map(item=><button key={item} aria-pressed={phase===item} className={phase===item?'active':''} onClick={()=>setPhase(item)}>{item}</button>)}</div>}

function MockSpine({phase}:{phase:Phase}){return <aside className="mock-spine"><span className="put-down">← PUT DOWN</span>{['Brief','Discovery','Direction','Proposal','Project','Install','Care'].map(item=>{const active=item===phase;const past=['Brief','Discovery','Direction','Proposal'].includes(item)||(phase!=='Project'&&item==='Project');return <div className={`spine-row ${active?'active':''} ${past?'past':''}`} key={item}><span className="spine-rule"/><div><b>{item}</b><small>{active?'IN HAND':past?'SETTLED':'—'}</small></div></div>})}<div className="timer"><Circle size={8} fill="currentColor"/> IN HAND<br/><strong>1h 12m</strong></div></aside>}
function Masthead({phase}:{phase:Phase}){const copy=phaseCopy[phase];return <header className="mock-masthead"><div className="mock-title"><Mark/><div><h3>Winky Loft</h3><p>for Kody Winky · Aug 12 → Dec 30</p></div></div><div className="stage-readout"><small>{phase.toUpperCase()}</small><strong>{copy.stage}</strong><span>{copy.meta}</span></div><div className="next-act"><small>NEXT UP</small><b>{copy.next}</b><button type="button" disabled aria-label="Illustrative open action">OPEN <ArrowRight size={13}/></button></div></header>}
function RoomRows({phase}:{phase:Phase}){const data=phase==='Project'?[['Living','6 pieces · $22,840','2 decisions'],['Dining','4 pieces · $14,900','Release A3'],['Entry','3 pieces · $4,240','On track']]:phase==='Install'?[['Living','5 of 6 installed','1 damaged'],['Dining','2 of 4 installed','3 arriving'],['Entry','3 of 3 installed','Complete']]:[['Living','1 punch item','Walkthrough'],['Dining','Complete','Filed'],['Entry','Complete','Filed']];return <div className="room-rows">{data.map(([room,meta,state],i)=><div className="room-row" key={room}><span className="room-index">0{i+1}</span><div><b>{room}</b><small>{meta}</small></div><span className={state.toLowerCase().includes('complete')||state==='Filed'?'good':''}>{state}</span><ChevronRight size={15}/></div>)}</div>}

function ChaptersMock({phase}:{phase:Phase}){const tabs=phase==='Project'?['Schedule','Rooms & FF&E','Coordination','Commercial','References']:phase==='Install'?['Rooms on site','Deliveries','Coordination','Punch','References']:['Closeout','Portfolio','Installation record','Reviews','References'];return <div className="layout-canvas"><MockSpine phase={phase}/><main className="mock-paper"><Masthead phase={phase}/><nav className="chapter-nav">{tabs.map((x,i)=><span className={i===0?'active':''} key={x}>{x}</span>)}</nav><div className="chapter-grid"><section className="primary-sheet"><div className="section-kicker">{phase==='Install'?'ROOMS ON SITE':phase==='Care'?'CLOSEOUT RECORD':'SCHEDULE · ACTIVE WORK'}</div><h4>{phase==='Project'?'What moves this week':phase==='Install'?'The install by room':'Finish well, then make it useful'}</h4><RoomRows phase={phase}/></section><aside className="summary-stack"><div className="summary-card urgent"><small>BLOCKED</small><b>{phase==='Care'?'1 punch item':'Dining table finish'}</b><span>Kody’s hand · due today</span></div><div className="summary-card"><small>NEXT MILESTONE</small><b>{phase==='Install'?'Site day · Aug 14':'Client review · Aug 16'}</b><span>3 related items</span></div><div className="summary-card"><small>CLOSEOUT</small><b>{phase==='Care'?'4 of 6 complete':'Not ready · folded'}</b><span>Open summary</span></div></aside></div></main><aside className="mock-margin"><b>IN THE MARGIN</b><button>+ NOTE</button><div className="margin-note">DECISION · DUE<br/><strong>Dining table finish</strong></div><div className="margin-note quiet">MONEY · SENT<br/><strong>INV-0018</strong></div></aside></div>}

const runwayCards:Record<Phase,[string,string,string[]][]> = {
  Project:[['NOW','3',['Resolve dining finish','Release lighting package','Review reflected ceiling plan']],['THIS WEEK','5',['Finalize living selections','Issue drawing set v3','Approve budget B-002']],['WAITING','2',['Kody · finish decision','Maker · revised strike-off']],['RECORD','12',['A1 executed','Budget B-002','Drawing set v3']]],
  Install:[['NOW','3',['Confirm receiving window','Resolve dining damage','Send site-day brief']],['THIS WEEK','5',['Living install','Styling pull list','Client walkthrough']],['WAITING','2',['Receiver · dock time','Maker · ship notice']],['RECORD','12',['Delivery 014','Site report 006','Punch log v2']]],
  Care:[['NOW','1',['Settle living-room punch']],['THIS WEEK','3',['Complete client review','File care instructions','Select portfolio images']],['WAITING','1',['Kody · walkthrough note']],['RECORD','18',['Installed-piece record','Final drawing set','Payments clear']]],
}
function RunwayMock({phase}:{phase:Phase}){return <div className="layout-canvas runway-layout"><MockSpine phase={phase}/><main className="mock-paper"><Masthead phase={phase}/><div className="runway-rule"><span className="past">CONSULT</span><span className="past">DESIGN</span><span className="past">PROCURE</span><span className="now">{phase.toUpperCase()}</span><span>COMPLETE</span></div><section className="runway-board">{runwayCards[phase].map(([title,count,cards])=><div className="runway-column" key={title}><div className="column-head"><b>{title}</b><span>{count}</span></div>{cards.map((card,i)=><div className={`task-slip ${i===0&&title==='NOW'?'hot':''}`} key={card}><small>{i===0?'NEXT ACT':phase}</small><b>{card}</b><span>{i===0?'Today · you':phase==='Care'?'Filed · studio':'Aug 14 · studio'}</span></div>)}</div>)}</section><div className="runway-footer"><b>{phase==='Care'?'ROOM COMPLETION':'ROOM PULSE'}</b><RoomRows phase={phase}/></div></main></div>}

const folioCopy:Record<Phase,{progress:string;items:[string,string,string][];sideLabel:string;sideTitle:string;stats:[string,string][];action:string}> = {
  Project:{progress:'5 of 6 specified',items:[['Otto dining table','FINISH DECISION · DUE','$9,995'],['Line credenza','AUTHORIZED · A1','$3,777'],['PH5 pendant','APPROVAL REQUESTED','$990']],sideLabel:'ROOM SUMMARY',sideTitle:'Living room',stats:[['06','Pieces specified'],['$22K','Room budget'],['02','Open decisions']],action:'OPEN ROOM BRIEF'},
  Install:{progress:'5 of 6 installed',items:[['Otto dining table','ARRIVING TOMORROW','$9,995'],['Line credenza','INSTALLED','$3,777'],['PH5 pendant','BLOCKED · SITE','$990']],sideLabel:'SITE DAY',sideTitle:'Friday · Aug 14',stats:[['08:00','Receiver access'],['10:30','Installer arrival'],['02','Open coordination items']],action:'OPEN CALL SHEET'},
  Care:{progress:'1 punch item remains',items:[['Otto dining table','INSTALLED · FILED','$9,995'],['Line credenza','INSTALLED · FILED','$3,777'],['PH5 pendant','PUNCH · SHADE ALIGNMENT','$990']],sideLabel:'COMPLETION RECORD',sideTitle:'Living room',stats:[['05','Pieces settled'],['01','Punch item'],['CLEAR','Room balance']],action:'OPEN INSTALL RECORD'},
}
function RoomsMock({phase}:{phase:Phase}){const copy=folioCopy[phase];return <div className="layout-canvas rooms-layout"><MockSpine phase={phase}/><main className="mock-paper"><Masthead phase={phase}/><div className="rooms-workspace"><aside className="folio-index"><small>ROOM FOLIOS</small>{['Living','Dining','Entry','Throughout'].map((x,i)=><button type="button" disabled aria-label={`Illustrative ${x} folio`} className={i===0?'active':''} key={x}><span>0{i+1}</span>{x}<em>{i===0?'1 issue':'clear'}</em></button>)}</aside><section className="room-sheet"><div className="room-heading"><div><small>ROOM 01</small><h4>Living</h4></div><span>{copy.progress}</span></div>{copy.items.map(([name,state,price],i)=><div className={`piece-row ${i===2?'blocked':''}`} key={name}><span className="piece-dot"/><div><b>{name}</b><small>{state}</small></div><strong>{price}</strong><ChevronRight size={15}/></div>)}</section><aside className="field-sheet"><small>{copy.sideLabel}</small><h4>{copy.sideTitle}</h4>{copy.stats.map(([value,label])=><div className="field-stat" key={label}><b>{value}</b><span>{label}</span></div>)}<button type="button" disabled aria-label="Illustrative doorway" className="field-action">{copy.action} <ArrowRight size={13}/></button></aside></div></main></div>}
function LayoutMock({layout,phase}:{layout:LayoutKey;phase:Phase}){if(layout==='runway')return <RunwayMock phase={phase}/>;if(layout==='rooms')return <RoomsMock phase={phase}/>;return <ChaptersMock phase={phase}/>}

function App(){const[phase,setPhase]=useState<Phase>('Install');const[layout,setLayout]=useState<LayoutKey>('chapters');return <div className="report-shell">
  <nav className="report-nav"><a href="#top" className="report-brand"><Mark/><span>PATINA<br/><small>DESIGN REVIEW · 08.12.26</small></span></a><div><a href="#diagnosis">Diagnosis</a><a href="#evidence">Evidence</a><a href="#layouts">Three layouts</a><a href="#decision">Recommendation</a></div></nav>
  <header className="hero" id="top"><div className="hero-index">01 / 05</div><div className="eyebrow">DESIGNER PORTAL · /DOC · PROJECT → INSTALL</div><h1>The Document has a<br/><em>strong shell</em> and a<br/>broken handoff.</h1><p className="hero-lede">A production UI/UX audit of how Patina’s document supports a designer after the proposal is signed—through planning, procurement, installation, and closeout.</p><div className="hero-verdict"><span>THE SHORT VERSION</span><p>Project accumulates every useful surface at equal weight. Install then removes the room and coordination structures the designer needs to keep her bearings.</p></div><a className="down-link" href="#diagnosis">READ THE FINDINGS <ArrowDown size={15}/></a></header>
  <main>
    <section className="chapter" id="diagnosis"><div className="chapter-number">02</div><div className="chapter-intro"><span>DIAGNOSIS</span><h2>Where the experience falls apart</h2><p>This is an information-architecture problem, not a data problem. The facts are mostly present; their relationship and phase-specific priority are not.</p></div><div className="finding-grid">{findings.map(f=><article className="finding" key={f.n}><div className="finding-head"><span>{f.n}</span><Severity>{f.severity}</Severity></div><h3>{f.title}</h3><p>{f.body}</p><small>{f.evidence}</small></article>)}</div></section>
    <section className="journey-section"><div className="section-label">THE CURRENT JOURNEY</div><div className="journey-line">{[['Lead','Light, focused capture','good'],['Discovery','Structured essentials','good'],['Proposal','Clear commitment','good'],['Project','Everything, all at once','bad'],['Install','Active work without stable room structure','bad'],['Care','Closeout mixed with live install records','warn']].map(([title,body,state],i)=><div className={`journey-node ${state}`} key={title}><span>0{i+1}</span><b>{title}</b><p>{body}</p></div>)}</div></section>
    <section className="chapter evidence-chapter" id="evidence"><div className="chapter-number">03</div><div className="chapter-intro"><span>PRODUCTION EVIDENCE</span><h2>What the designer actually sees</h2><p>Walked live in Chrome under the authorized studio account. Two clearly labeled audit records were created to probe lead capture, direct project creation, schedule birth, install timing, and closeout readiness.</p></div><div className="evidence-grid"><figure className="evidence-hero"><img src={existingProject} alt="Existing production project document with dense top stack"/><figcaption><b>Existing active project</b><span>The first viewport prioritizes approval ceremony and document chrome before schedule, rooms, or work.</span></figcaption></figure><figure><img src={leadCapture} alt="Lead capture sheet"/><figcaption><b>Lead capture works</b><span>Small ask, clear consequence, one next act.</span></figcaption></figure><figure><img src={projectSchedule} alt="Project schedule and FF&E start"/><figcaption><b>The Project page expands</b><span>Six-phase schedule plus FF&E begins a very long vertical document.</span></figcaption></figure><figure className="evidence-wide"><img src={closeout} alt="Closeout form appearing in an active project"/><figcaption><b>Closeout is visually premature</b><span>A large portfolio and closeout form competes with active operational work.</span></figcaption></figure></div><div className="observed-strip"><AlertTriangle size={18}/><div><b>Observed contradiction</b><span>The schedule contains “Installation & Styling,” yet the left document spine remains “Install —”. That is the clearest visual proof that schedule phases and document chapters are not speaking one language.</span></div></div></section>
    <section className="principles-section"><div className="section-label">DESIGN RULES FOR THE REPAIR</div><div className="principle-grid">{principles.map(([title,body],i)=><div className="principle" key={title}><span>0{i+1}</span><b>{title}</b><p>{body}</p></div>)}</div></section>
    <section className="chapter layouts-chapter" id="layouts"><div className="chapter-number">04</div><div className="chapter-intro"><span>THREE PROPOSED LAYOUTS</span><h2>Three ways to make the same facts cohere</h2><p>Switch the phase and layout below. Each concept preserves Patina’s paper, spine, margin, and quiet typography—while changing the organizing idea of the work.</p></div><div className="layout-controls"><div className="layout-tabs" role="group" aria-label="Proposed layout">{(Object.keys(layoutMeta) as LayoutKey[]).map(key=><button key={key} aria-pressed={layout===key} onClick={()=>setLayout(key)} className={layout===key?'active':''}><span>{layoutMeta[key].name}</span><small>{layoutMeta[key].strap}</small></button>)}</div><PhaseSwitch phase={phase} setPhase={setPhase}/></div><div className="layout-caption"><div><span>CONCEPT</span><h3>{layoutMeta[layout].name}</h3></div><p>{layoutMeta[layout].fit}</p></div><LayoutMock layout={layout} phase={phase}/><div className="layout-notes">{layout==='chapters'&&<><b>Why it works</b><p>It repairs hierarchy with the least conceptual change. The active chapter becomes a worktable; every other domain becomes a scored summary. Project, Install, and Care keep identical bones.</p><span className="recommendation-chip"><Check size={14}/> RECOMMENDED DIRECTION</span></>}{layout==='runway'&&<><b>Why it works</b><p>It organizes the designer’s week by motion and ball-in-court. Excellent for a busy studio, though it risks feeling more like operations software and less like a lasting document.</p></>}{layout==='rooms'&&<><b>Why it works</b><p>It matches how furnishings and install work are experienced physically. The room remains the unit from specification through punch, but schedule-level dependencies require a secondary doorway.</p></>}</div></section>
    <section className="decision-section" id="decision"><div className="decision-mark"><Mark/></div><div className="decision-copy"><span>RECOMMENDATION</span><h2>Build Layout A.<br/>Borrow Layout C for Install.</h2><p>The Chaptered Worktable is the cleanest evolution of the current concept. It needs no new nouns and no new data. When the active chapter is Install, its primary work module should use the Room Folios pattern: stable room groups, item movement, site-day context, and punch—all in one place.</p></div><div className="decision-actions">{['Collapse the opening stack into one phase masthead','Add a phase-local contents strip with one module open','Preserve room groups and coordination through Install','Reduce closeout to readiness until chosen or ready','Recast installed pieces as a quiet record in Care'].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></section>
    <section className="method-section"><div><span>METHOD</span><p>Production walkthrough · desktop Chrome · existing active project + two labeled audit records · source review of the `/doc` route, FF&E, schedule, workflow, spine, margin, and Care band · review against the append-only Document decisions.</p></div><div><span>BOUNDARY</span><p>This review proposes no changes to the data model. It focuses on how existing information fits together from the designer’s point of view.</p></div><div><span>TEST RECORDS</span><p><code>[UX Audit] Kochaver install journey</code><br/><code>[UX Audit] Project-to-install layout study</code></p></div></section>
  </main><footer><span>PATINA · THE DOCUMENT</span><span>DESIGNER PORTAL UI/UX REVIEW · AUGUST 12, 2026</span></footer>
</div>}
export default App
