export const meta = {
  name: 'daily-return-w1b-fix',
  description: 'W1b fix round on the integration branch: the Companion ≤6-row crash, the engaged seed account that cannot sign in, the residual browse-grid hit-frame mismatch — then review and a full re-walk',
  phases: [
    { title: 'Fix', detail: 'one Opus implementer on daily-return/integration' },
    { title: 'Review', detail: 'separate-context review of the fix diff' },
    { title: 'Re-walk', detail: 'the full W1b acceptance script, all accounts' },
  ],
}

const ROOT = '/Users/kody/Code/patina-merged'
const OUT = `${ROOT}/artifacts/ios-daily-return-2026-08-26`
const S = `${OUT}/source`
const R = `${OUT}/research`
const W = `${OUT}/waves/w1b`
const WT = `${ROOT}/.codex/worktrees/agent-dr-w1b-integration`
const INT_UDID = '34EDD568-43AE-4546-A0FE-AB9161FF9391'
const REVIEW_UDID = '973D1724-90BF-4A0A-B02D-481D561547B3'

const COMMON = `You are one agent in the Daily Return build program for the Patina iOS CLIENT app (apps/mobile/Patina). The orchestrator (Fable) reads only your structured return and your files on disk.
Ground rules: program folder ${OUT}; read ${S}/build-plan.md "Global constraints" first, then ${W}/walk.md (the failed acceptance walk — the three findings are your brief), ${W}/integration.md, ${W}/rulings-fable.md. Sandbox: xcodebuild, xcrun simctl, git worktree/merge, osascript, docker, sips and the supabase CLI need dangerouslyDisableSandbox: true; everything else sandboxed; every build/test in the foreground. Never git add -A; pathspec commits only; never push; never run git in the main checkout except read-only; never touch production. Honesty (C5) and the Companion contract (C8: ≤6 rows per context, coaching phases unchanged) are canon. Report with evidence; FINAL action = StructuredOutput even on failure.`

const safe = async (label, p) => { try { const r = await p; if (!r) log(`${label}: returned null`); return r } catch (e) { log(`${label}: threw ${e && e.message ? e.message : e}`); return null } }
const REPORT = { type: 'object', required: ['ok', 'notes'], properties: { ok: { type: 'boolean' }, commits: { type: 'array', items: { type: 'string' } }, gate: { type: 'string' }, app_path: { type: 'string' }, notes: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }
const REV = { type: 'object', required: ['file', 'blocking', 'major', 'minor'], properties: { file: { type: 'string' }, blocking: { type: 'array', items: { type: 'string' } }, major: { type: 'array', items: { type: 'string' } }, minor: { type: 'array', items: { type: 'string' } } } }

phase('Fix')
const fix = await safe('F', agent(`${COMMON}

ROLE: F — fix the three walk findings on branch daily-return/integration in ${WT} (verify git rev-parse --show-toplevel ends with agent-dr-w1b-integration; mkdir .writer.lock.d — if it exists, stop and report). Simulator for your gate + checks: ${INT_UDID} (dr-w1b-int, the integration build is installed there). -derivedDataPath ${WT}/.build/dd for tests; the signed .app goes to ${WT}/.build/dd-signed.
1. THE CRASH (blocking). Read Features/Companion/Services/CompanionContextProvider.swift (the assertion at :106) and CompanionAreaBuilders.swift homeItems() in full, plus CompanionActionMatrixTests. Design, do not suppress: the assertion is canon (C8, ≤6 rows per context) and stays. Make homeItems() honour it in EVERY branch — enumerate the inputs (rooms 0 / 1+, DesignerRelationship live / none, promoted request present / absent, saved count 0 / n, tier) and collapse rows by this priority: (1) Message your designer (only when live), (2) the request/matched row (only when present), (3) Browse pieces, (4) Saved (unconditional per SP-12), (5) Your spaces — with "Scan a room" folded INTO the spaces row's action when zero rooms exist (one row, not two), (6) whatever standing tail the provider appends. If the tail plus rows still exceed six in any combination, drop the lowest-priority row and say which in a comment. Add CompanionActionMatrixTests cases that build the home menu for every input combination and assert count ≤ 6 and that the priority order holds; keep the existing matrix cases green. Then prove it on the simulator: sign in as client@patina.dev (password123; per ${R}/02-steward-boot.md §7) and open the Daily Room — no assertion; capture ${OUT}/shots/w1b-fix-01-daily-room-client.png and the Companion panel w1b-fix-02.
2. THE ENGAGED SEED (blocking for the walk). GoTrue 500s for james.okafor@example.com: "converting NULL to string is unsupported" on auth.users.confirmation_token. Find the seed that inserts that auth.users row (grep supabase/seed for james.okafor and for INSERT INTO auth.users) and set the four GoTrue token columns to '' (confirmation_token, recovery_token, email_change_token_new, email_change) — for EVERY seeded auth.users row that leaves them NULL, not just James. Re-run supabase db reset (unsandboxed; you own the local DB now) and prove sign-in with curl -s -X POST http://127.0.0.1:54321/auth/v1/token?grant_type=password (apikey + Content-Type headers; the anon key per 02-steward-boot.md) for james.okafor@example.com AND client@patina.dev → 200 with access_token. Note: the seeded invoice INV-2026-0142 is now in supabase/seed/invoices.sql (added at integration) — confirm it survives the reset.
3. THE GRID HIT-FRAMES (SP-02 residual). walk.md shows two same-row cards with different heights/origins (Heirloom {x:-4.33,y:218,w:228,h:262} vs Live-Edge {x:207,y:154,w:171,h:326}). Read Features/Recommendations/Views/RecommendationsView.swift's grid and Features/Shared/Views/ProductCard.swift; find why one card's frame is taller and shifted (name wrapping to more lines, a missing fixed image height, an alignment on the LazyVGrid row, or the matched-geometry source frame) and make every card in a row the same size with its hit-box equal to its visible bounds; pin with BrowseGridContractTests (a card's intrinsic height must not depend on name length beyond a fixed two-line clamp). Prove with describe_screen frames before/after on the simulator (blitz: ToolSearch "select:mcp__blitz-iphone__describe_screen,mcp__blitz-iphone__device_action,mcp__blitz-iphone__scan_ui,mcp__blitz-iphone__get_screenshot"; explicit udid ${INT_UDID}) and a shot w1b-fix-03.
GATE (unsandboxed, foreground): apps/mobile/Patina/scripts/ios-gate.sh build (twice if the first fails without an error line); xcodebuild test -only-testing:PatinaTests on ${INT_UDID}; apps/mobile/Patina/scripts/ios-gate.sh lint-delta main; supabase db reset clean + scripts/run-sql-tests.sh; signed rebuild; install on ${INT_UDID}. Pathspec commits, Conventional Commits, each finding its own commit. rmdir the lock. Return ok, commits, gate, app_path, notes, failures.`, { label: 'F fix', phase: 'Fix', model: 'opus', effort: 'high', schema: REPORT }))
if (!fix || !fix.ok) return { fix }

phase('Review')
const rev = await safe('V', agent(`${COMMON}

ROLE: V — reviewer of the fix round, separate context, read-only (git -C ${WT} log --oneline -4; git -C ${WT} show <sha> for each fix commit). Implementer's report: ${JSON.stringify({ commits: fix.commits, gate: fix.gate, notes: fix.notes })}. Check: (1) the ≤6 assertion still stands and homeItems() honours it in every input combination (reason through the branches yourself; do the new tests cover rooms × designer × request × saved × tier); is the collapse a design (priority order, spaces/scan folded) rather than a silent drop; canonical row labels (C4: "Browse pieces", "Saved", "Your spaces", "Get design help"/"Message your designer"); (2) the seed fix covers every seeded auth.users row and nothing else changed in those files; (3) the grid fix addresses the cause, not a symptom, and the test pins it; (4) no unrelated changes; pathspec commits. Write ${W}/fix-review.md; report every finding with severity + confidence.`, { label: 'V review', phase: 'Review', model: 'sonnet', schema: REV }))
if (rev && rev.blocking.length) { log(`Review blocking: ${rev.blocking.join(' | ')}`); return { fix, review: rev } }

phase('Re-walk')
const walk = await safe('walk', agent(`${COMMON}

ROLE: walker — the FULL W1b acceptance walk, again, on the review simulator ${REVIEW_UDID} (yours). Read ${W}/walk.md (the failed pass — its PASS items need not be re-proven if the fix touched nothing near them, but say so per item), the "Acceptance walk (walker…)" paragraph of build-plan.md §W1b (the script), and the four re-shoot targets w1b-90..93 named in the W1b workflow (Studio subhead fallback, "Awaiting you" badge, Today's decision Next Move copy, the Studio Conversation row at zero threads). Unsandboxed: xcrun simctl install ${REVIEW_UDID} ${fix.app_path}; terminate + launch with -DeploymentTarget local; if the app is signed in as client@patina.dev already, continue; else sign in per ${R}/02-steward-boot.md §7. Accounts: client@patina.dev, james.okafor@example.com (now signs in), guest. Blitz taps with explicit udid. Run notify_client_attention(...) unsandboxed for the open invoice + one pending decision before opening Notifications (the function signature is in supabase/migrations/00534_*.sql in ${WT}). Capture ${OUT}/shots/w1b-NN-slug.png per script line (continue numbering from the last w1b- shot), append ledger rows under "## w1b re-walk", and REWRITE ${W}/walk.md as the final record: one PASS / FAIL / BLOCKED line per acceptance item with the shot and verbatim copy for every FAIL. The "Saved shows it under All items with date" line is a W4 deliverable per build-plan.md — mark it DEFERRED-W4, not FAIL. Leave the simulator signed in as client@patina.dev on the Daily Room. Return ok = no FAIL lines.`, { label: 'walk', phase: 'Re-walk', model: 'sonnet', schema: REPORT }))
return { fix: { ok: fix.ok, commits: fix.commits, gate: fix.gate, app_path: fix.app_path, notes: fix.notes }, review: rev, walk }
