export const meta = {
  name: 'daily-return-w2-record',
  description: 'W2 of the Daily Return build: the Record home (ruling R1 "now") — record data, record UI + designer seat + house rail + New This Week, July-rail hygiene (Q4), and migration 00537 — in owned-file lanes, reviewed, fixed, integrated, walked',
  phases: [
    { title: 'Steward setup', detail: 'worktrees, Secrets.swift, simulator clones, owned-file map, project_rooms policy check' },
    { title: 'Lanes', detail: 'R1 record data ∥ R2 record UI ∥ R3 hygiene ∥ D backend 00537' },
    { title: 'Reviews', detail: 'four separate-context adversarial reviews' },
    { title: 'Fix', detail: 'blocking + major addressed per lane' },
    { title: 'Integrate', detail: 'D → R1 → R3 → R2 into daily-return/integration; gates' },
    { title: 'Walk', detail: 'acceptance script on the review simulator, three accounts + guest' },
  ],
}

const ROOT = '/Users/kody/Code/patina-merged'
const OUT = `${ROOT}/artifacts/ios-daily-return-2026-08-26`
const S = `${OUT}/source`
const R = `${OUT}/research`
const W = `${OUT}/waves/w2`
const APP = `${ROOT}/apps/mobile/Patina`
const REVIEW_UDID = '973D1724-90BF-4A0A-B02D-481D561547B3'
const LANES = [
  { key: 'r1', name: 'R1 · record data', model: 'opus', reviewer: 'opus' },
  { key: 'r2', name: 'R2 · record UI', model: 'opus', reviewer: 'opus' },
  { key: 'r3', name: 'R3 · hygiene (Q4)', model: 'sonnet', reviewer: 'sonnet' },
  { key: 'd', name: 'D · backend 00537', model: 'opus', reviewer: 'sonnet' },
]
const wt = (k) => `${ROOT}/.codex/worktrees/agent-dr-w2-${k}`
const br = (k) => `daily-return/w2-${k}`

const COMMON = `You are one agent in the Daily Return build program for the Patina iOS CLIENT app (apps/mobile/Patina). The orchestrator (Fable) reads only your structured return and your files on disk.
Ground rules:
- Program folder: ${OUT}. Read ${S}/build-plan.md "Global constraints", "Team model", "### W1a — DONE" (deviations you inherit: FeatureFlags sync-from-cache; DesignerRelationship fed by liveLead; one attention predicate) and "### W2" IN FULL first; then ${S}/rulings-2026-08-27.md (R1, Q4, Q7); then ${S}/direction-b.md §1, §2, §3, §11 (M1, M1d, M2, M2d, M6d, M9 are the screens); the mocks ${OUT}/mock/fragments/b-M1.html, b-M1.sheet.html, b-M2.html, b-M2.sheet.html, b-M6d.html (Read them — the screen sheets carry copy, components, states, events); ${S}/synthesis.md §5 grafts; ${S}/build-plan-critique.md M4, M13, M16, M21, M22; ${OUT}/waves/w1b/integration.md and walk.md (what W1b left). Load Skill "patina-parallel-work"; iOS lanes also "patina-ios-verification"; the backend lane also "patina-db-migrations".
- Sandbox: xcodebuild, xcrun simctl, git worktree add/remove, git merge, osascript, docker, sips and the supabase CLI fail inside the command sandbox — run exactly those with dangerouslyDisableSandbox: true; everything else sandboxed. Every build/test in the foreground. The first xcodebuild in a fresh worktree fails on the generated GitCommit.swift — run it twice.
- Never git add -A / git add . ; pathspec commits only; never push; never run git in the main checkout except read-only log/show; never touch production.
- Owned files: edit ONLY the files in your lane's owned set (${W}/steward.md is authoritative). Cross-lane needs go into ${W}/<lane>-notes.md as integration notes the steward applies.
- Honesty (C5) governs every row and every empty: a row draws only for a real event with its real date; at guest/discovering an empty record draws NOTHING; at engaged/activeProject the truthful empties draw; "new" comes from LastSeenStore; nothing counts days away at the person. Brand voice per ${ROOT}/.claude/skills/patina-brand-voice/SKILL.md; canonical names (C4): the header word stays "Today".
- Report with evidence (command output, diff stats, test names + pass/fail, shot names) — never a paraphrase. FINAL action = StructuredOutput, even on failure.`

const safe = async (label, p) => { try { const r = await p; if (!r) log(`${label}: returned null`); return r } catch (e) { log(`${label}: threw ${e && e.message ? e.message : e}`); return null } }
const REPORT = { type: 'object', required: ['ok', 'notes'], properties: { ok: { type: 'boolean' }, commits: { type: 'array', items: { type: 'string' } }, gate: { type: 'string' }, tasks_file: { type: 'string' }, notes_file: { type: 'string' }, app_path: { type: 'string' }, migrations: { type: 'array', items: { type: 'string' } }, notes: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }
const REV = { type: 'object', required: ['file', 'blocking', 'major', 'minor'], properties: { file: { type: 'string' }, blocking: { type: 'array', items: { type: 'string' } }, major: { type: 'array', items: { type: 'string' } }, minor: { type: 'array', items: { type: 'string' } } } }

phase('Steward setup')
const setup = await safe('S', agent(`${COMMON}

ROLE: S — steward setup for W2. Base = current main tip (W1b merged): record git -C ${ROOT} log --oneline -1 main. Unsandboxed, for each key in [r1, r2, r3, d]: git -C ${ROOT} worktree add ${ROOT}/.codex/worktrees/agent-dr-w2-<key> -b daily-return/w2-<key> main; copy ${APP}/Patina/App/Configuration/Secrets.swift into each (never commit). Clone + boot a simulator "dr-w2-<key>" from ${REVIEW_UDID} for r1, r2, r3. Delete any leftover dr-w1b-* clones and remove any leftover agent-dr-w1b-* worktrees whose branches are merged (git merge-base --is-ancestor <branch> main → remove worktree + delete branch; otherwise leave and report).
Then settle the plan's open verification before the lanes start: is there already a client-scoped SELECT policy on project_rooms (build-plan-critique M4 cites 00066_proposal_project_flow_v2.sql:249-253 and 00316:148)? Read those migrations and, unsandboxed, prove it against the local database as client@patina.dev's uid (psql: set role authenticated; set request.jwt.claims to that sub; select count(*) from project_rooms) — write the answer into ${W}/steward.md so lane D mints the policy only if it is truly missing.
Write ${W}/steward.md: base sha, worktrees, clones, the project_rooms answer, the migration tip (ls supabase/migrations | tail -3) and lane D's provisional number (00537), and the OWNED-FILE MAP: R1 = Features/Home/Models/HouseRecord.swift (new), Core/Persistence/RecordSnapshotStore.swift (new), Core/Persistence/LastSeenStore.swift (new), Services/Badges/BadgeCountService.swift, Features/Profile/ViewModels/StudioQueueBuilder.swift, Core/Network/{Decisions,Proposals,Projects}APIClient.swift, Core/Models/** for any new row models, Patina/Patina.entitlements (App Group), tests for all of it; R2 = Features/Home/Views/** (HouseRecordCard, YourDesignerSeat, YourHouseRail, NewThisWeekRail — new; DailyRoomView, DailyGreetingHeader, TodayModules, DailyStoryCard), Features/Home/ViewModels/**, Features/Home/Models/TodayExperience.swift, Core/Network/EditorialStoriesAPIClient.swift (query order), tests; R3 = the Q4 orphan set (Features/Home/Views/DailyRoomStateBlocks.swift, HomeStudioBlock, StudioHubSection, MarketplaceLinksSection, WorkWithDesignerCTA, RoomChipRail, RoomContextBar, DailyFeedEmptyModule, DailyProductCard, DailyProductDetailView, ContinueScanCard, DesignRequestStatusCard — AddToRoomSheet and AddedToRoomToast are LIVE and excluded) + the tests that reference them + research/11-canon-digest.md §5; D = supabase/migrations/00537_*.sql, supabase/tests/**, packages/supabase/src/database.types.ts. R1 and R2 both touch the Home tree: R1 owns models/stores/services, R2 owns views/view-models — R1 exposes HouseRecord + the stores; R2 consumes them. Return ok, notes.`, { label: 'S setup', phase: 'Steward setup', model: 'opus', schema: REPORT }))
if (!setup || !setup.ok) return { setup }

phase('Lanes')
const laneBrief = (l) => `${COMMON}

ROLE: implementer of lane ${l.name} for W2. Read ${W}/steward.md. Deliver exactly your lane's W2 row in build-plan.md — no unrequested features, refactors or abstractions.
WORKSPACE (mandatory, first): cd ${wt(l.key)}; verify git rev-parse --show-toplevel ends with agent-dr-w2-${l.key}; mkdir .writer.lock.d (exists → stop and report); -derivedDataPath ${wt(l.key)}/.build/dd on every xcodebuild.
TASK LIST FIRST: ${W}/${l.key}-tasks.md in the writing-plans format (exact files, the interfaces neighbours rely on, failing test code, run, implement, run, pathspec commit). Read the code before writing (Serena scoped to apps/mobile/Patina, or grep + Read). Execute in order, committing per task with Conventional Commits.
${l.key === 'r1' ? `R1 SPECIFICS. Interfaces (R2 depends on these exact names — publish them in your task list first, and do not change them after your first commit):
- struct HouseRecord { let needsYou: [HouseRecordRow]; let moved: [HouseRecordRow]; let window: DateInterval; let lastSeenAt: Date?; var isEmpty: Bool }
- struct HouseRecordRow: Identifiable { enum Kind { case decisionAsked, proposalSent, invoiceDue, messageReceived, orderMoved, savedPieceRepriced, savedPieceWithdrawn, story, matchedDesigner }; let id: String; let kind: Kind; let title: String; let detail: String?; let date: Date; let state: HouseRecordRow.State; let isNew: Bool; let route: AppRoute? } with enum State { case none, overdue, due(Date), amount(cents: Int, due: Date?), new }
- HouseRecordBuilder.build(from badges: BadgeCountService, saved: [TableItemModel], products: [Product], story: EditorialStory?, liveLead: DesignRequestStatus?, lastSeen: Date?, now: Date) -> HouseRecord — rolling 7 days, ≤3 per eyebrow (the rest behind hasMore flags), ordered NEEDS YOU by date asked ascending, MOVED newest first; six-hour suppression (a record built within 6 h of the previous build keeps the previous window anchor); discovering rows: savedPieceWithdrawn (products.deleted_at set since last seen — needs the product row) and savedPieceRepriced (saved_items.price_cents_at_save ≠ current price — 00535 column; state both numbers, never a strike-through or a countdown).
- RecordSnapshotStore.shared.save(_ record: HouseRecord) / load() -> HouseRecord? — App Group "group.cloud.patina.app" via containerURL(forSecurityApplicationGroupIdentifier:), falling back to the app's Application Support when nil (Simulator without provisioning may return nil — log it, do not crash); JSON-encoded; add the App Group to Patina.entitlements.
- LastSeenStore.shared.lastSeenAt / markSeen(now:) — UserDefaults key "patina.house.lastSeenAt", written on scenePhase → .active AFTER the record for that open was built (so "new" ticks survive one open).
- BadgeCountService: per-item rows are already retained (W1a); add designer identity to the rows via one "designer:profiles!<fk>(display_name, studio_name)" embed each on Decisions/Proposals/Projects clients (find the FK names in the migrations; keep the existing shape; fallback "your designer").
- StudioQueueBuilder: per-item rows with dates (keep the grouped rows the Studio hub uses; add a flat itemized variant the record consumes).
Tests: ordering, both empties, the two-weeks-away window, first run (no lastSeen → nothing is "new"), the second open of the day (rows persist, no re-dating), six-hour suppression, discovering rows, snapshot round-trip, fallback container.` : ''}
${l.key === 'r2' ? `R2 SPECIFICS. Consume R1's interfaces exactly as published in ${W}/r1-tasks.md (read it before you start; if it is not there yet, wait — poll every 5 minutes up to 30 — then proceed against the plan's names). Build, per direction-b §2 and the M1/M2 sheets:
- HouseRecordCard (one card, two eyebrows NEEDS YOU / MOVED in DM Mono, rows 56 pt with date and state on the right — overdue / by <date> / $4,250.00 · due Sep 1 — a "new" tick, "See all →" when hasMore, truthful empties "Nothing needs you right now." / "Nothing moved since <weekday>." at engaged/activeProject; at guest/discovering an empty half is not drawn and an empty record is not mounted).
- The header: date line, TimeOfDay greeting ("Good morning." etc. — the word "Today" remains the screen's name in the tour/index, per C4/C23), the bell, the "Studio" labelled control with the W1a attention count (replaces the bare monogram).
- YourDesignerSeat (name · studio · one line of what she is doing from liveLead/project state · "Message" via W1a's MessagingAPIClient.createThread) — mounted from engaged upward.
- YourHouseRail (project rooms read-only cards with real budget/committed cents when a project owns rooms + local rooms + "Add a room"; the guest/discovering "Start with a room" two-act block: "Type the dimensions" first, "Scan it" second).
- NewThisWeekRail (get_recommendations rows with published_at ≤ 7 days — 00533 column; draws only at ≥3 rows, never pads).
- The story block demoted below the record when nothing published since last seen; EditorialStoriesAPIClient query reordered published_at desc, sort_order desc; the unread dot from SP-18's stored read id.
- Next Move: keep it as the second block only when the record has no NEEDS YOU rows; the empty-queue Next Move names current_phase (ProjectsAPIClient.swift:25).
- Card weight follows content: the record takes the hero footprint when non-empty; the story drops to a 96 pt row.
- CARRY-OVER (W1b ruling 1): fold lane B's .moneyScreenTopBand() into PatinaScreenChrome so one modifier owns the status-bar reservation (a translucent material band via safeAreaInset(edge: .top)); the money screens (Features/Proposals, Invoices, Decisions, Budget — yours for this one edit) read the shared modifier; delete the duplicate.
- Home composition per tier exactly as direction-b §2 (guest / discovering / engaged / activeProject); mount order top→bottom; the record is UNFLAGGED (R1 "now"); dark + Dynamic Type XXL clean; VoiceOver labels on every row.
- Snapshot first paint: on launch render RecordSnapshotStore.load() immediately, then refresh.
Tests: composition per tier (which blocks mount), empties per tier, hero/96 pt weighting, snapshot-first paint, the Studio control count.
SIM CHECK on your clone: client@patina.dev (activeProject), james.okafor@example.com (engaged), guest, plus a discovering account if one exists locally (see ${R}/02-steward-boot.md §6) — shots w2-r2-NN-*.png light + dark + XXL for the home at each tier; ledger rows under "## w2-r2".` : ''}
${l.key === 'r3' ? `R3 SPECIFICS (Q4 — retire the July home rail). For EACH view in your owned set: prove the call graph with grep (production code only, tests excluded) and record it in ${W}/r3-tasks.md; delete views with zero production references outright; for views still referenced (build-plan-critique M1b: DailyProductCard ← DailyRoomViewModel/ProductCard/DailyProductDetailView; StudioHubSection ← DailyRoomStateBlocks/MarketplaceLinksSection; ContinueScanCard ← DesignRequestResumeBanner) delete the July COMPOSITION (DailyRoomStateBlocks, HomeStudioBlock, MarketplaceLinksSection, WorkWithDesignerCTA, RoomChipRail, RoomContextBar, DailyFeedEmptyModule) and re-home any piece a live surface still needs (keep DesignRequestResumeBanner working; if DailyProductCard is only used by the retired composition, delete it too — prove it). Never touch AddToRoomSheet / AddedToRoomToast (live). CARRY-OVER (W1b re-walk, SP-18 residual): the Companion's product-detail quick action "Try in your room / See it in AR" dead-ends on every product while usdz_url is NULL — remove that row from the product-detail context (CompanionAreaBuilders / CompanionActionRows are yours for this one edit) and pin it in CompanionActionMatrixTests; it returns the day an AR asset pipeline exists. CARRY-OVER (W1b ruling 6, ${OUT}/waves/w1b/rulings-fable.md): in the proposals list/detail, an accepted-but-unsigned proposal shows checkmark.circle with "Accepted"; checkmark.seal.fill is reserved for signed_at present — one glyph change in lane B's former files (Features/Proposals/**), which are yours for this one edit; pin it with a test. Delete or rewrite the tests that pinned the deleted views (CompanionActionMatrixTests.homeStudioRow*, DailyRoomFeedMappingTests if they test the retired feed — keep any case that still tests live code). Append a dated "§5 — July home rail retired (ruling Q4, 2026-08-27)" note to ${R}/11-canon-digest.md listing what was deleted and why (write it via an integration note if the steward's map says research/ is outside your worktree — it is in the main checkout, so write it directly, it is not a git-tracked file in your worktree). Gate: build + the whole PatinaTests tier on your clone.` : ''}
${l.key === 'd' ? `D SPECIFICS. Read ${W}/steward.md's project_rooms answer and ${OUT}/waves/w1b/rulings-fable.md (rulings 2 and 4 are yours). Mint 00537_house_on_today.sql: ALTER TABLE rooms ADD COLUMN IF NOT EXISTS budget_cents integer; ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_seen_at timestamptz; the project_rooms client-scoped SELECT policy ONLY if the steward proved it missing (TO authenticated, USING the project's client_id = auth.uid() through the existing join); saved_items de-duplication (keep the earliest row per key) followed by two partial unique indexes — (user_id, product_id) WHERE room_id IS NULL and (user_id, product_id, room_id) WHERE room_id IS NOT NULL — read 00535 and the saved_items shape first; comments on each column. Mint 00538_client_account_anonymize.sql: rewrite purge_client_account(uuid) per ruling 2 — tombstone the client's profiles PII, detach/delete the auth user via the existing handler contract, re-point client identity on designer-owned rows (proposals, client_decisions, invoices, projects, designer_clients roster) to the tombstone (respecting the authority guards — use the sanctioned set_document_client path where the guards demand it, as d-notes §6(b) documents), delete only client-owned artefacts (rooms, room_scans, saved_items, threads the client started); keep the designer-caller refusal; update supabase/functions/delete-account if its contract changes; account_purge_test.sql asserts designer rows survive and client PII is gone. pgTAP cases for every item; supabase db reset (unsandboxed — you own the DB this wave) replays clean; deno test for delete-account; regen packages/supabase/src/database.types.ts with the repo's documented command. Re-check ls supabase/migrations | tail before your final commit; renumber if 00537/00538 collided. Gate output pasted.` : ''}
${l.key !== 'd' && l.key !== 'r3' ? 'GATE (unsandboxed, foreground): ios-gate.sh build (run twice if the first fails on GitCommit.swift); xcodebuild test -only-testing:PatinaTests on your clone with -derivedDataPath .build/dd — the whole tier must pass; no ios-gate.sh all / lint-delta (steward-only). Build a properly signed .app at the end and record its path.' : ''}
INTEGRATION NOTES → ${W}/${l.key}-notes.md (file, exact diff, why). FINISH: rmdir .writer.lock.d; git log --oneline main..HEAD; git status --porcelain -uno empty. Return ok, commits, gate, tasks_file, notes_file, app_path / migrations, notes, failures.`

const laneResults = await parallel(LANES.map(l => () => safe(l.key, agent(laneBrief(l), { label: `lane ${l.key}`, phase: 'Lanes', model: l.model, effort: l.model === 'opus' ? 'high' : undefined, schema: REPORT }))))
log(`Lanes: ${LANES.map((l, i) => `${l.key}:${laneResults[i] ? laneResults[i].ok : 'NULL'}`).join(' ')}`)

phase('Reviews')
const reviews = await parallel(LANES.map((l, i) => () => laneResults[i] && laneResults[i].ok ? safe(`rev ${l.key}`, agent(`${COMMON}

ROLE: adversarial reviewer of lane ${l.name} (W2), separate context. Read-only: git -C ${wt(l.key)} diff main...HEAD, git -C ${wt(l.key)} log --oneline main..HEAD, ${W}/${l.key}-tasks.md, ${W}/${l.key}-notes.md if present, and the implementer's report: ${JSON.stringify({ commits: laneResults[i].commits, gate: laneResults[i].gate, notes: laneResults[i].notes, failures: laneResults[i].failures })}. Do not build; do not commit.
Check against build-plan.md §W2, direction-b §1/§2/§3, the M1/M2/M6d screen sheets, the synthesis grafts (draw nothing when nothing moved at guest/discovering; empty-queue Next Move names the phase; card weight follows content; six-hour suppression), and the honesty rules: does every row come from a real event with its real date; is "new" derived from LastSeenStore and never fabricated; are the empties tier-correct; does the record never count days at the person; is the snapshot painted first; is the App Group handled when nil; are R1's interfaces exactly the published names; per-tier composition exactly direction-b §2; VoiceOver labels; dark + XXL; tests real and failing-without-the-change; existing suites green per the gate output; no edits outside owned files; Conventional Commits with pathspecs; anything the report claims that the diff does not show. (R3: is every deletion proven by the call graph; does any live surface lose a piece; are tests adjusted, not silenced.) (D: additive-only; policy scope; regen done.) Write ${W}/${l.key}-review.md. Report every finding with severity + confidence; do not filter.`, { label: `review ${l.key}`, phase: 'Reviews', model: l.reviewer, effort: l.reviewer === 'opus' ? 'high' : undefined, schema: REV })) : Promise.resolve(null)))
log(`Reviews: ${LANES.map((l, i) => `${l.key}:${reviews[i] ? `${reviews[i].blocking.length}/${reviews[i].major.length}/${reviews[i].minor.length}` : '-'}`).join(' ')}`)

phase('Fix')
const fixes = await parallel(LANES.map((l, i) => () => (reviews[i] && (reviews[i].blocking.length || reviews[i].major.length)) ? safe(`fix ${l.key}`, agent(`${laneBrief(l)}

FIX ROUND (replaces "TASK LIST FIRST"): the lane is implemented on ${br(l.key)} in ${wt(l.key)}; read ${W}/${l.key}-review.md; address EVERY blocking and major (change the code, or rebut in ${W}/${l.key}-fix-log.md with evidence); take cheap minors; re-run the lane's gate; pathspec-commit each fix. Findings: blocking=${JSON.stringify(reviews[i].blocking)} major=${JSON.stringify(reviews[i].major)}`, { label: `fix ${l.key}`, phase: 'Fix', model: l.model, effort: l.model === 'opus' ? 'high' : undefined, schema: REPORT })) : Promise.resolve(null)))

phase('Integrate')
const integ = await safe('integrate', agent(`${COMMON}

ROLE: steward — integrate W2. Read ${W}/steward.md, every ${W}/<lane>-review.md, -fix-log.md and -notes.md. Lane reports: ${JSON.stringify(LANES.map((l, i) => ({ lane: l.key, impl: laneResults[i] && { ok: laneResults[i].ok, commits: laneResults[i].commits }, fix: fixes[i] && { ok: fixes[i].ok, commits: fixes[i].commits } })))}.
Unsandboxed: git -C ${ROOT} worktree add ${ROOT}/.codex/worktrees/agent-dr-w2-integration -b daily-return/integration main (if the branch exists from W1b, delete it first: it is merged); copy Secrets.swift; mkdir .writer.lock.d; clone + boot "dr-w2-int". Merge d → r1 → r3 → r2 (subjects "chore(daily-return): integrate w2 lane <x>" — the hook rejects "merge:"); resolve conflicts by intent; apply every integration note. Migrations: check the tip, renumber if needed, supabase db reset (unsandboxed), pgTAP, regen types if stale. iOS: ios-gate.sh build; the whole PatinaTests tier on your clone; ios-gate.sh lint-delta main; signed .app. Write ${W}/integration.md. Return ok only if every gate is green.`, { label: 'integrate', phase: 'Integrate', model: 'opus', effort: 'high', schema: REPORT }))

phase('Walk')
const walk = integ && integ.ok ? await safe('walk', agent(`${COMMON}

ROLE: walker — W2 acceptance on ${REVIEW_UDID}. Read ${W}/integration.md and the "Acceptance:" paragraph of build-plan.md §W2 — that is your script — plus direction-b §1 "The day" (7:40 Walt / 12:30 Ruth / 9:10 Maya / two weeks away). Unsandboxed: install ${integ.app_path}; terminate + launch with -DeploymentTarget local. Accounts per ${R}/02-steward-boot.md §6–§7 (client@patina.dev activeProject; james.okafor@example.com engaged; guest; a discovering account if the steward named one). For the two-weeks header: set the UserDefaults key patina.house.lastSeenAt on the simulator container to 14 days ago (xcrun simctl spawn <udid> defaults write cloud.patina.app patina.house.lastSeenAt -date <iso>) and relaunch. For a "new" tick: set it to yesterday, relaunch. Blitz taps per §5. CARRY-OVER (W1b re-walk): the push primer was never observed firing — for client@patina.dev, ensure at least one client-facing proposal/invoice/decision notification row exists (run notify_client_attention unsandboxed if the seed has none), relaunch, and capture the primer (SP-08's sentence verbatim) or record exactly why it did not appear. CARRY-OVER (W1b ruling 8): at Dynamic Type XXL also shoot the proposal detail scrolled to "Sign proposal" (is the button clear of the Companion?), a decision detail, Budget, and an invoice detail — PASS/FAIL each. Capture w2-NN-slug.png per script line (light, dark, XXL for the home at each tier), ledger rows under "## w2 walk", ${W}/walk.md with PASS/FAIL per item and verbatim copy for every FAIL. Leave the simulator signed in as client@patina.dev on the Daily Room. Return ok = every item PASS.`, { label: 'walk', phase: 'Walk', model: 'sonnet', schema: REPORT })) : null

return {
  setup: setup.notes,
  lanes: LANES.map((l, i) => ({ lane: l.key, impl: laneResults[i] && { ok: laneResults[i].ok, commits: laneResults[i].commits, gate: laneResults[i].gate, failures: laneResults[i].failures }, review: reviews[i] && { blocking: reviews[i].blocking, major: reviews[i].major, minor_n: reviews[i].minor.length }, fix: fixes[i] && { ok: fixes[i].ok, commits: fixes[i].commits, failures: fixes[i].failures } })),
  integration: integ && { ok: integ.ok, gate: integ.gate, app_path: integ.app_path, migrations: integ.migrations, notes: integ.notes, failures: integ.failures },
  walk: walk && { ok: walk.ok, notes: walk.notes, failures: walk.failures },
}
