export const meta = {
  name: 'ios-daily-return-w4-deck',
  description: 'Art-direct the deck, build the phone mocks for both directions and the shared planks, author the deck parts, build presentation.html, fact-check and render-QA it',
  phases: [
    { title: 'Art direction', detail: 'deck head CSS, build script, style guide for part authors' },
    { title: 'Mocks', detail: 'Direction A ∥ Direction B ∥ shared/iOS return surfaces — CSS phone fragments + screen sheets' },
    { title: 'Parts', detail: 'ten deck sections authored in parallel, ≤30k chars each' },
    { title: 'Build + check', detail: 'build.mjs → presentation.html → fact-check ∥ rendered QA' },
    { title: 'Fix', detail: 'one repair pass, rebuild, re-render' },
  ],
}

const ROOT = '/Users/kody/Code/patina-merged'
const OUT = `${ROOT}/artifacts/ios-daily-return-2026-08-26`
const R = `${OUT}/research`
const S = `${OUT}/source`
const MOCK = `${OUT}/mock`
const PARTS = `${MOCK}/deck-parts`
const FRAG = `${MOCK}/fragments`
const DECK = `${OUT}/presentation.html`

const COMMON = `You are one agent in an autonomous multi-agent review program ("The Daily Return") of the Patina iOS CLIENT app. The orchestrator reads only your structured return and your files on disk.
Ground rules: output root ${OUT}; never write to the session scratchpad; no git commit/add/stash/checkout; no app-source edits; no prod. Brand voice per ${ROOT}/.claude/skills/patina-brand-voice/SKILL.md (decks: Playfair headlines, Inter body, DM Mono labels; understatement over exclamation; technology silent; designers are the intelligence layer). Honesty rules: ${S}/instruments.md §11 (the panel is simulated and the deck says so; evidence levels labelled sim-verified / code-read / inferred; no invented numbers; every F## resolves to ${R}/31-verified-findings.json).
Inputs you may need: the kit ${MOCK}/kit.css + ${MOCK}/KIT.md (class names, tokens, phone frame, iOS system set, deck utilities; read KIT.md fully before drawing anything); directions ${S}/direction-a.md and ${S}/direction-b.md (each ends with a "Mock manifest" — the screens, block order, verbatim labels, and screen sheets); ${S}/shared-planks.md; judges ${S}/judge-*.md; THE REVIEW LEAD'S SYNTHESIS ${S}/synthesis.md (the verdict, the three rulings, the grafts — the recommendation section presents this, attributed to the review lead; the cover's thesis sentence comes from it); findings ${R}/36-findings-by-theme.md, ${R}/31-verified-findings.md; panel reports ${R}/2x-panel-*.md; walk evidence ${R}/01-shot-ledger.md, ${R}/03-walk-observations.md, shots in ${OUT}/shots; grounding ${R}/10-code-anatomy.md, ${R}/12-backend-reality.md, ${R}/11-canon-digest.md, ${R}/17-gap-fills.md; plan + assumptions ${S}/plan.md; instruments ${S}/instruments.md (§9 mock spec, §10 deck outline + design plan).
Your FINAL action must be the StructuredOutput tool call, even on failure.`

const safe = async (label, p) => { try { const r = await p; if (!r) log(`${label}: returned null`); return r } catch (e) { log(`${label}: threw ${e && e.message ? e.message : e}`); return null } }
const FILES = { type: 'object', required: ['files', 'notes'], properties: { files: { type: 'array', items: { type: 'string' } }, notes: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }

phase('Art direction')
const ad = await safe('AD', agent(`${COMMON}

ROLE: art director + build engineer. Load the Skill "artifact-design" first (it governs artifacts) and follow it; the deck must survive the Artifact CSP (external hosts blocked except https://fonts.googleapis.com / fonts.gstatic.com; data: URIs fine; ≤ 16 MB; light AND dark designed with the three-state token pattern; body paints its own background; no horizontal page scroll — wide content scrolls inside its own container; a real <title>).
Read instruments §10 (design plan: the deck's spine is A DAY — Morning · Midday · Evening · Two weeks later — encoded in the eyebrow, not numbered markers; palette from the app's ground #FAF7F2 / #2C2926 / #5C4A3C / #C4A57B plus one deck-only evidence ink; Playfair Display / Inter / DM Mono; phone mocks are the hero; evidence shots sit in a visibly different register from proposals; no emoji markers, no accent rails on rounded cards, no everything-centered). Study the previous deck in this series for lineage, not to copy: ${ROOT}/artifacts/document-wayfinding-directions-2026-08-25/presentation.html (its .dk-* chrome, the evidence/analysis register device, its build.mjs at mock/deck-parts/build.mjs and qa-run.cjs).
Deliver:
1. ${PARTS}/00-head.html — <title>The Daily Return</title>, the Google Fonts link, and ALL deck CSS: tokens (light on :root; dark under @media (prefers-color-scheme: dark) guarded :root:not([data-theme="light"]) and again under :root[data-theme="dark"]); the two registers (.reg-paper for analysis/proposal, .reg-dark for evidence — both fully themed); the day-spine eyebrow (.hour: DM Mono, e.g. "07:40 · MORNING"); a sticky top index (.dk-index) with anchors for every section; a 12-column asymmetric layout (.dk-grid — prose cols 1–5, frames cols 6–12 at ≥1100px; stacked below); phone-frame wrappers that scale the 402×874 .frame to fit (.frames-2, .frames-3 side by side at ≥1100, CSS zoom/transform scale at narrower widths — the frame must never overflow the viewport); the screen-sheet layout (.sheet-table beside or under its frame, with the "new vs today" cell visibly marked); evidence figure (.ev-fig with a shot image + DM Mono caption + level chip sim-verified/code-read/inferred); finding chips (.f-chip F##, severity-tinted, semantic colours separate from the accent); persona quote block (.voice with the seat name + role line); judge scoreboard table; compare table; plank list; question cards; colophon; print styles; :focus-visible; prefers-reduced-motion. Do NOT include kit.css here — build.mjs inlines it before the deck CSS; namespace deck classes with dk- or the names above so nothing collides with kit classes.
2. ${PARTS}/99-script.html — a small inline script: index highlighting on scroll, smooth anchor scroll (disabled under reduced motion), a light/dark toggle that stamps data-theme on <html> (default = system), keyboard focus management. No external requests.
3. ${PARTS}/build.mjs — Node ESM: concatenates parts in a fixed order [00-head, 01-cover, 02-ask, 03-today, 04-panel, 05-found, 06-why-return, 07-why-buy, 08-planks, 09-direction-a, 10-direction-b, 11-purchase, 12-compare, 13-recommendation, 14-questions, 15-colophon, 99-script]; resolves <!-- include:fragments/NAME.html --> markers by inlining ${FRAG}/NAME.html; resolves <!-- shot:FILE.png --> and <img data-shot="FILE.png"> to base64 JPEG data URIs after downscaling with sips to 804 px wide (write temp JPEGs to ${MOCK}/deck-assets/, quality 78) — budget: warn if total > 12 MB, fail if > 15.5 MB; inlines ${MOCK}/kit.css and the ${MOCK}/img/*.jpg crops the fragments reference (rewrite their src to data URIs); writes ${DECK}; prints the size and a manifest of included shots/fragments; exits non-zero on a missing include. Run it once now with placeholder parts (write minimal stubs for every part so the build passes) to prove it works.
4. ${PARTS}/DECK.md — the style guide for the ten part authors: the exact markup for a section (id, .hour eyebrow, h2, lede), how to place one/two/three frames with sheets, how to embed a shot with its level chip, how to cite a finding chip and a seat quote, the register rules, the voice rules, the size budget per part (≤ 30k chars of HTML), the section list with anchors and the day-spine assignment (which sections are Morning / Midday / Evening / Two weeks later), and a checklist.
Return files + notes (include the build command).`, { label: 'art director', phase: 'Art direction', model: 'opus', effort: 'high', schema: FILES }))
if (!ad) return { ad }

phase('Mocks')
const MOCKS = { type: 'object', required: ['fragments', 'notes'], properties: { fragments: { type: 'array', items: { type: 'object', required: ['file', 'screen'], properties: { file: { type: 'string' }, screen: { type: 'string' }, dark_variant: { type: 'string' } } } }, notes: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }
const mockBrief = (who, source, prefix, extra) => `${COMMON}

ROLE: mock builder — ${who}. Read ${MOCK}/KIT.md fully, then ${source} (its "Mock manifest" is your spec: block order, verbatim labels, existing vs new components, screen sheets), then instruments §9. Draw every screen in the manifest as an HTML fragment ${FRAG}/${prefix}-M<n>.html containing exactly one .frame (402×874 kit phone frame, status bar 9:41, Dynamic Island, home indicator, the Companion orb where the app shows it) using ONLY kit classes plus a small <style> block scoped under a unique root class for anything the kit lacks (name the additions in your notes so KIT.md can absorb them); real seed content only (names, prices, makers, the editorial story, the walk accounts' projects/invoice) — never lorem, never a stock photo; use the ${MOCK}/img crops or the kit's honest placeholder tile. Add numbered callouts (.callout-n) on each frame that key to the screen sheet. Write a matching ${FRAG}/${prefix}-M<n>.sheet.html fragment containing the screen sheet as a .sheet-table (purpose · entry points · components existing/new · copy · data source · states · interactions + analytics events · tier behaviour · new vs today) with the callout numbers referenced. Dark variants: ${extra} — set data-scheme="dark" on that fragment's frame. Render-check your own work: write ${FRAG}/_preview-${prefix}.html that includes kit.css + all your fragments side by side, render it with Playwright (chromium from ${ROOT}/apps/designer-portal/node_modules/@playwright/test, 2x; unsandboxed only if the sandboxed launch fails) to ${FRAG}/_preview-${prefix}.png, LOOK at the PNG, and fix overflow, clipped text, wrong tokens, or any screen that does not read as the real app. Report every fragment + what remains imperfect.`
const [ma, mb, ms] = await parallel([
  () => safe('MA', agent(mockBrief('Direction A', `${S}/direction-a.md`, 'a', 'the home at discovering and the piece detail, at minimum'), { label: 'mocks A', phase: 'Mocks', model: 'opus', effort: 'high', schema: MOCKS })),
  () => safe('MB', agent(mockBrief('Direction B', `${S}/direction-b.md`, 'b', 'the home at discovering and the piece detail, at minimum'), { label: 'mocks B', phase: 'Mocks', model: 'opus', effort: 'high', schema: MOCKS })),
  () => safe('MS', agent(mockBrief('shared planks + iOS return surfaces', `${S}/shared-planks.md (draw the planks that are visual — at least: the repaired piece detail with dimensions/lead time/maker story, the Saved that holds a piece and a board, the notification-permission moment with its pre-permission copy, the share card a partner receives; plus the iOS return surfaces both directions cite: a Lock Screen push banner, a small and a medium Home Screen widget, a Live Activity for a delivery, drawn with the kit's iOS system set — take the copy from the direction docs, section 4)`, 's', 'the widget pair and the push banner'), { label: 'mocks shared', phase: 'Mocks', model: 'opus', effort: 'high', schema: MOCKS })),
])
log(`Mocks: A ${ma ? ma.fragments.length : 'NULL'} · B ${mb ? mb.fragments.length : 'NULL'} · S ${ms ? ms.fragments.length : 'NULL'}`)
const fragIndex = { a: ma ? ma.fragments : [], b: mb ? mb.fragments : [], s: ms ? ms.fragments : [] }

phase('Parts')
const PART = { type: 'object', required: ['file', 'chars', 'findings_cited', 'shots_used'], properties: { file: { type: 'string' }, chars: { type: 'number' }, findings_cited: { type: 'array', items: { type: 'string' } }, shots_used: { type: 'array', items: { type: 'string' } }, notes: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }
const partBrief = (file, hour, what, model) => ({ file, hour, what, model })
const parts = [
  partBrief('01-cover.html', 'DAWN', 'Cover: the name "The Daily Return", the subtitle (the Patina iOS app, reviewed by three homeowners, three interior designers and three UX/UI practitioners — simulated, and said so), the date, the provenance (main 3cd84ecb3, iPhone 17 Pro simulator, local stack), and the thesis in one sentence drawn from the judges. Then 02-ask.html: Kody\'s ask verbatim, the six assumptions from plan.md, what evidence was and was not available (no usage data, no prod counts, no device), and the reading guide (registers, level chips, the day spine).', 'opus'),
  partBrief('03-today.html', '07:40 · MORNING', 'The app today: the anatomy in one picture (a diagram or structured figure of the home\'s four modules, the Companion as the only nav, the Studio two acts deep, the tiers — from 10-code-anatomy A1/A2/A20) and a strip of 8–12 evidence shots (guest home, client home, browse grid, the product-detail trap, Saved, room, Studio hub, proposal, invoice, dark home) each with a one-line caption and level chip; then "what changes between two mornings" as a short table (date string · story · Next Move · bell) with the code-read citations.', 'sonnet'),
  partBrief('04-panel.html', '07:40 · MORNING', 'The panel: nine seat cards (name, town, one line of who they are, the question they asked of the app, their one-sentence verdict from the panel reports\' closing lines); the task script T1–T14 as a compact table; the method in four lines (walk → findings → three refuters → what survived: give the real counts from 31-verified-findings and 32-refuted-findings).', 'sonnet'),
  partBrief('05-found.html', '12:30 · MIDDAY', 'What we found: the themes from 36-findings-by-theme.md (return · purchase · trust · wayfinding · content · reach), each with its top findings as chips, one or two evidence shots, and one verbatim seat quote (.voice); then "the twelve that matter most" as a ranked list with severity and the seats that raised each. Be concrete and unsparing; this is the section Kody will read twice. ≤ 30k chars — if the material is bigger, split into 05-found.html and 05b-found.html and tell the builder in your notes (the builder concatenates in name order).', 'opus'),
  partBrief('06-why-return.html', '21:10 · EVENING', 'Why people would return: the honest rituals — from U1\'s ranked mechanics and the H seats\' "three things that would make me open this every day" — as a comparison of what the app offers at each hour today vs what the directions offer (7:40 Walt · 12:30 Ruth · 9:10 Maya · two weeks later), with the rejected manipulative mechanics named in a small sidebar. Cite findings. Include the shared iOS return-surface mocks (widgets, push banner, Live Activity) via include markers from fragIndex.s where relevant.', 'opus'),
  partBrief('07-why-buy.html', '21:10 · EVENING', 'Why people would buy here: the purchase dead end today (verbatim, with the shot), what already exists on the backend (direct_orders, hosted Checkout with Apple Pay, receipts) and what does not (designer attribution, order status beyond paid), the Apple rule (physical goods → external payment, no IAP), Walt\'s pre-payment checklist and D3\'s after-purchase checklist from the U3/D3 reports, and the three purchase paths by tier as a table.', 'opus'),
  partBrief('08-planks.html', 'ANY HOUR', 'Shared planks: from shared-planks.md — a list with id, title, findings answered, size, backend delta; the visual planks get their fragments (include markers from fragIndex.s: the repaired piece detail, Saved that holds a piece, the permission moment, the share card) with their sheets.', 'sonnet'),
  partBrief('09-direction-a.html', 'THE DAY, VERSION A', 'Direction A: name, thesis, the day (what is on the first screen at each hour), home per tier, remembered investment, return surfaces, designer in the home, what it declines and what that costs, first slice → waves, risks, rollback — then every A mock frame (include markers from fragIndex.a, two or three frames per row) each with its screen sheet fragment beside/under it. Keep the author\'s section order; compress prose, never the sheets.', 'opus'),
  partBrief('10-direction-b.html', 'THE DAY, VERSION B', 'Direction B: same structure as Direction A, plus the amendments table (B-n amends C# — what · why · cost · rollback) rendered prominently, and every B mock frame with its sheet (fragIndex.b).', 'opus'),
  partBrief('11-purchase.html', 'THE PURCHASE', 'The purchase path in both directions side by side: the order state machine, where money is taken, what the designer sees, the Apple compliance line, the backend deltas, and the purchase-flow frames from both directions (fragIndex.a / fragIndex.b purchase screens) with sheets.', 'sonnet'),
  partBrief('12-compare.html', 'THE VERDICT', 'Compare + judges: the J1/J2/J3 scoreboards (never averaged), the grafts each judge names, a compare table built from synthesis.md §3 (the home · navigation · Buy with a designer engaged · guest/discovering mornings · first slice, with the canon row each touches), and the judges\' verdict sentences. Then 13-recommendation.html: synthesis.md §2 and §4 rendered faithfully — "what the two directions share" (the six shared items + the repair planks), the verdict ("build A\'s first slice as B\'s W1, and put the three real differences to Kody with the slice in hand"), the three rulings with the recommendation for each, a "now / ruling 1 / ruling 2 / ruling 3" sequence, the grafts list (§5), and §6 "what this review could not settle". Attribute it to the review lead.', 'opus'),
  partBrief('14-questions.html', 'FOR KODY', 'Ten questions for Kody — each a card: the question, why it is his to rule (cite C#/R#/F##), the options with our recommendation first, what each costs. The first three cards ARE synthesis.md §4\'s three rulings (the home C23 vs B-3/B-4; the tab bar C1 B-1/B-2; Buy with a designer engaged + the R32 sequence), worded as there. Must also include: the C2-vs-C23 home ruling (Option B\'s four modules vs the marketplace rail), designer attribution on direct orders, order status beyond paid (migration), the notification-permission moment, widgets (a new target), household/partner, the tab-bar re-evaluation (R29), the product-detail trap hotfix, the Stripe live-vs-test question, and the local-stack restart. Then 15-colophon.html: evidence inventory (shots count, routes without shots, what is sim-verified vs code-read), workflow run ids from plan.md and the orchestrator notes, the simulated-panel disclosure, and the program folder path.', 'sonnet'),
]
const partResults = await parallel(parts.map(p => () => safe(p.file, agent(`${COMMON}

ROLE: deck part author — ${p.file} (day-spine eyebrow: "${p.hour}"). Read ${PARTS}/DECK.md first and follow it exactly (markup, classes, registers, size budget ≤ 30k chars per file, include markers). Write ${PARTS}/${p.file} (and the second file if the brief names one). Content: ${p.what}
Fragment index (use the include marker form DECK.md prescribes; every fragment listed has a matching .sheet.html): ${JSON.stringify(fragIndex)}
Every claim cites a finding chip (F##) or an evidence figure with its level chip; every number traces to a research file; quotes are verbatim from the panel reports; copy in the voice. Return chars written, the F## cited, and the shots used (filenames in ${OUT}/shots).`, { label: p.file, phase: 'Parts', model: p.model, effort: p.model === 'opus' ? 'high' : undefined, schema: PART }))))
log(`Parts: ${partResults.map((r, i) => `${parts[i].file.split('-')[0]}:${r ? r.chars : 'NULL'}`).join(' ')}`)

phase('Build + check')
const BUILD = { type: 'object', required: ['ok', 'size_bytes', 'notes'], properties: { ok: { type: 'boolean' }, size_bytes: { type: 'number' }, notes: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }
const build = await safe('build', agent(`${COMMON}

ROLE: builder. Run the build (${PARTS}/build.mjs — read it and DECK.md for the part order; parts written as 05b etc. must be included in name order) to produce ${DECK}. Fix build-breaking problems in parts (a missing include, a malformed marker, an unclosed tag that breaks a following section) minimally; do not rewrite content. Report size, included shots/fragments, and anything you had to touch.`, { label: 'build', phase: 'Build + check', model: 'sonnet', schema: BUILD }))
log(`Build: ${build ? `${build.ok} ${Math.round((build.size_bytes || 0) / 1024)} KB` : 'NULL'}`)

const CHECK = { type: 'object', required: ['file', 'blocking', 'major', 'minor'], properties: { file: { type: 'string' }, blocking: { type: 'array', items: { type: 'string' } }, major: { type: 'array', items: { type: 'string' } }, minor: { type: 'array', items: { type: 'string' } }, renders: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }
const [fact, qa] = await parallel([
  () => safe('fact', agent(`${COMMON}

ROLE: fact-checker of ${DECK} (read the deck parts in ${PARTS} rather than the built file where easier). Verify: every F## chip exists in ${R}/31-verified-findings.json with the same title/severity gist and is not in 32-refuted; every number (counts, prices, dates, tap counts, scores) traces to a research/source file — list each with its source or mark it unsupported; every shot referenced exists in ${OUT}/shots; every seat quote is verbatim in a panel report; every screen-sheet copy line matches its direction doc; the simulated-panel disclosure appears on the ask page and colophon; no claim of device verification; no invented usage numbers; the Apple-guideline and Stripe statements match 17-gap-fills G2 and 12-backend-reality; canon citations (C#, R#) match instruments §6/§6b and the digest. Write ${R}/60-deck-factcheck.md with blocking / major / minor lists (each: part file, the line, the problem, the fix).`, { label: 'fact-check', phase: 'Build + check', model: 'opus', effort: 'high', schema: CHECK })),
  () => safe('qa', agent(`${COMMON}

ROLE: rendered QA. Write ${PARTS}/qa-run.cjs modelled on ${ROOT}/artifacts/document-wayfinding-directions-2026-08-25/mock/deck-parts/qa-run.cjs (Playwright chromium from ${ROOT}/apps/designer-portal/node_modules/@playwright/test; run sandboxed first, unsandboxed only if launch fails for a sandbox reason). Open file://${DECK} at 1440×900 and 390×844, in light and dark (emulate prefers-color-scheme; also test the toggle stamping data-theme); capture every section to ${MOCK}/deck-qa/<section>-<viewport>-<theme>.png; record: document.body.scrollWidth vs viewport (no horizontal scroll allowed), console errors, page errors, blocked/external requests (only fonts.googleapis/gstatic allowed), fonts actually loaded (document.fonts), file size, the <title> in the first 8 KB, any element whose bounding box exceeds the viewport width, any .frame that overflows its wrapper, text contrast samples on both registers in both themes, sticky index behaviour. Then LOOK at the PNGs (Read them) and list visual defects: overlapping frames and sheets, clipped mock text, phone frames that do not scale at 390, dark-theme colours only defined in one theme (unreadable text), sections that lost their eyebrow, images that failed to inline. Write ${R}/61-deck-visualqa.md with blocking / major / minor lists (each: section, viewport, theme, the problem, the PNG, the fix).`, { label: 'rendered QA', phase: 'Build + check', model: 'opus', effort: 'high', schema: CHECK })),
])
log(`Check: fact ${fact ? `${fact.blocking.length}/${fact.major.length}/${fact.minor.length}` : 'NULL'} · qa ${qa ? `${qa.blocking.length}/${qa.major.length}/${qa.minor.length}` : 'NULL'}`)

phase('Fix')
const fix = await safe('fix', agent(`${COMMON}

ROLE: repair. Read ${R}/60-deck-factcheck.md and ${R}/61-deck-visualqa.md. Fix every blocking and major item at its source (a deck part in ${PARTS}, a fragment in ${FRAG}, the head CSS, or build.mjs), and the minors that are cheap; log each fix in ${R}/62-deck-revision-log.md (item → file → what changed). Rebuild with build.mjs; re-run ${PARTS}/qa-run.cjs and confirm: no horizontal scroll at 390 and 1440, no console/page errors, no blocked requests, size ≤ 16 MB, title present. Report what remains.
Fact-check summary: ${JSON.stringify(fact && { blocking: fact.blocking, major: fact.major })}
Visual QA summary: ${JSON.stringify(qa && { blocking: qa.blocking, major: qa.major })}`, { label: 'fix', phase: 'Fix', model: 'opus', effort: 'high', schema: { type: 'object', required: ['fixed', 'remaining', 'size_bytes'], properties: { fixed: { type: 'array', items: { type: 'string' } }, remaining: { type: 'array', items: { type: 'string' } }, size_bytes: { type: 'number' }, qa_renders: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } } }))
log(`Fix: ${fix ? `${fix.fixed.length} fixed, ${fix.remaining.length} remaining, ${Math.round((fix.size_bytes || 0) / 1024)} KB` : 'NULL'}`)

return {
  ad: ad && ad.notes, mocks: { a: fragIndex.a.map(f => f.file), b: fragIndex.b.map(f => f.file), s: fragIndex.s.map(f => f.file), notes: { a: ma && ma.notes, b: mb && mb.notes, s: ms && ms.notes } },
  parts: partResults.map((r, i) => ({ file: parts[i].file, chars: r ? r.chars : null, failures: r ? r.failures : ['null'] })),
  build, fact: fact && { file: fact.file, blocking: fact.blocking, major: fact.major, minor_n: fact.minor.length }, qa: qa && { file: qa.file, blocking: qa.blocking, major: qa.major, minor_n: qa.minor.length, renders: qa.renders }, fix,
}
