export const meta = {
  name: 'daily-return-w4-fix',
  description: 'W4 fix round on the integration branch: server rooms hydrate the local store, Add to Room writes the room, the fit line is mounted — then review and a re-walk of the failed items',
  phases: [
    { title: 'Fix', detail: 'one Opus lane on daily-return/integration' },
    { title: 'Review', detail: 'separate-context review; majors fixed' },
    { title: 'Re-walk', detail: 'items 1, 4, 8 + a sign-out/sign-in room round trip' },
  ],
}
const ROOT = '/Users/kody/Code/patina-merged'
const OUT = `${ROOT}/artifacts/ios-daily-return-2026-08-26`
const S = `${OUT}/source`
const R = `${OUT}/research`
const W = `${OUT}/waves/w4`
const APP = `${ROOT}/apps/mobile/Patina`
const WT = `${ROOT}/.codex/worktrees/agent-dr-w4-integration`
const REVIEW_UDID = '973D1724-90BF-4A0A-B02D-481D561547B3'
const COMMON = `You are one agent in the Daily Return build program for the Patina iOS CLIENT app. Program folder ${OUT}; read ${S}/build-plan.md "Global constraints" and "### W4"; ${W}/walk.md (the failed items 1, 4, 8 and its "Open for Fable" list — your brief); ${W}/integration.md (§6 open items, the steward's dispositions); ${W}/h1-notes.md, ${W}/h2-notes.md; ${S}/shared-planks.md §SP-06, §SP-11, §SP-14 (rooms and saves are local-first with a server mirror; the guest's work is claimed on sign-in; a room synced to the server belongs to the account). Sandbox: xcodebuild, xcrun simctl, git worktree/merge, osascript, docker, sips and the supabase CLI need dangerouslyDisableSandbox: true; builds in the foreground; a first xcodebuild in a fresh tree may fail on GitCommit.swift — run twice. Pathspec commits only; never push; never git in the main checkout except read-only. Honesty (C5); brand voice (C6); both roots must render. FINAL action = StructuredOutput even on failure.`
const safe = async (label, p) => { try { const r = await p; if (!r) log(`${label}: returned null`); return r } catch (e) { log(`${label}: threw ${e && e.message ? e.message : e}`); return null } }
const REPORT = { type: 'object', required: ['ok', 'notes'], properties: { ok: { type: 'boolean' }, commits: { type: 'array', items: { type: 'string' } }, gate: { type: 'string' }, app_path: { type: 'string' }, notes: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }
const REV = { type: 'object', required: ['file', 'blocking', 'major', 'minor'], properties: { file: { type: 'string' }, blocking: { type: 'array', items: { type: 'string' } }, major: { type: 'array', items: { type: 'string' } }, minor: { type: 'array', items: { type: 'string' } } } }

phase('Fix')
const fix = await safe('F', agent(`${COMMON}

ROLE: F — close the three walk failures on branch daily-return/integration in ${WT} (verify git rev-parse --show-toplevel; mkdir .writer.lock.d — stop if it exists). Create + boot a fresh iPhone 17 Pro / iOS 26.5 device "dr-w4-fix" (unsandboxed simctl create; never ${REVIEW_UDID}); -derivedDataPath ${WT}/.build/dd. Write ${W}/fix-tasks.md first (writing-plans format), then one Conventional Commit per item with pathspecs:
1. ROOMS HYDRATE FROM THE SERVER (walk item 1 + the vanished-room evidence). RoomsAPIClient.listRooms() has zero call sites. Add a reconcile in RoomStore (or a RoomSyncCoordinator beside RoomCreationCoordinator): on sign-in completion and on Your Spaces / Daily Room appear (debounced), fetch the account's rooms and merge by remoteId into the local SwiftData store — server rows the store lacks are created locally (dimensions, budget_cents, name, updated_at), local rows already mirrored keep local edits newer than the server's updated_at, local-only rows (never synced) are untouched; the guest's unclaimed rooms are never merged into an account (SP-06). The house rail, Your Spaces and the room screen then show D's seeded "Guest Bedroom" and a room typed in-session survives a sign-out/sign-in. Tests: merge rules (server-only, local-newer, guest-unclaimed), idempotency, no duplicates by remoteId.
2. ADD TO ROOM WRITES THE ROOM (walk item 4). ProductDetailView's "Add to Room" (≈:443) only toggles the generic save. Wire the live AddToRoomSheet's chosen room into the save path: TableItemModel.roomId set locally AND saved_items.room_id in the mirror (SP-14's CreateSavedItemPayload already carries the column — verify), so SavedRowMeta draws "· <Room>" and the room-scoped Saved (.roomSavedItems) lists it; a save from a room-scoped Browse (roomEmergence) defaults to that room. Tests: the payload carries room_id; the row meta draws the room; room-scoped Saved filters by it.
3. MOUNT THE FIT LINE (walk item 8). RoomFitLine exists with zero call sites; mount it on the piece detail under the dimensions (and it will also be read by W5's order sheet) — draws only when a room measured with the unit control (measuredWithUnitControl) exists and the product has dimensions; numbers only, no promise. Test: mounted-when-qualifying, absent otherwise (SourcePin + a view test if the harness allows).
4. RULED ITEMS from ${W}/integration.md §6 (the orchestrator's dispositions — implement, each its own commit): (§6.2) apply D's two UPDATEs from ${W}/d-notes.md §4 to the seed so both project_rooms carry real budget_cents/committed_cents, then supabase db reset; (§6.3) RoomBudgetBar / BudgetAssessment: when the room stores a budgetCents, the bar measures against THAT and prints "$X of $Y"; when it does not, the bar and the "Your range" line are NOT drawn — the hard-coded $2K–$5K range is deleted (C5; the quiz's band is a different number and stays where it is); (§6.4) the Spaces gallery card reads "Typed, not scanned" (F51) instead of "Manual entry"; the room screen prints its dimensions once — RoomHero's idiom stays, SpatialMetadataRow's duplicate line goes; (§6.5) "— ROOM MATCH" / "— MATCH" cells are dropped when no score exists (RoomGalleryCard.statCells); (§6.7) a phase fee of $0 draws no fee text; (§6.8) RoomStore.createRoom from ManualRoomEntryView sets measuredWithUnitControl = true (its fields are explicitly feet, typed on purpose); (§6.6, backend — 00539 is unmerged so edit it in place): last_seen_at must not be world-readable — create profile_presence(user_id uuid primary key references profiles, last_seen_at timestamptz) with RLS: owner SELECT/UPSERT, plus SELECT for the client's designer of record (the accepted lead's or active project's designer_id); drop the profiles.last_seen_at column added in 00537 if nothing else reads it (grep the repo + regen types), and point H2's mirror at the new table; SQL test for both policies. Leave the copy rulings that are not listed here alone. Correct ${R}/02-steward-boot.md §6(b)'s stale UUID for james.okafor@example.com at the source (read it from local auth.users) — a research file in the main checkout, edit directly.
GATE (unsandboxed, foreground): ${APP}/scripts/ios-gate.sh build; xcodebuild test -only-testing:PatinaTests on dr-w4-fix; ${APP}/scripts/ios-gate.sh lint-delta main; supabase db reset + ./scripts/run-sql-tests.sh (you own the DB); signed rebuild → app_path; install on dr-w4-fix and prove with shots ${OUT}/shots/w4-fix-NN-*.png: sign in as client@patina.dev → Your Spaces lists Guest Bedroom; type a room → sign out (Settings → Sign Out) → sign in → the room is still there; save a piece into a room → Saved shows "· <Room>" and the room's Saved lists it; a qualifying piece shows the fit line under its dimensions. rmdir the lock; delete the dr-w4-fix device at the end. Return ok, commits, gate, app_path, notes, failures.`, { label: 'F fix W4', phase: 'Fix', model: 'opus', effort: 'high', schema: REPORT }))
if (!fix || !fix.ok) return { fix }

phase('Review')
const rev = await safe('V', agent(`${COMMON}

ROLE: V — reviewer of the W4 fix round, separate context, read-only (git -C ${WT} log --oneline -6; git -C ${WT} show <sha> per commit; ${W}/fix-tasks.md; report ${JSON.stringify({ commits: fix.commits, gate: fix.gate, notes: fix.notes })}). Check: the room reconcile's merge rules (server-only rows created; local-newer edits kept; guest-unclaimed rooms never merged into an account; idempotent; no duplicate by remoteId; never blocks the UI; never deletes a local room the server lacks); Add to Room sets room_id locally and in the mirror and the room-scoped Saved reads it; the fit line's gate; no unrelated change; tests real; both roots render; pathspec Conventional Commits. Write ${W}/fix-review.md; every finding with severity + confidence.`, { label: 'V review', phase: 'Review', model: 'opus', effort: 'high', schema: REV }))
if (rev && rev.blocking.length) { log(`Review blocking: ${rev.blocking.join(' | ')}`); return { fix, rev } }
let fix2 = null
if (rev && rev.major.length) {
  fix2 = await safe('F2', agent(`${COMMON}

ROLE: F2 — close the review's majors on daily-return/integration in ${WT} (lock discipline; a fresh "dr-w4-fix2" device). Read ${W}/fix-review.md; majors: ${JSON.stringify(rev.major)}. Change or rebut in ${W}/fix2-log.md with evidence; re-run the gate exactly as F did; signed rebuild → app_path; pathspec commits; rmdir the lock; delete the device. Return ok, commits, gate, app_path, notes, failures.`, { label: 'F2 majors', phase: 'Review', model: 'opus', effort: 'high', schema: REPORT }))
  if (!fix2 || !fix2.ok) return { fix, rev, fix2 }
}
const finalApp = (fix2 && fix2.app_path) || fix.app_path

phase('Re-walk')
const walk = await safe('walk', agent(`${COMMON}

ROLE: walker — W4 re-walk on ${REVIEW_UDID}. Read ${W}/walk.md (the prior pass — re-verify items 1, 4 and 8 in full; the PASS items need only a sanity glance), ${W}/fix-review.md, and ${W}/fix2-log.md if present. Unsandboxed: xcrun simctl install ${REVIEW_UDID} ${finalApp}; terminate + launch with -DeploymentTarget local (flag off), and repeat item 1 with -PatinaFlags house-first. Script: client@patina.dev — Your Spaces and the house rail list D's seeded Guest Bedroom beside the two project rooms; type a room, sign out via Settings, sign in → the room is still there (psql: it exists in rooms with the client's user_id); save a piece into a room from the piece detail → Saved shows the date · room · note and the room's own Saved lists the piece; a qualifying piece (room measured with the unit control + product with dimensions) shows the fit line with two numbers; james.okafor's matched card still survives the 20-day manipulation (restore afterwards). Shots w4-NN (continue numbering), ledger "## w4 re-walk", REWRITE ${W}/walk.md as the final record (PASS/FAIL/BLOCKED per item; keep the prior pass as history). Delete any test rooms you created server-side. Leave the simulator signed in as client@patina.dev, flag off, on the Daily Room. You are a walker: NO git writes of any kind. Return ok = no FAIL.`, { label: 'walk', phase: 'Re-walk', model: 'sonnet', schema: REPORT }))
return { fix: { ok: fix.ok, commits: fix.commits, gate: fix.gate, app_path: fix.app_path, notes: fix.notes }, rev, fix2: fix2 && { ok: fix2.ok, commits: fix2.commits }, walk }
