export const meta = {
  name: 'daily-return-w4-fix3',
  description: 'W4 third round: root-cause why Today\'s rail never draws typed/mirrored rooms on the review device while Your Spaces does (fixer vs walker divergence), the XXL story/rail overlap, un-save on every surface, the Companion overlay\'s sheet chain — then review and the re-walk',
  phases: [
    { title: 'Diagnose + fix', detail: 'systematic debugging on the walker\'s exact sequence; then the four fixes' },
    { title: 'Review 3', detail: 'separate-context check' },
    { title: 'Re-walk', detail: 'items 1, 2, dark+XXL, un-save from Saved and Browse, the Companion sheet at XXL' },
  ],
}
const ROOT = '/Users/kody/Code/patina-merged'
const OUT = `${ROOT}/artifacts/ios-daily-return-2026-08-26`
const S = `${OUT}/source`
const R = `${OUT}/research`
const W = `${OUT}/waves/w4`
const APP = `${ROOT}/apps/mobile/Patina`
const WT = `${ROOT}/.codex/worktrees/agent-dr-w4-integration`
const REVIEW_UDID = '973D1724-90BF-4A0A-B02D-481D561547B3'
const COMMON = `You are one agent in the Daily Return build program for the Patina iOS CLIENT app. Program folder ${OUT}; read ${S}/build-plan.md "Global constraints"; ${W}/walk.md IN FULL (the final record — its two FAILs and the exact sequence the walker used, and the Appendix); ${W}/fix2-review.md (MAJ-1, MAJ-2 and the minors); ${W}/fix-tasks.md (the previous rounds' outcome sections, incl. the "first-session presentation stall" observation). Sandbox: xcodebuild, xcrun simctl, git worktree/merge, osascript, docker, sips and the supabase CLI need dangerouslyDisableSandbox: true; builds in the foreground; a first xcodebuild in a fresh tree may fail on GitCommit.swift — run twice; run the gate script FROM THE WORKTREE (${WT}/apps/mobile/Patina/scripts/ios-gate.sh — the main checkout's copy gates main). Pathspec commits only; never push; never git in the main checkout except read-only. Honesty (C5); SP-06; both roots must render. FINAL action = StructuredOutput even on failure.`
const safe = async (label, p) => { try { const r = await p; if (!r) log(`${label}: returned null`); return r } catch (e) { log(`${label}: threw ${e && e.message ? e.message : e}`); return null } }
const REPORT = { type: 'object', required: ['ok', 'notes'], properties: { ok: { type: 'boolean' }, commits: { type: 'array', items: { type: 'string' } }, gate: { type: 'string' }, app_path: { type: 'string' }, root_cause: { type: 'string' }, notes: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }
const REV = { type: 'object', required: ['file', 'blocking', 'major', 'minor'], properties: { file: { type: 'string' }, blocking: { type: 'array', items: { type: 'string' } }, major: { type: 'array', items: { type: 'string' } }, minor: { type: 'array', items: { type: 'string' } } } }

phase('Diagnose + fix')
const fix = await safe('F3', agent(`${COMMON}

ROLE: F3 — on branch daily-return/integration in ${WT} (verify git rev-parse --show-toplevel; mkdir .writer.lock.d — stop if it exists). Load Skill "superpowers:systematic-debugging" and follow it for item 1 — no fix before a reproduced root cause. Create + boot a fresh iPhone 17 Pro / iOS 26.5 device "dr-w4-fix3" (unsandboxed; never ${REVIEW_UDID}); -derivedDataPath ${WT}/.build/dd.
1. THE RAIL (walk FAIL 1 and 2). The walker, on the review device, never saw a typed or mirrored room on Today's YOUR HOUSE rail (only the two project_rooms cards) across a keychain-reset clean install → sign in as client@patina.dev, a sign-out/sign-in, and a cold terminate+relaunch, on both roots — while Your Spaces (an @Query on the same SwiftData store) listed the rooms every time. The previous fixer saw the seeded Guest Bedroom on the rail on ITS device (shots/w4-fix2-01). Reproduce the WALKER'S exact sequence on your fresh device first (xcrun simctl keychain reset; uninstall; install a signed build of the current tip; launch -DeploymentTarget local; sign in with password123; look at the rail without backgrounding). If it reproduces, instrument (os_log / a DEBUG dump of DailyRoomViewModel.roomModels vs RoomStore.allRooms() vs the rail's own filter) and find the divergence — candidates to check explicitly: (a) the rail's local-rooms source is owner-scoped (SP-06 account scoping in DailyRoomViewModel or HouseRoomCard) while insertMirrored/applyRemote never stamp ownerUserId on a mirrored room, so the rail hides what Spaces shows; (b) the rail draws only rooms that pass a shape filter (dimensions, image, syncState, measuredWithUnitControl) that a mirrored room fails; (c) the reconcile's revision fires before the view subscribes, or the 30 s debounce plus RoomSyncCoordinator.forget() ordering leaves the first load stale; (d) the rail reads a snapshot built before sign-in and reloadRooms() reads a different owner id than the one the rooms were stamped with; (e) the walker's build was not the tip (their note says "the tip-ba209c2a5 build already there was stale" — verify by codesign/commit stamp which sha they walked, and if the review device carried an older app, say so in root_cause — but still make the rail robust). Fix at the cause; add a test that reproduces the walker's sequence (fresh store, sign-in, hydrate, rail reload) and a SourcePin if the fix is a filter. Prove on glass on your device with the walker's sequence: the seeded Guest Bedroom on the rail in the sign-in session (w4-fix3-01), a typed room on the rail after sign-out/sign-in (w4-fix3-02), both roots.
2. XXL OVERLAP (walk FAIL 3): at Dynamic Type XXL the story card (the 96 pt row when demoted) overlaps the house rail by ~13 pt and captures taps. Find why the demoted story row's height does not follow its content at XXL (a fixed frame / clipped VStack / a ZStack ordering) and make the layout flow; prove at XXL light + dark (w4-fix3-03/04) with AX frames showing no overlap.
3. MAJ-2: one shared removal path (e.g., SavedRemoval.remove(productId:) on the store) used by ProductDetailViewModel.toggleSave, CollectionsViewModel.removeSavedItem and RecommendationsViewModel.unsaveProduct, clearing the TableItemModel rows, the room's SavedItem and the mirror; tests for all three entry points.
4. MAJ-1: CompanionOverlay's two sheets on one chain (.helpPanel at :520 and the claim sheet at :527) → one sheet driver (the Presented-enum pattern F2 used on the piece screen); prove the claim sheet still presents on a guest→account sign-in with local work, and the Companion help panel still opens.
5. The Companion action sheet's list does not scroll at XXL (walk minor) — make the rows scroll so every row is reachable; prove at XXL (w4-fix3-05).
6. The first-session presentation stall (fix-tasks outcome note: no sheet presents in the session that ran onboarding + the quiz + the Companion coach-mark): reproduce on a fresh device; if the cause is a presentation left dangling by the tour host or the Companion intro overlay and the fix is contained, fix it with a test; if not, write the diagnosis into ${W}/fix3-log.md with the exact reproduction and stop there.
GATE (unsandboxed, foreground): the worktree's ios-gate.sh build; xcodebuild test -only-testing:PatinaTests on dr-w4-fix3; the worktree's ios-gate.sh lint-delta main; supabase db reset + ./scripts/run-sql-tests.sh; signed rebuild → app_path. One Conventional Commit per item with pathspecs; rmdir the lock; delete the device. Return ok, commits, gate, app_path, root_cause (item 1, one paragraph, with the evidence that settled it), notes, failures.`, { label: 'F3 diagnose + fix', phase: 'Diagnose + fix', model: 'opus', effort: 'xhigh', schema: REPORT }))
if (!fix || !fix.ok) return { fix }

phase('Review 3')
const rev = await safe('V3', agent(`${COMMON}

ROLE: V3 — reviewer of the third round, separate context, read-only (git -C ${WT} log --oneline -8; git show per commit; report ${JSON.stringify({ commits: fix.commits, gate: fix.gate, root_cause: fix.root_cause, notes: fix.notes })}). Is the rail root cause proven (a reproduction, not a theory) and fixed at the cause with a test that follows the walker's sequence; does the XXL layout flow rather than hide; is un-save one path for three surfaces; is the Companion overlay one sheet driver; is the sheet scroll fix contained; is the stall diagnosis honest; no unrelated change; pathspec commits. Write ${W}/fix3-review.md; every finding with severity + confidence.`, { label: 'V3 review', phase: 'Review 3', model: 'opus', effort: 'high', schema: REV }))
if (rev && rev.blocking.length) { log(`Review blocking: ${rev.blocking.join(' | ')}`); return { fix, rev } }

phase('Re-walk')
const walk = await safe('walk', agent(`${COMMON}

ROLE: walker — W4 third walk on ${REVIEW_UDID}. Read ${W}/walk.md (your last pass), ${W}/fix3-review.md, and the fixer's root_cause: ${JSON.stringify(fix.root_cause)}. Unsandboxed: xcrun simctl keychain reset ${REVIEW_UDID}; uninstall; xcrun simctl install ${REVIEW_UDID} ${fix.app_path} (verify the build's commit stamp matches the integration tip before walking — record it); launch -DeploymentTarget local; sign in as client@patina.dev. Script: Today's YOUR HOUSE rail shows the seeded Guest Bedroom beside the two project rooms in the sign-in session; type a room → it appears on the rail; Sign Out → sign in → both rooms still on the rail and in Spaces (psql confirms); the same on -PatinaFlags house-first; dark + XXL on Today — the story card and the rail do not overlap (AX frames), every rail card tappable; un-save a piece from the Saved row's Remove and from a Browse card → the room's count drops each time; the Companion sheet scrolls at XXL to its last row; the ? help panel and the room picker still present on the piece screen; james.okafor's matched card survives the 20-day manipulation (restore). Shots w4-NN (continue), ledger "## w4 walk 3", REWRITE ${W}/walk.md as the final record (PASS/FAIL per item; earlier passes as appendices). Delete any test rooms server-side. Leave the simulator signed in as client@patina.dev, flag off, on the Daily Room. You are a walker: NO git writes of any kind. Return ok = no FAIL.`, { label: 'walk', phase: 'Re-walk', model: 'sonnet', schema: REPORT }))
return { fix: { ok: fix.ok, commits: fix.commits, gate: fix.gate, app_path: fix.app_path, root_cause: fix.root_cause, notes: fix.notes }, rev, walk }
