export const meta = {
  name: 'daily-return-w6-widget',
  description: 'W6 of the Daily Return build: the first widget (Home + Lock Screen) over the Record snapshot behind house-widget, deep links from the widget and from notifications into the right tab, and an opt-in due-date reminder on the invoice — two lanes, reviewed, integrated, walked',
  phases: [
    { title: 'Steward setup', detail: 'worktrees, clones, owned-file map, the xcodeproj gem check' },
    { title: 'Lanes', detail: 'X1 widget target + timeline + deep links ∥ X2 snapshot/flag bridge + due reminder' },
    { title: 'Reviews + fix', detail: 'two separate-context reviews; fix rounds' },
    { title: 'Integrate', detail: 'X2 → X1; gates incl. the widget target build' },
    { title: 'Walk', detail: 'the widget added on the simulator home screen; deep links; the reminder' },
  ],
}

const ROOT = '/Users/kody/Code/patina-merged'
const OUT = `${ROOT}/artifacts/ios-daily-return-2026-08-26`
const S = `${OUT}/source`
const R = `${OUT}/research`
const W = `${OUT}/waves/w6`
const APP = `${ROOT}/apps/mobile/Patina`
const REVIEW_UDID = '973D1724-90BF-4A0A-B02D-481D561547B3'
const wt = (k) => `${ROOT}/.codex/worktrees/agent-dr-w6-${k}`
const br = (k) => `daily-return/w6-${k}`

const COMMON = `You are one agent in the Daily Return build program for the Patina iOS CLIENT app (apps/mobile/Patina). The orchestrator (Fable) reads only your structured return and your files on disk.
Ground rules:
- Program folder: ${OUT}. Read ${S}/build-plan.md "Global constraints" and "### W6" IN FULL; ${S}/rulings-2026-08-27.md (Q8: one small widget, Home + Lock Screen; carries what moved, never what is owed; refreshed on foreground + timeline policy; may sit one open behind); ${S}/direction-b.md §4 (return surfaces beyond the app) and §11 M6 (read ${OUT}/mock/fragments/b-M6a.html, b-M6b.html and their .sheet.html — the Lock Screen push and the widget); ${R}/2x-panel-u1.md §6 (which iOS surfaces fit the brand — no Wallet pass, no count of chores on the Lock Screen); ${OUT}/waves/w2/r1-notes.md §7 + r2-notes.md §3 (the App Group: honoured on one simulator build, empty entitlements on the ad-hoc gate build — treat the shared container as a device claim and keep the fallback); ${OUT}/waves/w3/steward.md §4 (the deep-link doors) and W3's RouteTabTable/TabNavigationModel; ${OUT}/waves/w5/integration.md + walk.md (what W5 left). Load Skill "patina-parallel-work" and "patina-ios-verification".
- Sandbox: xcodebuild, xcrun simctl, git worktree/merge, osascript, docker, sips need dangerouslyDisableSandbox: true; builds in the foreground; first xcodebuild in a fresh tree may fail on GitCommit.swift — run twice; ios-gate.sh build writes to the SHARED DerivedData — re-run a no-error failure.
- Never git add -A; pathspec commits only; never push; never git in the main checkout except read-only; never touch production or App Store Connect (the widget's bundle id registration is Kody's).
- Screen capture rule: simulator evidence ONLY via xcrun simctl io <udid> screenshot or blitz's screenshot tool; NEVER screencapture / desktop-region capture (the desktop is Kody's); if gestures stop delivering, stop and report.
- Honesty (C5): the widget shows what moved (the Record's MOVED rows and the house), never a count of what is owed, never a badge, never a fabricated "new"; a stale snapshot says when it was refreshed; the reminder is opt-in from the invoice itself, one per invoice, and says exactly what it will say. Brand voice (C6); canonical names (C4).
- Report with evidence; FINAL action = StructuredOutput even on failure.`

const safe = async (label, p) => { try { const r = await p; if (!r) log(`${label}: returned null`); return r } catch (e) { log(`${label}: threw ${e && e.message ? e.message : e}`); return null } }
const REPORT = { type: 'object', required: ['ok', 'notes'], properties: { ok: { type: 'boolean' }, commits: { type: 'array', items: { type: 'string' } }, gate: { type: 'string' }, tasks_file: { type: 'string' }, app_path: { type: 'string' }, notes: { type: 'array', items: { type: 'string' } }, failures: { type: 'array', items: { type: 'string' } } } }
const REV = { type: 'object', required: ['file', 'blocking', 'major', 'minor'], properties: { file: { type: 'string' }, blocking: { type: 'array', items: { type: 'string' } }, major: { type: 'array', items: { type: 'string' } }, minor: { type: 'array', items: { type: 'string' } } } }

phase('Steward setup')
const setup = await safe('S', agent(`${COMMON}

ROLE: S — steward setup for W6. Base = current main tip (W5 merged): record git -C ${ROOT} log --oneline -1 main. Unsandboxed: worktrees ${wt('x1')} (-b ${br('x1')}) and ${wt('x2')} (-b ${br('x2')}) from main; Secrets.swift copied in; two clones of ${REVIEW_UDID} named dr-w6-x1 / dr-w6-x2 (shut the review device down briefly to clone, re-boot everything); delete leftover dr-w5-* devices and remove merged agent-dr-w5-* worktrees. Facts for X1: does the `xcodeproj` Ruby gem resolve (`ruby -e 'require "xcodeproj"; puts Xcodeproj::VERSION'` — apps/mobile/Capture/scripts/generate_project.rb uses it); Patina.xcodeproj's objectVersion and whether the app target uses PBXFileSystemSynchronizedRootGroup (yes per apps/mobile/Patina/CLAUDE.md — a new extension target still needs pbxproj edits); the current entitlements (App Group group.cloud.patina.app from W2, aps-environment, applinks); the deployment target; how DeepLinkHandler / NotificationRouter / TabNavigationModel route today (W3); where RecordSnapshotStore writes (path + App Group suite) and LastSeenStore's suite; how FeatureFlags could be mirrored into the App Group for the widget (the widget process cannot read PostHog). Write ${W}/steward.md with all of it and the OWNED-FILE MAP: X1 = a new PatinaWidget/ directory beside Patina/ (the extension target: WidgetBundle, the small Home widget, the Lock Screen accessory, timeline provider, views, Info.plist, entitlements), Patina.xcodeproj/project.pbxproj (X1 is its SOLE writer this wave), App/** for the widget's deep-link entry (openURL handling into TabNavigationModel), Features/Navigation/** (route parsing for widget URLs), tests; X2 = Core/Persistence/RecordSnapshotStore.swift (the WidgetCenter reload hook + a widget-facing snapshot shape), Core/State/FeatureFlags.swift (mirror the resolved flag set into the App Group suite), Features/Invoices/** (the opt-in reminder), Services/Notifications/** or wherever local notifications belong, tests. Return ok, notes.`, { label: 'S setup', phase: 'Steward setup', model: 'opus', schema: REPORT }))
if (!setup || !setup.ok) return { setup }

phase('Lanes')
const GATE = (k) => `GATE (unsandboxed, foreground): ${APP}/scripts/ios-gate.sh build (twice if needed); xcodebuild test -project ${wt(k)}/apps/mobile/Patina/Patina.xcodeproj -scheme Patina -configuration Debug -destination 'platform=iOS Simulator,id=<your clone udid>' -derivedDataPath ${wt(k)}/.build/dd -only-testing:PatinaTests — whole tier green; ${k === 'x1' ? 'ALSO build the widget extension target for the simulator destination (xcodebuild build -scheme <the widget scheme or the app scheme that embeds it>) and prove the .appex is embedded in Patina.app (ls Patina.app/PlugIns); ' : ''}no ios-gate.sh all / lint-delta. Signed .app → app_path. SIM CHECK on your clone with -DeploymentTarget local -PatinaFlags house-widget; shots ${OUT}/shots/w6-${k}-NN-*.png; ledger rows under "## w6-${k}". FINISH: rmdir the lock; git status --porcelain -uno empty.`
const [x1, x2, x3] = await parallel([
  () => safe('X3', agent(`${COMMON}

ROLE: X3 — session isolation (W5's carry-over, build-plan.md §W5-DONE). Unsandboxed: git -C ${ROOT} worktree add ${wt('x3')} -b ${br('x3')} main; copy Secrets.swift in; a fresh iPhone 17 Pro / iOS 26.5 device "dr-w6-x3"; verify toplevel; mkdir .writer.lock.d. Owned files: Services/Auth/AuthService.swift (the account-change seam), Services/Badges/BadgeCountService.swift, Services/DesignServices/DesignRequestStatusService.swift, Features/Orders/**/OrdersService.swift, Features/Rooms/RoomSyncCoordinator.swift, Features/Messaging/**/DesignerThreadOpener.swift (or wherever it lives), Core/State/DesignerRelationship.swift (the project rule only), tests. TASK LIST FIRST: ${W}/x3-tasks.md. DELIVER: (1) one SessionScope reset on the auth-state change seam AuthService already owns (the same place LocalStoreReset/LocalStoreClaim run): every process-lifetime singleton that caches account data (BadgeCountService rows + counts, DesignRequestStatusService requests/liveLead, OrdersService, RoomSyncCoordinator's debounce, any DesignerThreadOpener inputs, RecordSnapshotStore's in-memory record) is cleared BEFORE the new account's first fetch and refetched after — enumerate them by grep (static let shared … @Observable) so none is missed, and pin the list with a SourcePin; (2) the project rule: DesignerRelationshipResolver.activeProject(in:) and DesignerThreadOpener pick the project carrying the most urgent NEEDS YOU item (HouseRecord.needsYou's first row's project), else the most recently updated active project — the same rule W4 gave the seat; James's Ask-designer and Ruth's Ask-Leah both land in the right thread. Tests: sign out A → sign in B → every singleton reads B's data (a test double per service); the project rule. ${GATE('x3')} Sim check on your clone: sign in client@patina.dev → Settings → Sign Out → sign in james.okafor@example.com → Ask Leah to source this → the thread is James's (psql: comms_threads created_by/participants), no error sheet. Return ok, commits, gate, app_path, notes, failures.`, { label: 'X3 session isolation', phase: 'Lanes', model: 'opus', effort: 'high', schema: REPORT })),
  () => safe('X1', agent(`${COMMON}

ROLE: X1 — the widget target, its timeline, and the deep links. Read ${W}/steward.md. WORKSPACE: cd ${wt('x1')}; verify toplevel; mkdir .writer.lock.d. TASK LIST FIRST: ${W}/x1-tasks.md.
DELIVER: (1) a WidgetKit extension target PatinaWidget (bundle id cloud.patina.app.widget, deployment target = the app's, App Group group.cloud.patina.app in its entitlements, the same Info.plist conventions as the app) added to Patina.xcodeproj via a throwaway Ruby script using the xcodeproj gem (commit the resulting pbxproj, not the script — or commit the script under scripts/ if it is reusable; say which) with the app target embedding it; (2) a WidgetBundle with a small Home Screen widget ("what moved": up to two MOVED rows from the Record snapshot with their dates, the house line, the app's tokens — Playfair/Inter/DM Mono are bundled by PatinaDesignKit; the widget target must link PatinaDesignKit or vendor the tokens; say which) and a Lock Screen accessory (rectangular: one MOVED line; circular: the Strata mark) — NEVER a count of what is owed, never a badge; (3) the timeline provider reads the widget-facing snapshot X2 publishes in the App Group (contract: read ${W}/x2-tasks.md when it exists — poll for it up to 30 min; the shape is WidgetSnapshot { movedRows: [WidgetRow(title, date)], houseLine: String?, refreshedAt: Date, flagOn: Bool }; when flagOn is false the widget draws a quiet placeholder — the Strata mark and "Open Patina" — never data); the placeholder and preview states; timeline policy .after(now + 30 min) plus reloads from the app; "Refreshed <relative>" when older than 6 h; (4) deep links: every widget tap opens a URL the app routes (patina://today, patina://record/<rowId> → the row's route on the right tab via TabNavigationModel/RouteTabTable; on the flag-off root the same routes push on the single stack); notification deep links (00534's /invoices/<id> etc.) already route — extend to the widget scheme in DeepLinkHandler; tests for the URL parsing and the tab landing (RouteTabTable exhaustive) and a snapshot decode test in the widget target if it has a test bundle (else in PatinaTests over the shared model). ${GATE('x1')} Sim check: add the widget on the simulator Home Screen (blitz: long-press the home screen → "+" → search "Patina" → add the small widget; if the gallery cannot be driven, capture the widget's preview via the app's own debug preview if X2 provides one — say which) and capture it with data (client@patina.dev) and with the flag off (placeholder); tap it → the app opens on the right tab. Return ok, commits, gate, app_path, notes, failures.`, { label: 'X1 widget + deep links', phase: 'Lanes', model: 'opus', effort: 'xhigh', schema: REPORT })),
  () => safe('X2', agent(`${COMMON}

ROLE: X2 — the snapshot/flag bridge and the opt-in reminder. Read ${W}/steward.md. WORKSPACE: cd ${wt('x2')}; verify toplevel; mkdir .writer.lock.d. TASK LIST FIRST: ${W}/x2-tasks.md — PUBLISH the WidgetSnapshot contract at the top (X1 reads it): struct WidgetSnapshot: Codable { movedRows: [WidgetRow]; houseLine: String?; refreshedAt: Date; flagOn: Bool }, struct WidgetRow: Codable { id: String; title: String; date: Date; route: RouteToken? }, written by RecordSnapshotStore to the App Group container as widget-snapshot.json (falling back to the app container when the group URL is nil, as the record does).
DELIVER: (1) RecordSnapshotStore.save(_:) also writes the WidgetSnapshot (MOVED rows only — never NEEDS YOU; the house line from the house rail's first room; refreshedAt = now; flagOn from FeatureFlags) and calls WidgetCenter.shared.reloadTimelines(ofKind:) (import WidgetKit in the app target is allowed); (2) FeatureFlags mirrors its resolved set into the App Group suite (key patina.flags.resolved) at resolveAtLaunch so the widget can read flagOn without PostHog; (3) the opt-in due-date reminder on the invoice detail: a "Remind me the day before it's due" act (only for a payable invoice with a due_date in the future; one reminder per invoice, idempotent by identifier; the row shows "Reminder set for <date>" and a way to remove it) scheduling a UNUserNotificationCenter local notification with the exact copy "Your invoice is due tomorrow — $<amount>. Nothing else." (adapt to the voice; no urgency words), routed on tap to /invoices/<id> through the existing NotificationRouter; requires notification authorization — if not granted, the act presents SP-08's primer sentence and the system prompt once (reuse PushPrimerView), never nags; tests: snapshot shape + fallback, flag mirror, reminder scheduling idempotency + copy + removal. ${GATE('x2')} Sim check: set a reminder on INV-2026-0142 → the row shows the date; remove it; the widget-snapshot.json exists after a record save (find it under the simulator's container). Return ok, commits, gate, app_path, notes, failures.`, { label: 'X2 bridge + reminder', phase: 'Lanes', model: 'opus', effort: 'high', schema: REPORT })),
])

phase('Reviews + fix')
const revs = await parallel([['x1', x1], ['x2', x2]].map(([k, res]) => () => res && res.ok ? safe(`rev ${k}`, agent(`${COMMON}

ROLE: reviewer of ${k.toUpperCase()}, separate context, read-only (git -C ${wt(k)} diff main...HEAD; ${W}/${k}-tasks.md; report ${JSON.stringify({ commits: res.commits, gate: res.gate, notes: res.notes })}). Check against ruling Q8, direction-b §4 and M6, the honesty rules (never what is owed on the widget; no badge; stale state named; the reminder opt-in, single, exact copy), the App Group fallback, the flag mirror, the pbxproj change's hygiene (X1: no stray targets, the app embeds the appex, signing settings consistent, deployment target matches), deep links landing on the right tab on both roots, tests real, no edits outside the owned set, pathspec commits. Write ${W}/${k}-review.md; every finding with severity + confidence.`, { label: `review ${k}`, phase: 'Reviews + fix', model: 'opus', effort: 'high', schema: REV })) : Promise.resolve(null)))
const fixes = await parallel([['x1', x1, revs[0]], ['x2', x2, revs[1]]].map(([k, res, rv]) => () => (rv && (rv.blocking.length || rv.major.length)) ? safe(`fix ${k}`, agent(`${COMMON}

ROLE: ${k.toUpperCase()} fix round in ${wt(k)} (lock discipline; read ${W}/${k}-tasks.md and ${W}/${k}-review.md). Address every blocking and major (change or rebut in ${W}/${k}-fix-log.md with evidence); re-run the lane gate (${GATE(k)}); pathspec commits. Findings: ${JSON.stringify({ blocking: rv.blocking, major: rv.major })}`, { label: `fix ${k}`, phase: 'Reviews + fix', model: 'opus', effort: 'high', schema: REPORT })) : Promise.resolve(null)))

phase('Integrate')
const integ = await safe('integrate', agent(`${COMMON}

ROLE: steward — integrate W6. Unsandboxed: git -C ${ROOT} worktree add ${wt('integration')} -b daily-return/integration main; copy Secrets.swift; mkdir .writer.lock.d; create + boot "dr-w6-int". Merge ${br('x3')} → ${br('x2')} → ${br('x1')} (subjects "chore(daily-return): integrate w6 lane <x>"; a branch that does not exist means its lane failed — skip it and say so); resolve by intent; apply ${W}/*-notes.md. Gates: ios-gate.sh build; the whole PatinaTests tier on your device; the widget target builds and the .appex is embedded; ios-gate.sh lint-delta main; signed .app; flag on and off both launch. Write ${W}/integration.md. Return ok only if every gate is green.`, { label: 'integrate', phase: 'Integrate', model: 'opus', effort: 'high', schema: REPORT }))

phase('Walk')
const walk = integ && integ.ok ? await safe('walk', agent(`${COMMON}

ROLE: walker — W6 acceptance on ${REVIEW_UDID}. Read ${W}/integration.md and build-plan.md §W6. Unsandboxed: install ${integ.app_path}; launch with -DeploymentTarget local -PatinaFlags house-widget (and once with house-first too). Script: client@patina.dev — open the app so a record saves; add the small widget on the Home Screen (long-press → + → Patina) and the Lock Screen rectangular accessory if the simulator allows; the widget shows up to two MOVED rows with dates and the house line, no counts; tap a row → the app opens on the row's route on the right tab (both roots); relaunch without house-widget → the widget shows the placeholder; set the due-date reminder on INV-2026-0142 → the row shows the date → remove it; dark + XXL on the widget (if the gallery renders them). Shots w6-NN-*.png; ledger "## w6 walk"; ${W}/walk.md PASS/FAIL/BLOCKED per item (a simulator that cannot present the widget gallery makes those items BLOCKED, with the reason). Leave the simulator signed in as client@patina.dev, flags off, on the Daily Room. You are a walker: NO git writes of any kind (no add, no commit) — the orchestrator commits the wave record. Return ok = no FAIL.`, { label: 'walk', phase: 'Walk', model: 'sonnet', schema: REPORT })) : null

return { setup: setup.notes, x1: x1 && { ok: x1.ok, commits: x1.commits, gate: x1.gate, failures: x1.failures }, x2: x2 && { ok: x2.ok, commits: x2.commits, gate: x2.gate, failures: x2.failures }, reviews: revs, fixes, integration: integ && { ok: integ.ok, gate: integ.gate, app_path: integ.app_path, notes: integ.notes, failures: integ.failures }, walk: walk && { ok: walk.ok, notes: walk.notes, failures: walk.failures } }
