/**
 * use-scan-refine-artifacts.ts — the portal's only reader of Refine's
 * delivery record (Field Capture P2, Layer 3).
 *
 * Mirrors use-room-scan-photos.test.ts: intercept the chained query builder,
 * the storage API and `fetch` at their boundaries and React Query at its, so
 * `queryFn` can be invoked directly and inspected — no live database, no
 * bucket, no network.
 *
 * The assertions that matter:
 *  · THE ROUND TRIP (bottom of this file). The document Layer 2 actually
 *    writes — `__fixtures__/refine-present-patch.json`, generated by
 *    `build_present_patch` and pinned byte-for-byte by
 *    `services/scan-pipeline/tests/test_refine_delivery.py` — is fed through
 *    this parser and the resolved readout asserted. Everything else in this
 *    file is a hand-built fixture, and a suite of hand-built fixtures is
 *    exactly how a reader that looked for the record under the WRONG KEY
 *    passed 28 tests while resolving `null` for every real delivery.
 *  · flag-off (`enabled: false`) ⇒ the query never runs — zero DB, zero
 *    Storage. A "gated at render" version of this hook would still sign URLs.
 *  · ONE `createSignedUrls` call, carrying only the WANTED keys.
 *  · every missing/broken slot resolves to `null` rather than throwing.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect, vi, beforeEach } from 'vitest';

type BuilderResult = { data: unknown; error: unknown };

interface MockBuilder {
  /* eslint-disable @typescript-eslint/no-explicit-any */
  select: any;
  eq: any;
  order: any;
  /* eslint-enable @typescript-eslint/no-explicit-any */
  then: (resolve: (value: BuilderResult) => unknown) => Promise<unknown>;
  __result: BuilderResult;
}

function makeBuilder(initial: BuilderResult): MockBuilder {
  const builder = { __result: initial } as MockBuilder;
  const record = () => vi.fn(() => builder);
  builder.select = record();
  builder.eq = record();
  builder.order = record();
  builder.then = (resolve) => Promise.resolve(builder.__result).then(resolve);
  return builder;
}

let tableResult: BuilderResult = { data: [], error: null };

type SignedEntry = { path: string | null; signedUrl: string; error: string | null };
let signedUrlsResult: { data: SignedEntry[] | null; error: unknown } = {
  data: [],
  error: null,
};
const createSignedUrls = vi.fn(async (_paths: string[], _expiresIn: number) => signedUrlsResult);
const storageFrom = vi.fn(() => ({ createSignedUrls }));
const fromSpy = vi.fn(() => makeBuilder(tableResult));

const supabaseClient = {
  from: fromSpy,
  storage: { from: storageFrom },
};

vi.mock('@supabase/ssr', () => ({
  createBrowserClient: () => supabaseClient,
}));

vi.mock('@tanstack/react-query', () => ({
  // Returns the config so tests can call queryFn and read `enabled` directly.
  useQuery: (config: unknown) => config,
}));

// Import AFTER the mocks are wired up.
import {
  useScanRefineArtifacts,
  parseScanRefineRecord,
  DEFAULT_REFINE_ARTIFACT_NAMES,
  REFINE_DELIVERY_CONTRACT,
  REFINE_PRESENT_KEY,
  type ScanRefineArtifactSet,
} from '../use-scan-refine-artifacts';

// ─────────────────────────────────────────────────────────────────────────────
// Fixtures
// ─────────────────────────────────────────────────────────────────────────────

const SCAN = 'ec1f9a54-0000-4000-8000-000000000001';
const ROOM_FILE = 'ec1f9a54-0000-4000-8000-0000000000f1';
const PREFIX = `room_file/74056c2a-866d-42b0-9e2a-d473c2484316/${SCAN}/v1/refine`;

const ADVISORY =
  'advisory_not_gating_r123: loop_rotation_rmse_deg 1.250000->1.310000 (+4.80%); ' +
  'loop_translation_direction_rmse_deg 2.000000->1.900000 (-5.00%); verified_loop_edges 31';

/** The four fields `build_delivery_record` nests under `verdict`. */
const VERDICT_FIELDS = [
  'refinementEvidenced',
  'absoluteAccuracyCertified',
  'verdictReason',
  'loopConsistencyAdvisory',
] as const;

const ARTIFACT_NAMES = [
  'pose-deltas-v1.json',
  'refined-poses-v1.json',
  'refinement-evidence-v1.json',
  'refine-manifest-v1.json',
] as const;

/**
 * Layer 2's record, in `build_delivery_record`'s shape: keys come from the
 * `artifacts[]` ledger, the verdict is NESTED, and there is no identity block.
 *
 * `overrides` is flat for readability — a key naming a verdict field patches
 * the nested object, anything else patches the record. `undefined` DELETES.
 */
function refineRecord(overrides: Record<string, unknown> = {}) {
  const verdict: Record<string, unknown> = {
    refinementEvidenced: true,
    absoluteAccuracyCertified: false,
    verdictReason: 'reprojection improved and loop evidence held',
    loopConsistencyAdvisory: ADVISORY,
  };
  const record: Record<string, unknown> = {
    schemaVersion: 1,
    contract: REFINE_DELIVERY_CONTRACT,
    bucket: 'room-scans',
    prefix: PREFIX,
    manifestKey: `${PREFIX}/refine-manifest-v1.json`,
    artifacts: ARTIFACT_NAMES.map((name) => ({
      key: `${PREFIX}/${name}`,
      name,
      sha256: 'f'.repeat(64),
      sizeBytes: 128,
      semanticMediaType: 'application/json',
    })),
    verdict,
  };
  for (const [key, value] of Object.entries(overrides)) {
    const target = (VERDICT_FIELDS as readonly string[]).includes(key)
      ? verdict
      : record;
    if (value === undefined) delete target[key];
    else target[key] = value;
  }
  return record;
}

/** `{ name, key }` rows for a subset of names — the ledger shape, trimmed. */
function ledger(...names: string[]) {
  return names.map((name) => ({ name, key: `${PREFIX}/${name}` }));
}

function roomFileRow(presentJson: unknown, version = 1) {
  return { id: ROOM_FILE, scan_id: SCAN, version, present: presentJson };
}

/** `room_files.present` as Layer 2 writes it: the record plus the TEXT keys. */
function present(record: unknown = refineRecord()) {
  return {
    [REFINE_PRESENT_KEY]: record,
    // A STRING, exactly as `build_present_patch` writes it and as 00377's
    // `scan_present_stats` view reads it. The parser must not confuse the two.
    refine_engine: 'colmap-4-known-pose-triangulate-ba',
    vram_peak_mb: 512,
  };
}

/** Invoke the hook's queryFn the way React Query would. */
async function runQuery(
  scanId: string | null,
  options?: Parameters<typeof useScanRefineArtifacts>[1],
) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const config = useScanRefineArtifacts(scanId, options) as any;
  return (await config.queryFn()) as ScanRefineArtifactSet | null;
}

const fetchMock = vi.fn();

beforeEach(() => {
  tableResult = { data: [], error: null };
  signedUrlsResult = { data: [], error: null };
  // This package's vitest config does not set `clearMocks`, so call history
  // and implementations leak between tests unless reset explicitly — and the
  // "nothing was signed" assertions are exactly the ones a leak would falsify.
  fetchMock.mockReset();
  createSignedUrls.mockReset();
  createSignedUrls.mockImplementation(async () => signedUrlsResult);
  storageFrom.mockClear();
  fromSpy.mockClear();
  vi.stubGlobal('fetch', fetchMock);
});

/** Sign every requested path and serve each one a JSON body. */
function serve(bodies: Record<string, unknown>, status = 200) {
  createSignedUrls.mockImplementation(async (paths: string[]) => ({
    data: paths.map((path) => ({
      path,
      signedUrl: `https://storage.test/${path}?token=abc`,
      error: null,
    })),
    error: null,
  }));
  fetchMock.mockImplementation(async (url: string) => {
    const name = url.split('?')[0].split('/').pop() as string;
    if (!(name in bodies)) return { ok: false, status: 404, json: async () => ({}) };
    return { ok: status === 200, status, json: async () => bodies[name] };
  });
}

// ═══════════════════════════════════════════════════════════════════════════
// parseScanRefineRecord
// ═══════════════════════════════════════════════════════════════════════════

describe('parseScanRefineRecord', () => {
  const ctx = { scanId: SCAN, roomFileId: ROOM_FILE, roomFileVersion: 1 };

  it('reads a well-formed record and keeps the advisory verbatim', () => {
    const parsed = parseScanRefineRecord(present(), ctx);
    expect(parsed).not.toBeNull();
    expect(parsed!.bucket).toBe('room-scans');
    expect(parsed!.refinementEvidenced).toBe(true);
    expect(parsed!.absoluteAccuracyCertified).toBe(false);
    // Character for character — refine_adapter.py:1116.
    expect(parsed!.loopConsistencyAdvisory).toBe(ADVISORY);
    expect(parsed!.keysByName['pose-deltas-v1.json']).toBe(
      `${PREFIX}/pose-deltas-v1.json`,
    );
  });

  // ── The two halves of the shipped defect, each as a named regression ──────
  it('the ENGINE NAME under `refine_engine` is not mistaken for the record', () => {
    // 00377 (already on production) reads `present->>'refine_engine'` as TEXT,
    // so a string is the correct value there. A parser that looked for the
    // record under that key found a string and returned null for every real
    // delivery — silently, and indistinguishably from "not enabled yet".
    expect(parseScanRefineRecord(present(), ctx)!.bucket).toBe('room-scans');
    // The record parked under the TEXT key resolves to nothing.
    expect(
      parseScanRefineRecord({ refine_engine: refineRecord() }, ctx),
    ).toBeNull();
  });

  it('the verdict is read from `verdict`, not from the record top level', () => {
    const flattened = refineRecord({ verdict: undefined });
    for (const field of VERDICT_FIELDS) {
      (flattened as Record<string, unknown>)[field] =
        field === 'loopConsistencyAdvisory'
          ? ADVISORY
          : field === 'verdictReason'
            ? 'flat'
            : field === 'refinementEvidenced';
    }
    // A top-level verdict is NOT the contract and is refused rather than
    // half-read: `build_delivery_record` nests all four under `verdict`.
    expect(parseScanRefineRecord({ refine: flattened }, ctx)).toBeNull();
  });

  it.each([
    ['present null', null],
    ['present a string', 'nope'],
    ['present an array', [{ refine: {} }]],
    ['no refine key', { drawings: {} }],
    ['refine not an object', { refine: 'delivered' }],
    ['no bucket', present(refineRecord({ bucket: undefined }))],
    ['empty bucket', present(refineRecord({ bucket: '' }))],
    ['no keys at all', present(refineRecord({ artifacts: [] }))],
    ['artifacts not an array', present(refineRecord({ artifacts: 'x' }))],
    ['verdict missing entirely', present(refineRecord({ verdict: undefined }))],
    ['verdict not an object', present(refineRecord({ verdict: 'passed' }))],
    [
      'refinementEvidenced not a boolean',
      present(refineRecord({ refinementEvidenced: 'true' })),
    ],
    [
      'absoluteAccuracyCertified missing',
      present(refineRecord({ absoluteAccuracyCertified: undefined })),
    ],
  ])('%s → null, no throw', (_label, value) => {
    let parsed: unknown;
    expect(() => {
      parsed = parseScanRefineRecord(value, ctx);
    }).not.toThrow();
    expect(parsed).toBeNull();
  });

  it('drops individual malformed ledger rows rather than the whole record', () => {
    const parsed = parseScanRefineRecord(
      present(
        refineRecord({
          artifacts: [
            { name: 'pose-deltas-v1.json', key: `${PREFIX}/pose-deltas-v1.json` },
            { name: 'refined-poses-v1.json', key: 42 },
            { name: 'refinement-evidence-v1.json', key: '' },
            { name: 'nameless' },
            'not-a-row',
          ],
        }),
      ),
      ctx,
    );
    expect(Object.keys(parsed!.keysByName)).toEqual(['pose-deltas-v1.json']);
  });

  it('accepts a flat keysByName map as an alternative to the ledger', () => {
    // Layer 2 does NOT write this; it is tolerated so a hand-assembled record
    // still resolves.
    const parsed = parseScanRefineRecord(
      present(
        refineRecord({
          artifacts: undefined,
          keysByName: {
            'pose-deltas-v1.json': `${PREFIX}/pose-deltas-v1.json`,
            'refined-poses-v1.json': 42,
            'refinement-evidence-v1.json': '',
          },
        }),
      ),
      ctx,
    );
    expect(Object.keys(parsed!.keysByName)).toEqual(['pose-deltas-v1.json']);
  });

  it('the ledger wins over keysByName where the two name the same artifact', () => {
    const parsed = parseScanRefineRecord(
      present(
        refineRecord({
          artifacts: ledger('pose-deltas-v1.json'),
          keysByName: {
            'pose-deltas-v1.json': 'somewhere/else.json',
            'refinement-evidence-v1.json': `${PREFIX}/refinement-evidence-v1.json`,
          },
        }),
      ),
      ctx,
    );
    expect(parsed!.keysByName['pose-deltas-v1.json']).toBe(
      `${PREFIX}/pose-deltas-v1.json`,
    );
    // …and a name only keysByName carries is still picked up.
    expect(parsed!.keysByName['refinement-evidence-v1.json']).toBe(
      `${PREFIX}/refinement-evidence-v1.json`,
    );
  });

  it('takes identity from the row — the record carries none', () => {
    // `build_delivery_record` writes no scanId/roomFileId/roomFileVersion:
    // the row IS the identity, and the delivery already refused unless the
    // manifest agreed with it.
    const record = refineRecord();
    expect(record).not.toHaveProperty('scanId');
    const parsed = parseScanRefineRecord(present(record), ctx);
    expect(parsed!.scanId).toBe(SCAN);
    expect(parsed!.roomFileId).toBe(ROOM_FILE);
    expect(parsed!.roomFileVersion).toBe(1);
  });

  it('honours an identity the record does carry, and ignores a junk one', () => {
    const parsed = parseScanRefineRecord(
      present(refineRecord({ scanId: 'other-scan', roomFileVersion: 'one' })),
      ctx,
    );
    expect(parsed!.scanId).toBe('other-scan');
    expect(parsed!.roomFileVersion).toBe(1); // 'one' is not a number
  });

  it('a record whose verdict is unreadable is refused, not half-rendered', () => {
    expect(
      parseScanRefineRecord(present(refineRecord({ refinementEvidenced: null })), ctx),
    ).toBeNull();
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// The flag gate — the property the whole design turns on
// ═══════════════════════════════════════════════════════════════════════════

describe('useScanRefineArtifacts — gating', () => {
  it('enabled: false ⇒ the query never runs (zero DB, zero Storage)', () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const config = useScanRefineArtifacts(SCAN, { enabled: false }) as any;
    expect(config.enabled).toBe(false);
    expect(fromSpy).not.toHaveBeenCalled();
    expect(storageFrom).not.toHaveBeenCalled();
    expect(createSignedUrls).not.toHaveBeenCalled();
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it.each([
    ['null', null],
    ['undefined', undefined],
    ['empty string', ''],
  ])('scanId %s ⇒ disabled', (_label, scanId) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const config = useScanRefineArtifacts(scanId as string | null) as any;
    expect(config.enabled).toBe(false);
  });

  it('is enabled only with BOTH a scanId and the flag on', () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    expect((useScanRefineArtifacts(SCAN, { enabled: true }) as any).enabled).toBe(true);
  });

  it('caches forever — the artifacts are create-only and checksummed', () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    expect((useScanRefineArtifacts(SCAN) as any).staleTime).toBe(Infinity);
  });

  it('the query key carries the scan and the SORTED wanted names', () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const config = useScanRefineArtifacts(SCAN, {
      names: ['refinement-evidence-v1.json', 'pose-deltas-v1.json', 'pose-deltas-v1.json'],
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    }) as any;
    expect(config.queryKey).toEqual([
      'scan-refine-artifacts',
      SCAN,
      ['pose-deltas-v1.json', 'refinement-evidence-v1.json'],
    ]);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// Resolution
// ═══════════════════════════════════════════════════════════════════════════

describe('useScanRefineArtifacts — resolution', () => {
  it('signs ONLY the wanted keys, in ONE createSignedUrls call', async () => {
    tableResult = { data: [roomFileRow(present())], error: null };
    serve({
      'pose-deltas-v1.json': { schemaVersion: 1, frames: [] },
      'refinement-evidence-v1.json': { schemaVersion: 1, refinementEvidenced: true },
    });

    const result = await runQuery(SCAN);

    expect(createSignedUrls).toHaveBeenCalledTimes(1);
    const [paths, expiresIn] = createSignedUrls.mock.calls[0];
    expect(expiresIn).toBe(3600);
    // The record carries four keys; only the two wanted ones are signed —
    // the manifest and refined-poses are never fetched by this consumer.
    expect(paths.sort()).toEqual([
      `${PREFIX}/pose-deltas-v1.json`,
      `${PREFIX}/refinement-evidence-v1.json`,
    ]);
    expect(Object.keys(result!.documents).sort()).toEqual([
      ...DEFAULT_REFINE_ARTIFACT_NAMES,
    ].sort());
    expect(result!.documents['pose-deltas-v1.json']).toEqual({
      schemaVersion: 1,
      frames: [],
    });
  });

  it('honours a caller-supplied name list', async () => {
    tableResult = { data: [roomFileRow(present())], error: null };
    serve({ 'refined-poses-v1.json': { schemaVersion: 1, frames: [] } });

    const result = await runQuery(SCAN, { names: ['refined-poses-v1.json'] });

    expect(createSignedUrls.mock.calls[0][0]).toEqual([
      `${PREFIX}/refined-poses-v1.json`,
    ]);
    expect(result!.documents['refined-poses-v1.json']).toEqual({
      schemaVersion: 1,
      frames: [],
    });
  });

  it('takes the newest room_file version that carries a record', async () => {
    tableResult = {
      data: [
        roomFileRow({ drawings: {} }, 3), // v3: no refine record
        roomFileRow(present(refineRecord({ roomFileVersion: 2 })), 2),
        roomFileRow(present(refineRecord({ roomFileVersion: 1 })), 1),
      ],
      error: null,
    };
    serve({ 'pose-deltas-v1.json': { schemaVersion: 1, frames: [] } });

    const result = await runQuery(SCAN);
    expect(result!.record.roomFileVersion).toBe(2);
  });

  it.each([
    ['no room_files rows', [] as unknown[]],
    ['a row with no present', [roomFileRow(null)]],
    ['a row with no refine record', [roomFileRow({ drawings: {} })]],
  ])('%s ⇒ null, and nothing is signed', async (_label, rows) => {
    tableResult = { data: rows, error: null };
    const result = await runQuery(SCAN);
    expect(result).toBeNull();
    expect(createSignedUrls).not.toHaveBeenCalled();
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it('a record carrying none of the wanted keys ⇒ null, nothing signed', async () => {
    tableResult = {
      data: [
        roomFileRow(
          present(refineRecord({ artifacts: ledger('refine-manifest-v1.json') })),
        ),
      ],
      error: null,
    };
    const result = await runQuery(SCAN);
    expect(result).toBeNull();
    expect(createSignedUrls).not.toHaveBeenCalled();
  });

  it('a 404 on one artifact yields null for THAT slot, not a failed query', async () => {
    tableResult = { data: [roomFileRow(present())], error: null };
    serve({ 'pose-deltas-v1.json': { schemaVersion: 1, frames: [] } }); // evidence 404s

    const result = await runQuery(SCAN);
    expect(result!.documents['pose-deltas-v1.json']).not.toBeNull();
    expect(result!.documents['refinement-evidence-v1.json']).toBeNull();
  });

  it('a rejected fetch yields null for that slot (allSettled, not all)', async () => {
    tableResult = { data: [roomFileRow(present())], error: null };
    createSignedUrls.mockImplementation(async (paths: string[]) => ({
      data: paths.map((path) => ({
        path,
        signedUrl: `https://storage.test/${path}`,
        error: null,
      })),
      error: null,
    }));
    fetchMock.mockImplementation(async (url: string) => {
      if (url.includes('pose-deltas')) throw new TypeError('network down');
      return { ok: true, status: 200, json: async () => ({ schemaVersion: 1 }) };
    });

    let result: ScanRefineArtifactSet | null = null;
    await expect(
      (async () => {
        result = await runQuery(SCAN);
      })(),
    ).resolves.toBeUndefined();
    expect(result!.documents['pose-deltas-v1.json']).toBeNull();
    expect(result!.documents['refinement-evidence-v1.json']).toEqual({ schemaVersion: 1 });
  });

  it('malformed JSON yields null for that slot', async () => {
    tableResult = { data: [roomFileRow(present())], error: null };
    createSignedUrls.mockImplementation(async (paths: string[]) => ({
      data: paths.map((path) => ({ path, signedUrl: `https://s/${path}`, error: null })),
      error: null,
    }));
    fetchMock.mockImplementation(async () => ({
      ok: true,
      status: 200,
      json: async () => {
        throw new SyntaxError('Unexpected token <');
      },
    }));

    const result = await runQuery(SCAN);
    expect(result!.documents['pose-deltas-v1.json']).toBeNull();
    expect(result!.documents['refinement-evidence-v1.json']).toBeNull();
  });

  it('a signing failure degrades every slot to null rather than throwing', async () => {
    tableResult = { data: [roomFileRow(present())], error: null };
    createSignedUrls.mockImplementation(async () => ({
      data: null,
      error: { message: 'not authorized' },
    }));

    const result = await runQuery(SCAN);
    expect(result!.record.bucket).toBe('room-scans');
    expect(result!.documents['pose-deltas-v1.json']).toBeNull();
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it('one signed entry carrying an error degrades only that slot', async () => {
    tableResult = { data: [roomFileRow(present())], error: null };
    createSignedUrls.mockImplementation(async (paths: string[]) => ({
      data: paths.map((path) => ({
        path,
        signedUrl: `https://s/${path}`,
        error: path.includes('evidence') ? 'Object not found' : null,
      })),
      error: null,
    }));
    fetchMock.mockImplementation(async () => ({
      ok: true,
      status: 200,
      json: async () => ({ schemaVersion: 1, frames: [] }),
    }));

    const result = await runQuery(SCAN);
    expect(result!.documents['pose-deltas-v1.json']).toEqual({ schemaVersion: 1, frames: [] });
    expect(result!.documents['refinement-evidence-v1.json']).toBeNull();
  });

  it('signs against the bucket the RECORD names, not a hard-coded one', async () => {
    tableResult = {
      data: [roomFileRow(present(refineRecord({ bucket: 'other-bucket' })))],
      error: null,
    };
    serve({ 'pose-deltas-v1.json': { schemaVersion: 1 } });
    await runQuery(SCAN);
    expect(storageFrom).toHaveBeenCalledWith('other-bucket');
  });

  it('a public-URL-form key is repaired to a bare path before signing (R122)', async () => {
    const publicForm = `https://x.supabase.co/storage/v1/object/public/room-scans/${PREFIX}/pose-deltas-v1.json`;
    tableResult = {
      data: [
        roomFileRow(
          present(
            refineRecord({
              artifacts: [{ name: 'pose-deltas-v1.json', key: publicForm }],
            }),
          ),
        ),
      ],
      error: null,
    };
    serve({ 'pose-deltas-v1.json': { schemaVersion: 1 } });

    await runQuery(SCAN, { names: ['pose-deltas-v1.json'] });
    expect(createSignedUrls.mock.calls[0][0]).toEqual([
      `${PREFIX}/pose-deltas-v1.json`,
    ]);
  });

  it('a database error still propagates — that is a real failure, not a gap', async () => {
    tableResult = { data: null, error: { message: 'permission denied' } };
    await expect(runQuery(SCAN)).rejects.toEqual({ message: 'permission denied' });
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// THE ROUND TRIP — Layer 2's actual output, through Layer 3's actual reader
//
// Everything above this line is a hand-built fixture. Hand-built fixtures on
// both sides of a boundary is how the writer (81263a1d) and the reader
// (77b859e2) shipped the same day, each with a thorough green suite, disagreeing
// about the record entirely: the reader looked under `present.refine_engine`
// (which holds a STRING — 00377 reads it as TEXT) for a verdict at the record's
// top level (it is nested under `verdict`).
//
// `__fixtures__/refine-present-patch.json` is the EXACT document
// `refine_delivery.build_present_patch` produces, generated by driving the
// shipped runner + publisher into a local scratch sink and pinned byte-for-byte
// by `test_the_checked_in_portal_fixture_is_byte_for_byte_what_this_module_writes`
// in `services/scan-pipeline/tests/test_refine_delivery.py`. Neither side can
// move without one of the two tests going red.
// ═══════════════════════════════════════════════════════════════════════════

/** Read from disk, not imported, so the bytes Python pins are the bytes read. */
const PRESENT_PATCH_FIXTURE = JSON.parse(
  readFileSync(
    join(__dirname, '..', '__fixtures__', 'refine-present-patch.json'),
    'utf-8',
  ),
) as Record<string, unknown>;

// The fixture's identity comes from the delivery's own CLI arguments.
const FIXTURE_CTX = {
  scanId: 'scan-1',
  roomFileId: 'room-file-1',
  roomFileVersion: 3,
};
const FIXTURE_PREFIX = 'room_file/user-1/scan-1/v3/refine';

describe('round trip — build_present_patch → parseScanRefineRecord', () => {
  it('the fixture is shaped the way Layer 2 writes, not the way we imagined', () => {
    // Guards the fixture itself: if someone hand-edits it into the old
    // imagined shape, this fails before the parse assertions can mislead.
    expect(typeof PRESENT_PATCH_FIXTURE.refine_engine).toBe('string');
    const record = PRESENT_PATCH_FIXTURE[REFINE_PRESENT_KEY] as Record<string, unknown>;
    expect(record).toBeTypeOf('object');
    expect(record.contract).toBe(REFINE_DELIVERY_CONTRACT);
    expect(record.schemaVersion).toBe(1);
    expect(Array.isArray(record.artifacts)).toBe(true);
    expect(record.verdict).toBeTypeOf('object');
    // `vram_peak_mb` is a JSON NUMBER (00377 casts it to numeric) and
    // `sfm_residual_pct` is absent on purpose (ruling R-D open).
    expect(typeof PRESENT_PATCH_FIXTURE.vram_peak_mb).toBe('number');
    expect(PRESENT_PATCH_FIXTURE).not.toHaveProperty('sfm_residual_pct');
  });

  it('parses — the assertion that would have caught the shipped defect', () => {
    const parsed = parseScanRefineRecord(PRESENT_PATCH_FIXTURE, FIXTURE_CTX);
    expect(parsed).not.toBeNull();
  });

  it('resolves every field the readout renders', () => {
    const parsed = parseScanRefineRecord(PRESENT_PATCH_FIXTURE, FIXTURE_CTX)!;

    expect(parsed.bucket).toBe('room-scans');
    expect(parsed.scanId).toBe(FIXTURE_CTX.scanId);
    expect(parsed.roomFileId).toBe(FIXTURE_CTX.roomFileId);
    expect(parsed.roomFileVersion).toBe(FIXTURE_CTX.roomFileVersion);

    // All eleven published objects are reachable, as BARE keys (R122).
    expect(Object.keys(parsed.keysByName)).toHaveLength(11);
    for (const key of Object.values(parsed.keysByName)) {
      expect(key.startsWith(`${FIXTURE_PREFIX}/`)).toBe(true);
      expect(key).not.toContain('://');
    }
    // The two Layer 3 actually fetches.
    for (const name of DEFAULT_REFINE_ARTIFACT_NAMES) {
      expect(parsed.keysByName[name]).toBe(`${FIXTURE_PREFIX}/${name}`);
    }

    expect(typeof parsed.refinementEvidenced).toBe('boolean');
    // Unreachable-by-construction: `evaluate_refinement_evidence` never sets
    // it. The readout renders NOT CERTIFIED unconditionally regardless.
    expect(parsed.absoluteAccuracyCertified).toBe(false);
    expect(parsed.verdictReason.length).toBeGreaterThan(0);
  });

  it('carries R123’s advisory VERBATIM — character for character', () => {
    const parsed = parseScanRefineRecord(PRESENT_PATCH_FIXTURE, FIXTURE_CTX)!;
    const written = (
      (PRESENT_PATCH_FIXTURE[REFINE_PRESENT_KEY] as Record<string, unknown>)
        .verdict as Record<string, unknown>
    ).loopConsistencyAdvisory as string;

    // Identity, not containment: no trim, no rounding, no truncation, no
    // paraphrase. `refine_adapter.py:1116` — "Nothing reads this string; it
    // exists to be read."
    expect(parsed.loopConsistencyAdvisory).toBe(written);
    expect(parsed.loopConsistencyAdvisory).toMatch(/^advisory_not_gating_r123: /);
    expect(parsed.loopConsistencyAdvisory).toContain('loop_rotation_rmse_deg');
    expect(parsed.loopConsistencyAdvisory).toContain(
      'loop_translation_direction_rmse_deg',
    );
    expect(parsed.loopConsistencyAdvisory).toContain('verified_loop_edges');
  });

  it('the whole hook resolves both documents off the real record', async () => {
    tableResult = {
      data: [
        {
          id: FIXTURE_CTX.roomFileId,
          scan_id: FIXTURE_CTX.scanId,
          version: FIXTURE_CTX.roomFileVersion,
          present: PRESENT_PATCH_FIXTURE,
        },
      ],
      error: null,
    };
    serve({
      'pose-deltas-v1.json': { schemaVersion: 1, frames: [] },
      'refinement-evidence-v1.json': { schemaVersion: 1, refinementEvidenced: true },
    });

    const result = await runQuery(FIXTURE_CTX.scanId);

    expect(result).not.toBeNull();
    expect(storageFrom).toHaveBeenCalledWith('room-scans');
    expect(createSignedUrls).toHaveBeenCalledTimes(1);
    expect([...createSignedUrls.mock.calls[0][0]].sort()).toEqual(
      [...DEFAULT_REFINE_ARTIFACT_NAMES]
        .map((name) => `${FIXTURE_PREFIX}/${name}`)
        .sort(),
    );
    expect(result!.documents['pose-deltas-v1.json']).toEqual({
      schemaVersion: 1,
      frames: [],
    });
    expect(result!.documents['refinement-evidence-v1.json']).toEqual({
      schemaVersion: 1,
      refinementEvidenced: true,
    });
  });
});
