/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';

export interface POLineItem {
  name: string;
  quantity: number;
  unitPriceCents: number;
  lineTotalCents: number;
}

export interface POTemplateProps {
  poNumber: string;
  projectName: string;
  vendorName: string;
  lineItems: POLineItem[];
  issuedAt: string;
}

const styles = StyleSheet.create({
  page: {
    padding: 56,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: '#2C2926',
  },
  header: {
    borderBottom: '1pt solid #2C2926',
    paddingBottom: 16,
    marginBottom: 24,
  },
  title: {
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 4,
  },
  meta: {
    fontSize: 9,
    color: '#5C4A3C',
  },
  twoCol: {
    flexDirection: 'row',
    gap: 32,
    marginBottom: 24,
  },
  block: { flex: 1 },
  label: {
    fontSize: 7,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: '#5C4A3C',
    marginBottom: 4,
  },
  value: { fontSize: 11 },
  table: {
    border: '1pt solid #E5E2DD',
    borderRadius: 2,
  },
  tableHead: {
    flexDirection: 'row',
    background: '#E5E2DD',
    padding: 8,
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderTop: '1pt solid #E5E2DD',
  },
  cellName: { flex: 3 },
  cellQty: { flex: 1, textAlign: 'right' },
  cellPrice: { flex: 1, textAlign: 'right' },
  cellTotal: { flex: 1, textAlign: 'right', fontWeight: 700 },
  totals: {
    marginTop: 24,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  totalsBlock: { width: 200 },
  totalsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  totalsTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderTop: '1pt solid #2C2926',
    fontWeight: 700,
  },
  footer: {
    position: 'absolute',
    bottom: 32,
    left: 56,
    right: 56,
    textAlign: 'center',
    fontSize: 8,
    color: '#5C4A3C',
  },
});

function fmt(cents: number): string {
  return `$${(cents / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function POTemplate(props: POTemplateProps) {
  const subtotal = props.lineItems.reduce((sum, l) => sum + l.lineTotalCents, 0);
  const issuedDate = new Date(props.issuedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Purchase Order</Text>
          <Text style={styles.meta}>{props.poNumber} · Issued {issuedDate}</Text>
        </View>

        <View style={styles.twoCol}>
          <View style={styles.block}>
            <Text style={styles.label}>Project</Text>
            <Text style={styles.value}>{props.projectName}</Text>
          </View>
          <View style={styles.block}>
            <Text style={styles.label}>Vendor</Text>
            <Text style={styles.value}>{props.vendorName}</Text>
          </View>
        </View>

        <View style={styles.table}>
          <View style={styles.tableHead}>
            <Text style={[styles.cellName, styles.label]}>Item</Text>
            <Text style={[styles.cellQty, styles.label]}>Qty</Text>
            <Text style={[styles.cellPrice, styles.label]}>Unit Price</Text>
            <Text style={[styles.cellTotal, styles.label]}>Total</Text>
          </View>
          {props.lineItems.map((line, idx) => (
            <View key={idx} style={styles.tableRow}>
              <Text style={styles.cellName}>{line.name}</Text>
              <Text style={styles.cellQty}>{line.quantity}</Text>
              <Text style={styles.cellPrice}>{fmt(line.unitPriceCents)}</Text>
              <Text style={styles.cellTotal}>{fmt(line.lineTotalCents)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.totals}>
          <View style={styles.totalsBlock}>
            <View style={styles.totalsRow}>
              <Text>Subtotal</Text>
              <Text>{fmt(subtotal)}</Text>
            </View>
            <View style={styles.totalsTotal}>
              <Text>Total Due</Text>
              <Text>{fmt(subtotal)}</Text>
            </View>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by Patina · patina.cloud
        </Text>
      </Page>
    </Document>
  );
}
