import { TimelineService } from './timeline.service';
import { CreateTimelineSegmentDto } from './dto/create-timeline-segment.dto';
import { UpdateTimelineSegmentDto } from './dto/update-timeline-segment.dto';
import { LogActivityDto } from './dto/log-activity.dto';
import { Request } from 'express';
export declare class TimelineController {
    private readonly timelineService;
    constructor(timelineService: TimelineService);
    createSegment(projectId: string, createDto: CreateTimelineSegmentDto, userId: string): Promise<{
        approvals: {
            status: string;
            title: string;
            id: string;
            metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
            priority: string;
            comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
            createdAt: Date;
            signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
            description: string | null;
            updatedAt: Date;
            documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
            projectId: string;
            dueDate: Date | null;
            rejectionReason: string | null;
            segmentId: string | null;
            approvalType: string;
            requestedBy: string;
            assignedTo: string;
            approvedAt: Date | null;
            approvedBy: string | null;
            rejectedAt: Date | null;
            rejectedBy: string | null;
        }[];
    } & {
        order: number;
        status: string;
        title: string;
        id: string;
        progress: number;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        description: string | null;
        updatedAt: Date;
        startDate: Date;
        endDate: Date;
        projectId: string;
        deliverables: import("../generated/prisma-client/runtime/library").JsonValue | null;
        phase: string;
        dependencies: import("../generated/prisma-client/runtime/library").JsonValue | null;
    }>;
    getTimeline(projectId: string): Promise<{
        projectId: string;
        projectStatus: string;
        startDate: Date | null;
        endDate: Date | null;
        overallProgress: number;
        segmentCount: number;
        segments: ({
            approvals: {
                status: string;
                title: string;
                id: string;
                metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
                priority: string;
                comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
                createdAt: Date;
                signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
                description: string | null;
                updatedAt: Date;
                documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
                projectId: string;
                dueDate: Date | null;
                rejectionReason: string | null;
                segmentId: string | null;
                approvalType: string;
                requestedBy: string;
                assignedTo: string;
                approvedAt: Date | null;
                approvedBy: string | null;
                rejectedAt: Date | null;
                rejectedBy: string | null;
            }[];
            _count: {
                approvals: number;
                activities: number;
            };
        } & {
            order: number;
            status: string;
            title: string;
            id: string;
            progress: number;
            metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
            createdAt: Date;
            description: string | null;
            updatedAt: Date;
            startDate: Date;
            endDate: Date;
            projectId: string;
            deliverables: import("../generated/prisma-client/runtime/library").JsonValue | null;
            phase: string;
            dependencies: import("../generated/prisma-client/runtime/library").JsonValue | null;
        })[];
    }>;
    getSegment(projectId: string, segmentId: string): Promise<{
        dependentSegments: {
            id: string;
            title: string;
            status: string;
            progress: number;
            endDate: Date;
        }[];
        approvals: {
            status: string;
            title: string;
            id: string;
            metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
            priority: string;
            comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
            createdAt: Date;
            signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
            description: string | null;
            updatedAt: Date;
            documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
            projectId: string;
            dueDate: Date | null;
            rejectionReason: string | null;
            segmentId: string | null;
            approvalType: string;
            requestedBy: string;
            assignedTo: string;
            approvedAt: Date | null;
            approvedBy: string | null;
            rejectedAt: Date | null;
            rejectedBy: string | null;
        }[];
        _count: {
            approvals: number;
            activities: number;
        };
        activities: {
            userAgent: string | null;
            id: string;
            metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
            duration: number | null;
            ipAddress: string | null;
            createdAt: Date;
            userId: string;
            projectId: string;
            segmentId: string | null;
            activityType: string;
            entityType: string | null;
            entityId: string | null;
        }[];
        order: number;
        status: string;
        title: string;
        id: string;
        progress: number;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        description: string | null;
        updatedAt: Date;
        startDate: Date;
        endDate: Date;
        projectId: string;
        deliverables: import("../generated/prisma-client/runtime/library").JsonValue | null;
        phase: string;
        dependencies: import("../generated/prisma-client/runtime/library").JsonValue | null;
    }>;
    updateSegment(projectId: string, segmentId: string, updateDto: UpdateTimelineSegmentDto, userId: string): Promise<{
        order: number;
        status: string;
        title: string;
        id: string;
        progress: number;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        createdAt: Date;
        description: string | null;
        updatedAt: Date;
        startDate: Date;
        endDate: Date;
        projectId: string;
        deliverables: import("../generated/prisma-client/runtime/library").JsonValue | null;
        phase: string;
        dependencies: import("../generated/prisma-client/runtime/library").JsonValue | null;
    }>;
    logActivity(projectId: string, logDto: LogActivityDto, userId: string, req: Request): Promise<{
        userAgent: string | null;
        id: string;
        metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
        duration: number | null;
        ipAddress: string | null;
        createdAt: Date;
        userId: string;
        projectId: string;
        segmentId: string | null;
        activityType: string;
        entityType: string | null;
        entityId: string | null;
    }>;
    getUpcoming(projectId: string, days?: string): Promise<{
        segments: {
            status: string;
            title: string;
            id: string;
            startDate: Date;
            endDate: Date;
            phase: string;
        }[];
        milestones: {
            order: number;
            status: string;
            title: string;
            id: string;
            metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
            createdAt: Date;
            description: string | null;
            updatedAt: Date;
            projectId: string;
            targetDate: Date;
            completedAt: Date | null;
        }[];
        approvals: {
            status: string;
            title: string;
            id: string;
            metadata: import("../generated/prisma-client/runtime/library").JsonValue | null;
            priority: string;
            comments: import("../generated/prisma-client/runtime/library").JsonValue | null;
            createdAt: Date;
            signature: import("../generated/prisma-client/runtime/library").JsonValue | null;
            description: string | null;
            updatedAt: Date;
            documents: import("../generated/prisma-client/runtime/library").JsonValue | null;
            projectId: string;
            dueDate: Date | null;
            rejectionReason: string | null;
            segmentId: string | null;
            approvalType: string;
            requestedBy: string;
            assignedTo: string;
            approvedAt: Date | null;
            approvedBy: string | null;
            rejectedAt: Date | null;
            rejectedBy: string | null;
        }[];
    }>;
    getProgress(projectId: string): Promise<{
        overallProgress: number;
        phaseProgress: Record<string, number>;
        statusDistribution: Record<string, number>;
        timeProgress: number;
        milestoneCompletionRate: number;
        totalSegments: number;
        totalMilestones: number;
        completedMilestones: number;
    }>;
}
//# sourceMappingURL=timeline.controller.d.ts.map