-- ═══════════════════════════════════════════════════════════════════════════
-- 00-legacy-grants — GENERATED by scripts/generate-legacy-grants.py. Do not
-- hand-edit; regenerate after adding migrations with GRANT/REVOKE statements.
--
-- Supabase's 2026-05-30 platform-default flip leaves fresh local stacks
-- without the creation-time grants every migration up to the flip relied on
-- (and makes the migrations' deliberate REVOKEs creation-order no-ops). This
-- seed restores the legacy blanket baseline, then replays the migrations'
-- entire top-level GRANT/REVOKE history in order — the final ACL state
-- matches what the old stack (and prod) converged to. Local-only: seeds never
-- run on prod. RLS remains the enforcement layer throughout.
-- ═══════════════════════════════════════════════════════════════════════════

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- Legacy creation-time baseline on everything that exists locally.
DO $baseline$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT c.oid::regclass AS obj
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p', 'v', 'm', 'f')
  LOOP
    EXECUTE format('GRANT ALL ON TABLE %s TO anon, authenticated, service_role', r.obj);
  END LOOP;
  FOR r IN
    SELECT c.oid::regclass AS obj
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'S'
  LOOP
    EXECUTE format('GRANT USAGE, SELECT, UPDATE ON SEQUENCE %s TO anon, authenticated, service_role', r.obj);
  END LOOP;
  FOR r IN
    SELECT p.oid::regprocedure AS obj, p.prokind
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.prokind IN ('f', 'p')
  LOOP
    EXECUTE format(
      'GRANT EXECUTE ON %s %s TO anon, authenticated, service_role',
      CASE WHEN r.prokind = 'p' THEN 'PROCEDURE' ELSE 'FUNCTION' END, r.obj);
  END LOOP;
END $baseline$;

-- Legacy defaults for anything created interactively after this seed.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;

-- ── Replay of every top-level GRANT/REVOKE across supabase/migrations/ ──────
-- Each statement is guarded: objects dropped by later migrations are skipped.

-- 00008_similarity_functions.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION find_similar_products TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00008_similarity_functions.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION find_products_similar_to TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00008_similarity_functions.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION search_products_semantic TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00008_similarity_functions.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION find_products_for_style TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00008_similarity_functions.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_embedding_stats TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00027_hero_frames.sql
DO $g$ BEGIN
  GRANT SELECT ON rooms_with_hero_frames TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00067_ios_api_endpoints.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION process_style_quiz TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00067_ios_api_endpoints.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_recommendations TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00067_ios_api_endpoints.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_recommendations TO anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00077_advanced_room_scan.sql
DO $g$ BEGIN
  GRANT SELECT ON room_scans_v2 TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00080_ab_variant_stats.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_ab_variant_stats(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00080_ab_variant_stats.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_ab_variant_stats(UUID) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00082_scan_upload_pipeline.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.mark_scan_upload_complete(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00082_scan_upload_pipeline.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.merge_scan_artifact_sha256(UUID, TEXT, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00085_decision_feedthrough_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION apply_decision(UUID, UUID, UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00086_activate_project_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.activate_project_v2(jsonb) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00103_comms_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.rpc_start_direct_thread(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00103_comms_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.rpc_start_project_thread(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00103_comms_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.rpc_start_vendor_brief(UUID, UUID, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00103_comms_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.rpc_mark_thread_read(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00103_comms_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.rpc_unread_summary() TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00103_comms_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.rpc_soft_delete_message(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00109_admin_outbox_rpc.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.get_outbox_events(integer, boolean) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00109_admin_outbox_rpc.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.get_outbox_counts() FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00109_admin_outbox_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.get_outbox_events(integer, boolean) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00109_admin_outbox_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.get_outbox_counts() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00110_admin_decision_analytics_rpc.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.get_decision_bottleneck_phases_admin() FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00110_admin_decision_analytics_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.get_decision_bottleneck_phases_admin() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00128_ffe_categories_taxonomy.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION migrate_legacy_ffe_notes() FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00128_ffe_categories_taxonomy.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION migrate_legacy_ffe_notes() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00130_proposal_captures.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION consume_capture(UUID, UUID, UUID, TEXT, INTEGER) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00130_proposal_captures.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION consume_capture(UUID, UUID, UUID, TEXT, INTEGER) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00130_proposal_captures.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION list_designer_open_proposals(UUID) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00130_proposal_captures.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION list_designer_open_proposals(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00135_proposal_phase_templates.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION apply_phase_template(UUID, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00142_proposal_items_line_total_rename.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION consume_capture(UUID, UUID, UUID, TEXT, INTEGER) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00142_proposal_items_line_total_rename.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION consume_capture(UUID, UUID, UUID, TEXT, INTEGER) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00154_promotion_rpcs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION promote_to_studio FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00154_promotion_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION promote_to_studio TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00154_promotion_rpcs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION is_product_in_active_use FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00154_promotion_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION is_product_in_active_use TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00154_promotion_rpcs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION demote_to_personal FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00154_promotion_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION demote_to_personal TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00155_promote_batch_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION promote_batch_to_studio FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00155_promote_batch_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION promote_batch_to_studio TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00160_admin_nomination_transition_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION set_nomination_status FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00160_admin_nomination_transition_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION set_nomination_status TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00161_link_studio_to_catalog.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION link_studio_to_catalog_for_vendor FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00161_link_studio_to_catalog.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION link_studio_to_catalog_for_vendor TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00173_decision_notifications.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.notify_decision_required(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00173_decision_notifications.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.notify_decision_overdue(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00173_decision_notifications.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.notify_decision_resolved(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00174_decision_resolved_email_and_overdue_cron.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.notify_decision_updated(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00175_decision_ffe_feedthrough.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION apply_decision(UUID, UUID, UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00176_proposal_clone_and_send.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION clone_proposal(UUID, TEXT, TEXT) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00176_proposal_clone_and_send.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION clone_proposal(UUID, TEXT, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00176_proposal_clone_and_send.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION send_proposal(UUID, TEXT, TEXT, TIMESTAMPTZ) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00176_proposal_clone_and_send.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION send_proposal(UUID, TEXT, TEXT, TIMESTAMPTZ) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00178_invoices_v1.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.issue_invoice(UUID, DATE) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00178_invoices_v1.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.issue_invoice(UUID, DATE) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00178_invoices_v1.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.record_invoice_payment(UUID, INTEGER, TEXT, TEXT, TIMESTAMPTZ, TEXT) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00178_invoices_v1.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.record_invoice_payment(UUID, INTEGER, TEXT, TEXT, TIMESTAMPTZ, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00178_invoices_v1.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.void_invoice(UUID, TEXT) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00178_invoices_v1.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.void_invoice(UUID, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00178_invoices_v1.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.apply_invoice_payment_effects(UUID) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00178_invoices_v1.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.apply_invoice_payment_effects(UUID) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00185_ffe_dual_pricing.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION apply_decision(UUID, UUID, UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00186_create_purchase_order_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.create_purchase_order(UUID, UUID, purchase_order_payment_pattern, UUID[], TEXT, DATE, BOOLEAN, DATE, INTEGER, JSONB, TEXT, TEXT) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00186_create_purchase_order_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.create_purchase_order(UUID, UUID, purchase_order_payment_pattern, UUID[], TEXT, DATE, BOOLEAN, DATE, INTEGER, JSONB, TEXT, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00186_create_purchase_order_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.log_po_acknowledgment(UUID, TEXT, DATE) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00186_create_purchase_order_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.log_po_acknowledgment(UUID, TEXT, DATE) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00187_invoice_ffe_lines.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.void_invoice(UUID, TEXT) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00187_invoice_ffe_lines.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.void_invoice(UUID, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00187_invoice_ffe_lines.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.get_ffe_invoice_coverage(UUID) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00187_invoice_ffe_lines.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.get_ffe_invoice_coverage(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00188_po_send_columns.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.assign_po_number(UUID) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00188_po_send_columns.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.assign_po_number(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00190_ack_any_active_status.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.log_po_acknowledgment(UUID, TEXT, DATE) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00190_ack_any_active_status.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.log_po_acknowledgment(UUID, TEXT, DATE) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00209_invoice_chase.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.chase_invoice(UUID) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00209_invoice_chase.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.chase_invoice(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00212_project_parties.sql
DO $g$ BEGIN
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.project_parties TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00212_project_parties.sql
DO $g$ BEGIN
  GRANT ALL ON public.project_parties TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00214_coordination_item_revisions.sql
DO $g$ BEGIN
  GRANT SELECT ON public.coordination_item_revisions TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00214_coordination_item_revisions.sql
DO $g$ BEGIN
  GRANT ALL ON public.coordination_item_revisions TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00217_coordination_rls.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.is_coordination_party(UUID, UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00218_resolve_coordination_item.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.submit_coordination_revision(UUID, JSONB, TEXT, TEXT, UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00218_resolve_coordination_item.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.resolve_coordination_item(UUID, UUID, TEXT, UUID, TEXT, UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00219_coordination_read_models.sql
DO $g$ BEGIN
  GRANT SELECT ON public.coordination_court_summary TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00219_coordination_read_models.sql
DO $g$ BEGIN
  GRANT SELECT ON public.coordination_court_summary TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00219_coordination_read_models.sql
DO $g$ BEGIN
  GRANT SELECT ON public.task_blocked_state TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00219_coordination_read_models.sql
DO $g$ BEGIN
  GRANT SELECT ON public.task_blocked_state TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00221_people_directory.sql
DO $g$ BEGIN
  GRANT SELECT ON public.people_directory TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00231_proposal_nudge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.nudge_proposal(UUID) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00231_proposal_nudge.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.nudge_proposal(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION commit_field_capture(UUID, TEXT, JSONB, UUID, UUID, TEXT, UUID) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION commit_field_capture(UUID, TEXT, JSONB, UUID, UUID, TEXT, UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION route_field_capture(UUID, UUID, UUID, TEXT) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION route_field_capture(UUID, UUID, UUID, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION dismiss_field_capture(UUID) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION dismiss_field_capture(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION merge_capture_artifact_sha256(UUID, TEXT, TEXT) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION mark_capture_upload_complete(UUID) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION merge_capture_artifact_sha256(UUID, TEXT, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00235_commit_field_capture_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION mark_capture_upload_complete(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00241_aesthete_jobs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION claim_aesthete_jobs(text, int) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00241_aesthete_jobs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION complete_aesthete_job(bigint, text, text) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00241_aesthete_jobs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION claim_aesthete_jobs(text, int) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00241_aesthete_jobs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION complete_aesthete_job(bigint, text, text) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON v_house_taste_public FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT SELECT ON v_house_taste_public TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION submit_taste_judgment(jsonb, text, text, uuid, int) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION submit_taste_correction(text, uuid, uuid, uuid, jsonb, text, text) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION update_my_biases(jsonb) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION export_designer_taste(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION retire_designer_taste(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION compute_house_taste_draft() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION activate_house_taste(int) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION refresh_style_centroids() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION is_aesthete_lead(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION submit_taste_judgment(jsonb, text, text, uuid, int) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION submit_taste_correction(text, uuid, uuid, uuid, jsonb, text, text) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION update_my_biases(jsonb) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION export_designer_taste(uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION retire_designer_taste(uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION compute_house_taste_draft() TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION activate_house_taste(int) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION refresh_style_centroids() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00242_aesthete_taste_foundation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION is_aesthete_lead(uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00243_aesthete_client_quiz.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _compute_quiz_profile(jsonb) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00243_aesthete_client_quiz.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION submit_style_quiz(uuid, jsonb, jsonb, text, jsonb) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00243_aesthete_client_quiz.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION claim_quiz_session(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00243_aesthete_client_quiz.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION aesthete_quiz_janitor() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00243_aesthete_client_quiz.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION submit_style_quiz(uuid, jsonb, jsonb, text, jsonb) TO anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00243_aesthete_client_quiz.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION claim_quiz_session(uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00243_aesthete_client_quiz.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION aesthete_quiz_janitor() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_product_spectrum(uuid) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_spectrum_term(jsonb, jsonb, jsonb, jsonb) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_spectrum_distance(jsonb, jsonb) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_material_bucket(text) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_material_color_term(jsonb, text[], real, real) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_budget_term(int, bigint, bigint, real, real, boolean) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_function_term(jsonb, text[], real, real, text, real) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_utilization(double precision) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_context_term(jsonb, real, real) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_rule_cond(jsonb, jsonb) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_rule_matches(jsonb, jsonb) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_theta_blend(real[], real[], real) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_phi(uuid) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_taste_term(real[], uuid) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION get_aesthete_matches(uuid, uuid, real, text, uuid, text, int, int, real, text) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_aesthete_matches(uuid, uuid, real, text, uuid, text, int, int, real, text) TO anon, authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION aesthete_search(text, jsonb) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION aesthete_search(text, jsonb) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION aesthete_dev_demo_seed() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00244_aesthete_match_rpc.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION aesthete_dev_demo_seed() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00245_aesthete_behavior_stats.sql
DO $g$ BEGIN
  REVOKE ALL ON product_behavior_stats FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00245_aesthete_behavior_stats.sql
DO $g$ BEGIN
  GRANT SELECT ON product_behavior_stats TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00245_aesthete_behavior_stats.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION refresh_product_behavior_stats() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00245_aesthete_behavior_stats.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION refresh_product_behavior_stats() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00246_aesthete_quiz_bridge.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION process_style_quiz(jsonb, jsonb) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00246_aesthete_quiz_bridge.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_recommendations(uuid, text, int, int) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00246_aesthete_quiz_bridge.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_recommendations(uuid, text, int, int) TO anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00247_aesthete_ask_knn.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION aesthete_ask_knn(vector, jsonb) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00247_aesthete_ask_knn.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION aesthete_ask_knn(vector, jsonb) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_primary_archetype(uuid) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION get_taste_refit_designers() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION get_taste_refit_payload(uuid) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION apply_taste_refit(uuid, real[], timestamptz, jsonb) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION preview_taste_update(bigint) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION get_designer_reliability_inputs(uuid) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION apply_designer_reliability(uuid, real, jsonb, jsonb) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION refresh_designer_teaching_stats() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION apply_starvation_decay() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_taste_refit_designers() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_taste_refit_payload(uuid) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION apply_taste_refit(uuid, real[], timestamptz, jsonb) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION preview_taste_update(bigint) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION get_designer_reliability_inputs(uuid) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION apply_designer_reliability(uuid, real, jsonb, jsonb) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION refresh_designer_teaching_stats() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00248_aesthete_nightly.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION apply_starvation_decay() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION enqueue_portfolio_embed() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_geometric_median(vector[]) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _aesthete_interpretable_groups() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION recompute_portfolio_centroid(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION seed_house_from_validated_catalog() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION derive_signature_biases(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION match_designers_for_client(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION aesthete_house_portfolio_nightly() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION recompute_portfolio_centroid(uuid) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION seed_house_from_validated_catalog() TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION derive_signature_biases(uuid) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION match_designers_for_client(uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION aesthete_house_portfolio_nightly() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION _aesthete_geometric_median(vector[]) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00249_aesthete_house_portfolio.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION _aesthete_interpretable_groups() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00250_aesthete_audit_jobs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION claim_aesthete_jobs(text, int) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00250_aesthete_audit_jobs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION claim_aesthete_jobs(text, int) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00250_aesthete_audit_jobs.sql
DO $g$ BEGIN
  REVOKE ALL ON ask_embed_cache FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00250_aesthete_audit_jobs.sql
DO $g$ BEGIN
  GRANT ALL ON ask_embed_cache TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00250_aesthete_audit_jobs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION aesthete_jobs_janitor() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00250_aesthete_audit_jobs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION aesthete_jobs_janitor() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00250_aesthete_audit_jobs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION run_aesthete_drift_audit(timestamptz) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00250_aesthete_audit_jobs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION run_aesthete_drift_audit(timestamptz) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00251_aesthete_why_phrases_breadth.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION _ae_pick_why_phrase(text, text, text) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00255_feedback_layer.sql
DO $g$ BEGIN
  GRANT SELECT, INSERT ON public.feedback TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00255_feedback_layer.sql
DO $g$ BEGIN
  GRANT SELECT ON public.feedback_events TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00255_feedback_layer.sql
DO $g$ BEGIN
  GRANT ALL ON public.feedback TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00255_feedback_layer.sql
DO $g$ BEGIN
  GRANT ALL ON public.feedback_events TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00255_feedback_layer.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.set_feedback_status(UUID, TEXT, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00255_feedback_layer.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.react_to_feedback(UUID, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00255_feedback_layer.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.reply_to_feedback(UUID, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00255_feedback_layer.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.mark_feedback_seen(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00257_realtime_project_authorization.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.realtime_project_access(text) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00258_edge_settings_vault.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.app_setting(text) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00258_edge_settings_vault.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.app_setting(text) FROM anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00258_edge_settings_vault.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.app_setting(text) FROM authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00260_clone_proposal_carry_boards.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION clone_proposal(UUID, TEXT, TEXT) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00260_clone_proposal_carry_boards.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION clone_proposal(UUID, TEXT, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00263_scope_reorder_rpcs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.reorder_proposal_items(uuid, uuid[]) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00263_scope_reorder_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.reorder_proposal_items(uuid, uuid[]) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00263_scope_reorder_rpcs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.reorder_proposal_scope_rooms(uuid, uuid[]) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00263_scope_reorder_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.reorder_proposal_scope_rooms(uuid, uuid[]) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00264_board_sections_status.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION clone_proposal(UUID, TEXT, TEXT) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00264_board_sections_status.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION clone_proposal(UUID, TEXT, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00266_document_shares.sql
DO $g$ BEGIN
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.document_shares TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00266_document_shares.sql
DO $g$ BEGIN
  GRANT ALL ON public.document_shares TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00266_document_shares.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.create_document_share(UUID, TEXT, JSONB, TIMESTAMPTZ) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00266_document_shares.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.revoke_document_share(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00266_document_shares.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.create_document_share(UUID, TEXT, JSONB, TIMESTAMPTZ) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00266_document_shares.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.revoke_document_share(UUID) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00266_document_shares.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.resolve_document_share(TEXT) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00266_document_shares.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.resolve_document_share(TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.item_feedback_gate(UUID, UUID, UUID) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT SELECT, INSERT ON public.item_feedback TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT SELECT ON public.item_feedback_events TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT ALL ON public.item_feedback TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT ALL ON public.item_feedback_events TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.notify_item_feedback(UUID) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.reply_to_item_feedback(UUID, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.resolve_item_feedback(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.reopen_item_feedback(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.item_feedback_after_insert() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.item_feedback_gate(p_proposal_item_id uuid, p_ffe_item_id uuid, p_board_item_id uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.notify_item_feedback(p_feedback_id uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.reopen_item_feedback(p_feedback_id uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.reply_to_item_feedback(p_feedback_id uuid, p_body text) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.resolve_item_feedback(p_feedback_id uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.item_feedback_gate(uuid, uuid, uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.reply_to_item_feedback(uuid, text) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.resolve_item_feedback(uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.reopen_item_feedback(uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00267_item_feedback.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.notify_item_feedback(uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00269_carry_custom_fields.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION clone_proposal(UUID, TEXT, TEXT) FROM PUBLIC;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00269_carry_custom_fields.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION clone_proposal(UUID, TEXT, TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00270_suggestion_events.sql
DO $g$ BEGIN
  GRANT SELECT, INSERT ON public.suggestion_events TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00270_suggestion_events.sql
DO $g$ BEGIN
  GRANT ALL ON public.suggestion_events TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00271_taught_alternatives_rpcs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.find_taught_alternatives(uuid, int) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00271_taught_alternatives_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.find_taught_alternatives(uuid, int) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00271_taught_alternatives_rpcs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.swap_line_to_product(uuid, uuid, uuid, int) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00271_taught_alternatives_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.swap_line_to_product(uuid, uuid, uuid, int) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00271_taught_alternatives_rpcs.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.escalate_item_feedback_to_decision(uuid, uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00271_taught_alternatives_rpcs.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.escalate_item_feedback_to_decision(uuid, uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00273_continue_board_in_project.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.continue_board_in_project(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00273_continue_board_in_project.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.continue_board_in_project(uuid) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00276_direct_orders.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.create_direct_order(UUID, INTEGER) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00276_direct_orders.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.create_direct_order(UUID, INTEGER) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00277_refund_reconciliation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.apply_invoice_payment_effects(UUID) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00277_refund_reconciliation.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.apply_invoice_payment_effects(UUID) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00281_field_parties.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.normalize_phone_e164(TEXT) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00281_field_parties.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.normalize_phone_e164(TEXT) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00281_field_parties.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.normalize_party_phone_e164() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00281_field_parties.sql
DO $g$ BEGIN
  GRANT SELECT ON public.people_directory TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00282_sms_core.sql
DO $g$ BEGIN
  GRANT SELECT ON public.sms_conversations TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00282_sms_core.sql
DO $g$ BEGIN
  GRANT SELECT ON public.sms_messages TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00282_sms_core.sql
DO $g$ BEGIN
  GRANT ALL ON public.sms_conversations TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00282_sms_core.sql
DO $g$ BEGIN
  GRANT ALL ON public.sms_messages TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00282_sms_core.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.apply_field_effect(UUID, JSONB, TEXT, UUID) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00282_sms_core.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.review_sms_message(UUID, TEXT, JSONB) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00282_sms_core.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.review_sms_message(UUID, TEXT, JSONB) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00282_sms_core.sql
DO $g$ BEGIN
  GRANT SELECT ON public.field_activity_summary TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00282_sms_core.sql
DO $g$ BEGIN
  GRANT SELECT ON public.field_activity_summary TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00283_field_links.sql
DO $g$ BEGIN
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.field_link_tokens TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00283_field_links.sql
DO $g$ BEGIN
  GRANT ALL ON public.field_link_tokens TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00283_field_links.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.create_field_link(UUID) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00283_field_links.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.revoke_field_link(UUID) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00283_field_links.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.resolve_field_link(TEXT) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00283_field_links.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.create_field_link(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00283_field_links.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.revoke_field_link(UUID) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00283_field_links.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.resolve_field_link(TEXT) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00284_field_dispatch_wiring.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.create_field_link(UUID) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00284_field_dispatch_wiring.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.create_field_link(UUID) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00284_field_dispatch_wiring.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.fc_dispatch_court_assignment() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00284_field_dispatch_wiring.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.fc_dispatch_task_assignment() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00284_field_dispatch_wiring.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.fc_dispatch_optin_invite() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00285_design_request_submit.sql
DO $g$ BEGIN
  GRANT SELECT ON public.lead_room_scans TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00285_design_request_submit.sql
DO $g$ BEGIN
  GRANT ALL ON public.lead_room_scans TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00285_design_request_submit.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.submit_design_request(uuid[], text, uuid, text, text, text, uuid, text, uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00285_design_request_submit.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.submit_design_request(uuid[], text, uuid, text, text, text, uuid, text, uuid) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00286_design_request_pool_claim.sql
DO $g$ BEGIN
  GRANT SELECT ON public.open_design_requests TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00286_design_request_pool_claim.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.claim_design_request(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00286_design_request_pool_claim.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.claim_design_request(uuid) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00289_design_request_client_status_notifications.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.claim_design_request(uuid) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00289_design_request_client_status_notifications.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.claim_design_request(uuid) TO authenticated, service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00289_design_request_client_status_notifications.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.notify_design_request_status_change() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00290_designer_invite_foundation.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.fc_sync_is_designer_from_role() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.record_activation_event(uuid, text, jsonb) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_project_created() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_proposal_created() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_proposal_sent() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_proposal_signed() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_design_request_claimed() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_client_added() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_first_capture() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_invoice_sent() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_payment_received() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00291_activation_event_bridge.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_hours_logged() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00292_designer_onboarding_enrollment.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.enroll_designer_onboarding(uuid) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00292_designer_onboarding_enrollment.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.ae_dispatch_milestone_notification() FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00295_studio_workspace_provisioning.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.generate_unique_org_slug(text) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00295_studio_workspace_provisioning.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public._provision_studio(uuid, text) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00295_studio_workspace_provisioning.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.create_studio_workspace(text) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00295_studio_workspace_provisioning.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.create_studio_workspace(text) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00295_studio_workspace_provisioning.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.accept_workspace_invitation(text) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00295_studio_workspace_provisioning.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.accept_workspace_invitation(text) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00295_studio_workspace_provisioning.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.decline_workspace_invitation(text) FROM PUBLIC, anon;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00295_studio_workspace_provisioning.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.decline_workspace_invitation(text) TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00295_studio_workspace_provisioning.sql
DO $g$ BEGIN
  REVOKE EXECUTE ON FUNCTION public.fc_provision_studio_on_designer() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  GRANT SELECT ON public.agent_tasks TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  GRANT SELECT ON public.agent_task_audit TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.enqueue_agent_task(text, jsonb, text, int, text, text, uuid, text, timestamptz, int, text, text, text, uuid, numeric, jsonb, text) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.claim_agent_tasks(text[], int, text, interval) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.complete_agent_task(uuid, text, jsonb, numeric, text, boolean, text) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.review_agent_task(uuid, text, text, text, jsonb, jsonb) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.requeue_agent_task(uuid, text, text) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.cancel_agent_task(uuid, text, text) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.agent_queue_stats() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.enqueue_agent_task(text, jsonb, text, int, text, text, uuid, text, timestamptz, int, text, text, text, uuid, numeric, jsonb, text) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.claim_agent_tasks(text[], int, text, interval) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.complete_agent_task(uuid, text, jsonb, numeric, text, boolean, text) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.review_agent_task(uuid, text, text, text, jsonb, jsonb) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.requeue_agent_task(uuid, text, text) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.cancel_agent_task(uuid, text, text) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00297_agent_tasks_queue.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.agent_queue_stats() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00299_agent_roles.sql
DO $g$ BEGIN
  GRANT USAGE ON SCHEMA public TO agent_writer;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00299_agent_roles.sql
DO $g$ BEGIN
  GRANT SELECT, INSERT ON public.agent_tasks TO agent_writer;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00299_agent_roles.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.enqueue_agent_task(text, jsonb, text, int, text, text, uuid, text, timestamptz, int, text, text, text, uuid, numeric, jsonb, text) TO agent_writer;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00299_agent_roles.sql
DO $g$ BEGIN
  GRANT agent_reader TO postgres;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00299_agent_roles.sql
DO $g$ BEGIN
  GRANT agent_writer TO postgres;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00300_queue_groom.sql
DO $g$ BEGIN
  GRANT SELECT ON public.job_runs TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00300_queue_groom.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.groom_agent_tasks(interval, interval, interval) FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00300_queue_groom.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.groom_agent_tasks(interval, interval, interval) TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00301_marketplace_vitals.sql
DO $g$ BEGIN
  GRANT SELECT ON public.metric_thresholds TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00301_marketplace_vitals.sql
DO $g$ BEGIN
  REVOKE ALL ON public.marketplace_vitals FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00301_marketplace_vitals.sql
DO $g$ BEGIN
  GRANT SELECT ON public.marketplace_vitals TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00301_marketplace_vitals.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.refresh_marketplace_vitals() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00301_marketplace_vitals.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.refresh_marketplace_vitals() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00301_marketplace_vitals.sql
DO $g$ BEGIN
  REVOKE ALL ON FUNCTION public.get_marketplace_vitals() FROM PUBLIC, anon, authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00301_marketplace_vitals.sql
DO $g$ BEGIN
  GRANT EXECUTE ON FUNCTION public.get_marketplace_vitals() TO service_role;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00302_daily_briefs.sql
DO $g$ BEGIN
  GRANT SELECT ON public.daily_briefs TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00303_cowork_intake_bridge.sql
DO $g$ BEGIN
  GRANT SELECT ON public.bridge_state TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00306_catalog_normalizer_staging.sql
DO $g$ BEGIN
  GRANT SELECT ON public.catalog_feed_batches TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;

-- 00306_catalog_normalizer_staging.sql
DO $g$ BEGIN
  GRANT SELECT ON public.catalog_feed_items TO authenticated;
EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;
END $g$;
