// Deno tests for the pure parse-room-scan lib.
// Run: deno test --config supabase/functions/deno.json supabase/functions/parse-room-scan/lib.test.ts
//
// The synthetic CapturedRoom below is generated by the INVERSE of the parser's
// pipeline: a hand-authored true plan (feet, NW origin) is pushed back through
// a deliberate ~15° global rotation + offset origin into an ARKit-like world
// frame (meters, column-major transforms, keyed-enum encoding). The parser must
// recover the true plan. Truth values asserted below are therefore known by
// construction (feet conversions are exact round-trips; see tolerances).
//
// NOTE: the canonical shared fixture
//   supabase/seed/fixtures/room-scans/elena-formal-dining.captured_room.json
// lands in a sibling task; the integration gate cross-checks the parser against
// it. These vectors are self-contained and author-owned.

import {
  assert,
  assertAlmostEquals,
  assertEquals,
} from "https://deno.land/std@0.168.0/testing/asserts.ts";
import {
  M_TO_FT,
  objectKeyFromUrl,
  parseCapturedRoom,
  PARSER_VERSION,
  type GeometryElement,
  type ParseResult,
} from "./lib.ts";

// ─── inverse pipeline (true plan feet → ARKit world) ────────────────────────

const M = M_TO_FT;
const THETA_DEG = 15;
const THETA = (THETA_DEG * Math.PI) / 180;
const O = { x: 2.5, z: -1.3 }; // origin offset, meters (in the rotated frame)

function rotCCW(x: number, z: number, ang: number): { x: number; z: number } {
  const c = Math.cos(ang), s = Math.sin(ang);
  return { x: x * c - z * s, z: x * s + z * c };
}
// planFt → world XZ (meters): /M, + offset, rotate by +θ
function invWorld(xFt: number, zFt: number): { x: number; z: number } {
  return rotCCW(xFt / M + O.x, zFt / M + O.z, THETA);
}
// column-major 4×4 with x-basis at world heading `hw`, translation (wx,wy,wz)
function mat(hw: number, wx: number, wy: number, wz: number): number[] {
  const cx = Math.cos(hw), sx = Math.sin(hw);
  return [
    cx, 0, sx, 0, //  col0 = x-basis
    0, 1, 0, 0, //   col1 = y-basis (up)
    -sx, 0, cx, 0, // col2 = z-basis
    wx, wy, wz, 1, //  col3 = translation
  ];
}

function wallSurf(
  id: string, x1: number, z1: number, x2: number, z2: number,
  conf: string, heightFt = 8,
) {
  const phi = Math.atan2(z2 - z1, x2 - x1);
  const lenFt = Math.hypot(x2 - x1, z2 - z1);
  const w = invWorld((x1 + x2) / 2, (z1 + z2) / 2);
  return {
    category: { wall: {} },
    confidence: { [conf]: {} },
    dimensions: [lenFt / M, heightFt / M, 0.1],
    identifier: id,
    transform: mat(phi + THETA, w.x, heightFt / 2 / M, w.z),
  };
}

function windowSurf(
  id: string, parentId: string, cxFt: number, czFt: number,
  widthFt: number, heightFt: number, sillFt: number,
) {
  const w = invWorld(cxFt, czFt);
  return {
    category: { window: {} },
    confidence: { high: {} },
    dimensions: [widthFt / M, heightFt / M, 0.05],
    identifier: id,
    parentIdentifier: parentId,
    transform: mat(THETA, w.x, (sillFt + heightFt / 2) / M, w.z),
  };
}

function doorSurf(
  id: string, parentId: string, cxFt: number, czFt: number,
  widthFt: number, heightFt: number, isOpen: boolean,
) {
  const w = invWorld(cxFt, czFt);
  return {
    category: { door: { isOpen } },
    confidence: { high: {} },
    dimensions: [widthFt / M, heightFt / M, 0.05],
    identifier: id,
    parentIdentifier: parentId,
    transform: mat(THETA, w.x, heightFt / 2 / M, w.z),
  };
}

function objectSurf(
  id: string, cat: string, cxFt: number, czFt: number, rotDeg: number,
  wFt: number, hFt: number, dFt: number, conf: string,
) {
  const w = invWorld(cxFt, czFt);
  return {
    category: { [cat]: {} },
    confidence: { [conf]: {} },
    dimensions: [wFt / M, hFt / M, dFt / M],
    identifier: id,
    transform: mat((rotDeg * Math.PI) / 180 + THETA, w.x, hFt / 2 / M, w.z),
  };
}

function floorSurf(id: string, cornersFt: Array<[number, number]>) {
  return {
    category: { floor: {} },
    confidence: { high: {} },
    dimensions: [19 / M, 0.1, 14 / M],
    identifier: id,
    transform: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], // identity
    polygonCorners: cornersFt.map(([x, z]) => {
      const w = invWorld(x, z);
      return [w.x, 0, w.z];
    }),
  };
}

// Phase-1 gate failure shape: polygonCorners arrive already PRE-TRANSFORMED
// into world space (a producer bug — they should be LOCAL, per floorSurf()
// above), but ship alongside a real (non-identity) `transform` anyway. The
// parser applies floor0.transform to floor0.polygonCorners unconditionally
// (lib.ts's floor-polygon step), so this double-transforms the floor: a pure
// 90° extra rotation, zero translation, lands the true 19×14 rectangle
// rotated a net 90° relative to the (correctly, singly-transformed) walls —
// width_ft/depth_ft come out swapped (~14×19 instead of ~19×14).
function malformedWorldSpaceFloorSurf(id: string, cornersFt: Array<[number, number]>) {
  return {
    category: { floor: {} },
    confidence: { high: {} },
    dimensions: [19 / M, 0.1, 14 / M],
    identifier: id,
    transform: mat(Math.PI / 2, 0, 0, 0), // pure 90° rotation, no translation
    polygonCorners: cornersFt.map(([x, z]) => {
      const w = invWorld(x, z); // already world-space — the bug
      return [w.x, 0, w.z];
    }),
  };
}

// UUIDs (ARKit identifiers are Foundation UUIDs)
const ID = {
  wNWwest: "11111111-1111-4111-8111-111111111111",
  wNWeast: "22222222-2222-4222-8222-222222222222",
  wEast: "33333333-3333-4333-8333-333333333333",
  wSouth: "44444444-4444-4444-8444-444444444444",
  wWest: "55555555-5555-4555-8555-555555555555",
  win1: "66666666-6666-4666-8666-666666666666",
  win2: "77777777-7777-4777-8777-777777777777",
  door: "88888888-8888-4888-8888-888888888888",
  sofa: "99999999-9999-4999-8999-999999999999",
  table: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
  chair: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
  console: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
};

// Full synthetic CapturedRoom (keyed-enum encoding), ~15° rotated, offset origin.
function buildCapturedRoom(): Record<string, unknown> {
  return {
    version: "17.0",
    identifier: "0f0f0f0f-0f0f-4f0f-8f0f-0f0f0f0f0f0f",
    story: 0,
    walls: [
      wallSurf(ID.wNWwest, 0, 0, 13, 0, "high"), // North, west run
      wallSurf(ID.wNWeast, 13, 0, 19, 0, "low"), // North, east run (low conf)
      wallSurf(ID.wEast, 19, 0, 19, 14, "high"), // East
      wallSurf(ID.wSouth, 19, 14, 0, 14, "high"), // South (reversed dir on purpose)
      wallSurf(ID.wWest, 0, 14, 0, 0, "high"), // West (reversed dir on purpose)
    ],
    doors: [doorSurf(ID.door, ID.wSouth, 17, 14, 3, 7, false)],
    windows: [
      windowSurf(ID.win1, ID.wWest, 0, 4.5, 4, 4.5, 2.5),
      windowSurf(ID.win2, ID.wWest, 0, 10.5, 4, 4.5, 2.5),
    ],
    openings: [],
    floors: [floorSurf("d0d0d0d0-d0d0-4d0d-8d0d-d0d0d0d0d0d0", [
      [0, 0], [19, 0], [19, 14], [0, 14],
    ])],
    objects: [
      objectSurf(ID.sofa, "sofa", 17.1, 7.0, 90, 7.0, 2.6, 3.0, "high"),
      objectSurf(ID.table, "table", 13.6, 7.5, 0, 4.0, 1.4, 2.0, "medium"),
      objectSurf(ID.chair, "chair", 6.0, 2.9, 0, 2.5833, 2.5, 2.5833, "high"),
      objectSurf(ID.console, "television", 0.75, 8.1, 90, 5.0, 1.8, 1.5, "high"),
    ],
    sections: [],
  };
}

// Recursively convert no-payload keyed enums ({"high":{}} → "high") to bare
// strings, LEAVING payload-carrying enums keyed ({"door":{"isOpen":false}}).
// deno-lint-ignore no-explicit-any
function toBareEnums(v: any): any {
  if (Array.isArray(v)) return v.map(toBareEnums);
  if (v && typeof v === "object") {
    const keys = Object.keys(v);
    if (
      keys.length === 1 &&
      v[keys[0]] &&
      typeof v[keys[0]] === "object" &&
      !Array.isArray(v[keys[0]]) &&
      Object.keys(v[keys[0]]).length === 0
    ) {
      return keys[0]; // bare-string form
    }
    const out: Record<string, unknown> = {};
    for (const k of keys) out[k] = toBareEnums(v[k]);
    return out;
  }
  return v;
}

// ─── helpers for assertions ─────────────────────────────────────────────────

const TOL_FT = 5e-3; // feet tolerance — round4 + float round-trip
const TOL_DEG = 5e-3;

function walls(r: ParseResult): GeometryElement[] {
  return r.elements.filter((e) => e.kind === "wall");
}
function wallByLabel(r: ParseResult, label: string): GeometryElement {
  const w = walls(r).find((e) => e.label === label);
  assert(w, `expected a wall labelled "${label}"`);
  return w!;
}
function isAxisAligned(w: GeometryElement): boolean {
  return Math.min(Math.abs(w.x1_ft! - w.x2_ft!), Math.abs(w.z1_ft! - w.z2_ft!)) < TOL_FT;
}

// ════════════════════════════════════════════════════════════════════════════
// (a) full synthetic — keyed-enum encoding, 15° rotation, offset origin
// ════════════════════════════════════════════════════════════════════════════

Deno.test("(a) recovers frame: yaw ≈ 15°, offset ≈ O, NW origin", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  assertAlmostEquals(r.header.origin_yaw_deg, THETA_DEG, TOL_DEG);
  assertAlmostEquals(r.header.origin_offset_m.x, O.x, 1e-3);
  assertAlmostEquals(r.header.origin_offset_m.z, O.z, 1e-3);
  // floor bbox min corner sits at (0,0) → NW origin
  let minX = Infinity, minZ = Infinity;
  for (const [x, z] of r.header.floor_polygon) { minX = Math.min(minX, x); minZ = Math.min(minZ, z); }
  assertAlmostEquals(minX, 0, TOL_FT);
  assertAlmostEquals(minZ, 0, TOL_FT);
});

Deno.test("(a) overall dimensions + area exact in feet", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  assertAlmostEquals(r.header.width_ft, 19, TOL_FT);
  assertAlmostEquals(r.header.depth_ft, 14, TOL_FT);
  assertAlmostEquals(r.header.wall_height_ft, 8, TOL_FT);
  assertAlmostEquals(r.header.floor_area_sqft, 19 * 14, 0.05);
  assertEquals(r.header.wall_thickness_ft, null);
  assertEquals(r.header.parser_version, PARSER_VERSION);
  assertEquals(r.header.source_schema_version, "17.0");
  assertEquals(r.header.units, "ft");
});

Deno.test("(a) de-rotation lands every wall axis-aligned", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  assertEquals(walls(r).length, 5);
  for (const w of walls(r)) assert(isAxisAligned(w), `wall "${w.label}" not axis-aligned`);
});

Deno.test("(a) compass labels + collinear run qualifiers", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  const nwWest = wallByLabel(r, "North wall (west run)");
  const nwEast = wallByLabel(r, "North wall (east run)");
  wallByLabel(r, "East wall");
  wallByLabel(r, "South wall");
  wallByLabel(r, "West wall");
  // the east run is the low-confidence one
  assertEquals(nwEast.confidence, "low");
  assertEquals(nwWest.confidence, "high");
  // both north runs lie on z ≈ 0
  assertAlmostEquals(nwWest.z1_ft!, 0, TOL_FT);
  assertAlmostEquals(nwEast.z1_ft!, 0, TOL_FT);
});

Deno.test("(a) windows: from/to/sill/head vs hand-computed truth", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  const wins = r.elements
    .filter((e) => e.kind === "window")
    .sort((a, b) => a.from_ft! - b.from_ft!);
  assertEquals(wins.length, 2);
  // window 1: centre z=4.5, width 4 → from 2.5 to 6.5; sill 2.5, head 7
  assertAlmostEquals(wins[0].from_ft!, 2.5, TOL_FT);
  assertAlmostEquals(wins[0].to_ft!, 6.5, TOL_FT);
  assertAlmostEquals(wins[0].sill_ft!, 2.5, TOL_FT);
  assertAlmostEquals(wins[0].head_ft!, 7, TOL_FT);
  // window 2: centre z=10.5 → from 8.5 to 12.5
  assertAlmostEquals(wins[1].from_ft!, 8.5, TOL_FT);
  assertAlmostEquals(wins[1].to_ft!, 12.5, TOL_FT);
  assertAlmostEquals(wins[1].sill_ft!, 2.5, TOL_FT);
  // both resolve to the West wall
  const west = wallByLabel(r, "West wall");
  assertEquals(wins[0].wall_ref, west.apple_id);
  assertEquals(wins[1].wall_ref, west.apple_id);
  // swing never fabricated
  assertEquals(wins[0].swing, null);
  assertEquals(wins[0].swing_inward, null);
});

Deno.test("(a) door: placement, floor sill, isOpen → extras", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  const door = r.elements.find((e) => e.kind === "door")!;
  assert(door);
  assertAlmostEquals(door.from_ft!, 15.5, TOL_FT);
  assertAlmostEquals(door.to_ft!, 18.5, TOL_FT);
  assertAlmostEquals(door.sill_ft!, 0, TOL_FT);
  assertAlmostEquals(door.head_ft!, 7, TOL_FT);
  assertAlmostEquals(door.width_ft!, 3, TOL_FT);
  assertEquals(door.extras.isOpen, false);
  assertEquals(door.swing, null); // never fabricated
  const south = wallByLabel(r, "South wall");
  assertEquals(door.wall_ref, south.apple_id);
});

Deno.test("(a) objects: de-rotation, dims, label, centre", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  const objs = r.elements.filter((e) => e.kind === "object");
  assertEquals(objs.length, 4);
  const sofa = objs.find((o) => o.cat === "sofa")!;
  assertAlmostEquals(sofa.rotation_deg!, 90, TOL_DEG);
  assertAlmostEquals(sofa.width_ft!, 7, TOL_FT);
  assertAlmostEquals(sofa.depth_ft!, 3, TOL_FT);
  assertAlmostEquals(sofa.center_x_ft!, 17.1, 1e-2);
  assertAlmostEquals(sofa.center_z_ft!, 7.0, 1e-2);
  assertEquals(sofa.label, "sofa · 84″ × 36″");
  const table = objs.find((o) => o.cat === "table")!;
  assertEquals(table.label, "table · 48″ × 24″");
  assertAlmostEquals(table.rotation_deg!, 0, TOL_DEG);
  const chair = objs.find((o) => o.cat === "chair")!;
  assertEquals(chair.label, "chair · 31″ × 31″");
  const tv = objs.find((o) => o.cat === "television")!;
  assertEquals(tv.label, "television · 60″ × 18″");
  assertAlmostEquals(tv.rotation_deg!, 90, TOL_DEG);
});

Deno.test("(a) confidence_summary counts walls + objects, all three levels honest", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  // walls: 4 high + 1 low; objects: 3 high + 1 medium
  assertEquals(r.header.confidence_summary, { high: 7, medium: 1, low: 1 });
});

Deno.test("(a) walls precede openings; positions are a dense 0..n-1 sequence", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  const kinds = r.elements.map((e) => e.kind);
  const lastWall = kinds.lastIndexOf("wall");
  const firstOpening = kinds.findIndex((k) => k === "window" || k === "door" || k === "opening");
  assert(lastWall < firstOpening, "all walls must precede openings in the array");
  const positions = r.elements.map((e) => e.position);
  assertEquals(positions, positions.map((_, i) => i));
  // every element carries a valid parseable apple_id
  for (const e of r.elements) assert(e.apple_id && /^[0-9a-f-]{36}$/.test(e.apple_id));
});

// ════════════════════════════════════════════════════════════════════════════
// (b) bare-string enum form → identical output
// ════════════════════════════════════════════════════════════════════════════

Deno.test("(b) bare-string enums produce identical output to keyed", () => {
  const keyed = parseCapturedRoom(buildCapturedRoom());
  const bare = parseCapturedRoom(toBareEnums(buildCapturedRoom()));
  assertEquals(bare, keyed);
});

// ════════════════════════════════════════════════════════════════════════════
// (c) malformed / partial inputs → warnings, never throws
// ════════════════════════════════════════════════════════════════════════════

Deno.test("(c) non-object input → warning, empty result, no throw", () => {
  for (const bad of [null, undefined, 42, "nope", []]) {
    const r = parseCapturedRoom(bad);
    assert(r.warnings.length > 0);
    assertEquals(r.elements, []);
  }
});

Deno.test("(c) no walls → warning, degenerate header", () => {
  const r = parseCapturedRoom({ version: "17.0", walls: [] });
  assert(r.warnings.some((w) => /no walls/.test(w)));
  assertEquals(r.elements, []);
  assertEquals(r.header.source_schema_version, "17.0");
});

Deno.test("(c) missing floors[] → derives floor from wall-endpoint hull + warns", () => {
  const room = buildCapturedRoom();
  delete (room as Record<string, unknown>).floors;
  const r = parseCapturedRoom(room);
  assert(r.warnings.some((w) => /hull/.test(w)));
  // hull of a rectangular room's wall endpoints still ≈ 19 × 14
  assertAlmostEquals(r.header.width_ft, 19, 0.1);
  assertAlmostEquals(r.header.depth_ft, 14, 0.1);
  assert(r.header.floor_polygon.length >= 3);
});

Deno.test("(c) orphan opening (bad parentIdentifier) → warning + wall_ref null, still landed", () => {
  const room = buildCapturedRoom();
  (room.windows as Array<Record<string, unknown>>)[0].parentIdentifier =
    "deadbeef-dead-4bee-8bee-deadbeefdead"; // no such wall
  const r = parseCapturedRoom(room);
  assert(r.warnings.some((w) => /no matching wall/.test(w)));
  const orphan = r.elements.find((e) => e.kind === "window" && e.wall_ref === null);
  assert(orphan, "orphan window should still be emitted with wall_ref null");
  // constraint-required fields stay non-null even for an orphan
  assert(Number.isFinite(orphan!.from_ft!));
  assert(Number.isFinite(orphan!.to_ft!));
});

Deno.test("(c) unknown object category → kept + warned, never thrown", () => {
  const room = buildCapturedRoom();
  (room.objects as Array<Record<string, unknown>>)[0].category = { spaceship: {} };
  const r = parseCapturedRoom(room);
  assert(r.warnings.some((w) => /unrecognized category 'spaceship'/.test(w)));
  const obj = r.elements.find((e) => e.kind === "object" && e.cat === "spaceship");
  assert(obj, "unknown-category object still emitted");
  assertEquals(obj!.extras.raw_category, "spaceship");
});

Deno.test("(c) garbage transform on one wall → skipped with warning, rest parse", () => {
  const room = buildCapturedRoom();
  (room.walls as Array<Record<string, unknown>>)[0].transform = ["x", null, {}];
  const r = parseCapturedRoom(room);
  assert(r.warnings.some((w) => /unusable transform/.test(w)));
  assert(walls(r).length === 4); // the other four still parse
});

Deno.test("(c) floor pre-transformed into world space (double-transform bug) → extent-divergence warning", () => {
  const room = buildCapturedRoom();
  room.floors = [
    malformedWorldSpaceFloorSurf(
      "d0d0d0d0-d0d0-4d0d-8d0d-d0d0d0d0d0d0",
      [[0, 0], [19, 0], [19, 14], [0, 14]],
    ),
  ];
  const r = parseCapturedRoom(room);
  assert(
    r.warnings.some((w) => /floor extent diverges from wall extent/.test(w)),
    `expected a floor/wall extent-divergence warning; got: ${JSON.stringify(r.warnings)}`,
  );
  // A warning, not a rejection — nothing throws, and walls still parse fine
  // (only the floor's own frame was malformed).
  assertEquals(walls(r).length, 5);
  // width_ft/depth_ft land roughly swapped by the extra 90° rotation.
  assertAlmostEquals(r.header.width_ft, 14, 0.2);
  assertAlmostEquals(r.header.depth_ft, 19, 0.2);
});

Deno.test("(c) well-formed floor never triggers the extent-divergence warning", () => {
  const r = parseCapturedRoom(buildCapturedRoom());
  assert(!r.warnings.some((w) => /floor extent diverges/.test(w)));
});

// ════════════════════════════════════════════════════════════════════════════
// (d) determinism
// ════════════════════════════════════════════════════════════════════════════

Deno.test("(d) two runs are byte-identical (deterministic)", () => {
  const a = parseCapturedRoom(buildCapturedRoom());
  const b = parseCapturedRoom(buildCapturedRoom());
  assertEquals(JSON.stringify(a), JSON.stringify(b));
});

// ════════════════════════════════════════════════════════════════════════════
// contract test — build the prototype ROOM shape from parser output and assert
// every field the two projections read (room-view-prototype.html L365–386) exists
// ════════════════════════════════════════════════════════════════════════════

Deno.test("contract: prototype ROOM shape is fully constructible from output", () => {
  const r = parseCapturedRoom(buildCapturedRoom());

  const wallsOut = walls(r).map((w) => ({
    x1: w.x1_ft!, z1: w.z1_ft!, x2: w.x2_ft!, z2: w.z2_ft!,
    conf: w.confidence, name: w.label,
    len: Math.hypot(w.x2_ft! - w.x1_ft!, w.z2_ft! - w.z1_ft!),
  }));
  const windowsOut = r.elements.filter((e) => e.kind === "window").map((o) => ({
    wall: o.wall_ref, from: o.from_ft!, to: o.to_ft!, sill: o.sill_ft!, head: o.head_ft!,
  }));
  const doorEl = r.elements.find((e) => e.kind === "door")!;
  const doorOut = { wall: doorEl.wall_ref, from: doorEl.from_ft!, to: doorEl.to_ft!, h: doorEl.head_ft! };
  const objectsOut = r.elements.filter((e) => e.kind === "object").map((o) => ({
    x: o.center_x_ft! - o.width_ft! / 2, z: o.center_z_ft! - o.depth_ft! / 2,
    w: o.width_ft!, d: o.depth_ft!, h: o.height_ft!, cat: o.cat!, label: o.label!,
  }));
  const ROOM = {
    width: r.header.width_ft,
    depth: r.header.depth_ft,
    wallH: r.header.wall_height_ft,
    thick: r.header.wall_thickness_ft ?? 0.45, // drawing convention (schema stores null)
    walls: wallsOut,
    windows: windowsOut,
    door: doorOut,
    objects: objectsOut,
  };

  // top-level scalars the plan + orbit read
  for (const k of ["width", "depth", "wallH", "thick"] as const) {
    assert(Number.isFinite(ROOM[k]), `ROOM.${k} must be finite`);
  }
  // every field drawPlan()/orbit read off each wall
  assert(ROOM.walls.length > 0);
  for (const w of ROOM.walls) {
    for (const k of ["x1", "z1", "x2", "z2", "len"] as const) assert(Number.isFinite(w[k]));
    assert(typeof w.name === "string" && w.name.length > 0);
    assert(w.conf === "high" || w.conf === "medium" || w.conf === "low");
  }
  // window fields
  assert(ROOM.windows.length > 0);
  for (const w of ROOM.windows) {
    for (const k of ["from", "to", "sill", "head"] as const) assert(Number.isFinite(w[k]));
  }
  // door fields
  for (const k of ["from", "to", "h"] as const) assert(Number.isFinite(ROOM.door[k]));
  // object fields
  assert(ROOM.objects.length > 0);
  for (const o of ROOM.objects) {
    for (const k of ["x", "z", "w", "d", "h"] as const) assert(Number.isFinite(o[k]));
    assert(typeof o.cat === "string" && o.cat.length > 0);
    assert(typeof o.label === "string" && o.label.includes("″"));
  }
});

// ─── objectKeyFromUrl (shell helper, pure) ──────────────────────────────────

Deno.test("objectKeyFromUrl: split on /room-scans/, tolerate app variance + query", () => {
  assertEquals(
    objectKeyFromUrl("https://p.supabase.co/storage/v1/object/public/room-scans/u/s/CapturedRoom.json"),
    "u/s/CapturedRoom.json",
  );
  // signed url with a token query string
  assertEquals(
    objectKeyFromUrl("https://p.supabase.co/storage/v1/object/sign/room-scans/a/b/c.json?token=xyz"),
    "a/b/c.json",
  );
  // Patina Field's deeper segment layout still yields the tail
  assertEquals(
    objectKeyFromUrl("https://p/storage/v1/object/public/room-scans/field/2026/07/scan/CapturedRoom.json"),
    "field/2026/07/scan/CapturedRoom.json",
  );
  // already a bare bucket key
  assertEquals(objectKeyFromUrl("u/s/CapturedRoom.json"), "u/s/CapturedRoom.json");
  assertEquals(objectKeyFromUrl(""), null);
});
