/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 5e463ca1b39ce9159d3099d90027c50c)
interface __BaseEnv_CloudflareBindings {
	SUPABASE_UPSTREAM_URL: string;
	SUPABASE_JWT_ISSUER: string;
	SUPABASE_JWT_AUDIENCE: string;
	SUPABASE_JWKS_URL: string;
	CATALOG_SOURCE: string;
	CATALOG_HYPERDRIVE_PERCENT: string;
	LEGACY_FETCH_TIMEOUT_MS: string;
	COMPATIBILITY_FETCH_TIMEOUT_MS: string;
	WEBSOCKET_HANDSHAKE_TIMEOUT_MS: string;
	SCAN_ROUTES: string;
	SCAN_R2_ENDPOINT: string;
	SCAN_R2_BUCKET: string;
	MEDIA_UPLOADS: string;
	SCAN_R2_ORIGINALS_BUCKET: string;
	DB_FRESH?: Hyperdrive;
	DB_CATALOG_FRESH?: Hyperdrive;
	DB_PUBLIC_CACHE?: Hyperdrive;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface LocalEnv {
		SUPABASE_UPSTREAM_URL: string;
		SUPABASE_JWT_ISSUER: string;
		SUPABASE_JWT_AUDIENCE: string;
		SUPABASE_JWKS_URL: string;
		CATALOG_SOURCE: string;
		CATALOG_HYPERDRIVE_PERCENT: string;
		LEGACY_FETCH_TIMEOUT_MS: string;
		COMPATIBILITY_FETCH_TIMEOUT_MS: string;
		WEBSOCKET_HANDSHAKE_TIMEOUT_MS: string;
		SCAN_ROUTES: string;
		SCAN_R2_ENDPOINT: string;
		SCAN_R2_BUCKET: string;
		MEDIA_UPLOADS: string;
		SCAN_R2_ORIGINALS_BUCKET: string;
	}
	interface StagingEnv {
		DB_FRESH: Hyperdrive;
		DB_CATALOG_FRESH: Hyperdrive;
		DB_PUBLIC_CACHE: Hyperdrive;
		SUPABASE_UPSTREAM_URL: string;
		SUPABASE_JWT_ISSUER: string;
		SUPABASE_JWT_AUDIENCE: string;
		SUPABASE_JWKS_URL: string;
		CATALOG_SOURCE: string;
		CATALOG_HYPERDRIVE_PERCENT: string;
		LEGACY_FETCH_TIMEOUT_MS: string;
		COMPATIBILITY_FETCH_TIMEOUT_MS: string;
		WEBSOCKET_HANDSHAKE_TIMEOUT_MS: string;
		SCAN_ROUTES: string;
		SCAN_R2_ENDPOINT: string;
		SCAN_R2_BUCKET: string;
		MEDIA_UPLOADS: string;
		SCAN_R2_ORIGINALS_BUCKET: string;
	}
	interface ProductionEnv {
		DB_FRESH: Hyperdrive;
		DB_CATALOG_FRESH: Hyperdrive;
		DB_PUBLIC_CACHE: Hyperdrive;
		SUPABASE_UPSTREAM_URL: string;
		SUPABASE_JWT_ISSUER: string;
		SUPABASE_JWT_AUDIENCE: string;
		SUPABASE_JWKS_URL: string;
		CATALOG_SOURCE: string;
		CATALOG_HYPERDRIVE_PERCENT: string;
		LEGACY_FETCH_TIMEOUT_MS: string;
		COMPATIBILITY_FETCH_TIMEOUT_MS: string;
		WEBSOCKET_HANDSHAKE_TIMEOUT_MS: string;
		SCAN_ROUTES: string;
		SCAN_R2_ENDPOINT: string;
		SCAN_R2_BUCKET: string;
		MEDIA_UPLOADS: string;
		SCAN_R2_ORIGINALS_BUCKET: string;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_UPSTREAM_URL" | "SUPABASE_JWT_ISSUER" | "SUPABASE_JWT_AUDIENCE" | "SUPABASE_JWKS_URL" | "CATALOG_SOURCE" | "CATALOG_HYPERDRIVE_PERCENT" | "LEGACY_FETCH_TIMEOUT_MS" | "COMPATIBILITY_FETCH_TIMEOUT_MS" | "WEBSOCKET_HANDSHAKE_TIMEOUT_MS" | "SCAN_ROUTES" | "SCAN_R2_ENDPOINT" | "SCAN_R2_BUCKET" | "MEDIA_UPLOADS" | "SCAN_R2_ORIGINALS_BUCKET">> {}
}
