// scripts/gen-fulfillment-fonts.ts — generator for the BOH PO PDF's embedded
// brand fonts (S3). Reads the repo's OFL brand TTFs and emits
// supabase/functions/_shared/fulfillment-fonts.ts with each font base64-inlined
// so the fulfillment-po edge function is fully self-contained (nothing fetched
// at render time — the spike proved base64 data-URL Font.register genuinely
// embeds a FontFile2 TrueType stream, not a Helvetica fallback).
//
// Re-run after swapping a TTF:  deno run -A scripts/gen-fulfillment-fonts.ts
//
// Only the two families the PO paper actually uses are embedded — Playfair
// Display (masthead wordmark, R/M weights) + DM Mono (PO number + line table).
// Body/labels stay base-14 Helvetica (no embed) to avoid the 325 KB Inter.

import { encodeBase64 } from 'https://deno.land/std@0.224.0/encoding/base64.ts';

const FONT_DIR = new URL(
  '../apps/mobile/PatinaDesignKit/Sources/PatinaDesignKit/Resources/Fonts/',
  import.meta.url,
);

const FONTS: Array<{ constName: string; file: string }> = [
  { constName: 'PLAYFAIR_REGULAR_B64', file: 'PlayfairDisplay-Regular.ttf' },
  { constName: 'PLAYFAIR_MEDIUM_B64', file: 'PlayfairDisplay-Medium.ttf' },
  { constName: 'DM_MONO_REGULAR_B64', file: 'DMMono-Regular.ttf' },
];

const parts: string[] = [];
for (const { constName, file } of FONTS) {
  const bytes = await Deno.readFile(new URL(file, FONT_DIR));
  const b64 = encodeBase64(bytes);
  parts.push(`const ${constName} =\n  '${b64}';`);
  console.log(`${file}: ${bytes.length} bytes → ${b64.length} base64 chars`);
}

const out = `// AUTO-GENERATED by scripts/gen-fulfillment-fonts.ts — DO NOT hand-edit.
//
// Brand TTFs (SIL Open Font License) embedded as base64 so the fulfillment-po
// edge function renders the PO paper with brand fonts under the Deno edge
// runtime with nothing fetched at render time. The base64 data-URL
// Font.register path is spike-proven to embed a real FontFile2 TrueType stream
// (docs: S3 font spike, Task 1 — OUTCOME A). Regenerate with the script above.
//
// Families embedded: Playfair Display (masthead, weights 400/500) + DM Mono
// (PO number + line table). Body/labels use base-14 Helvetica (no embed).

import { Font } from 'npm:@react-pdf/renderer@4.3.0';

${parts.join('\n\n')}

let registered = false;

/** Register the PO paper's brand fonts exactly once (idempotent). Call before
 *  the first renderToBuffer; safe to call on every request. */
export function registerFulfillmentFonts(): void {
  if (registered) return;
  Font.register({
    family: 'Playfair Display',
    fonts: [
      { src: \`data:font/ttf;base64,\${PLAYFAIR_REGULAR_B64}\`, fontWeight: 400 },
      { src: \`data:font/ttf;base64,\${PLAYFAIR_MEDIUM_B64}\`, fontWeight: 500 },
    ],
  });
  Font.register({ family: 'DM Mono', src: \`data:font/ttf;base64,\${DM_MONO_REGULAR_B64}\` });
  // Never hyphenate the mono PO strings / line descriptions.
  Font.registerHyphenationCallback((word) => [word]);
  registered = true;
}
`;

const outPath = new URL('../supabase/functions/_shared/fulfillment-fonts.ts', import.meta.url);
await Deno.writeTextFile(outPath, out);
console.log(`wrote ${outPath.pathname}`);
