#!/usr/bin/env python3
"""Regenerate supabase/seed/00-legacy-grants.sql.

Supabase flipped platform defaults on 2026-05-30: new local stacks no longer
auto-grant table/function privileges to anon/authenticated at object creation,
which breaks every migration written under the legacy defaults (42501s all
over). Worse, the migrations' deliberate `REVOKE`s are creation-order no-ops
under the new defaults, so the final ACL state cannot be reconstructed from
the database alone — the migration TEXT is the only source of truth.

This script emits a seed that (1) restores the legacy blanket baseline on all
existing public objects, then (2) replays every top-level GRANT/REVOKE
statement from supabase/migrations/*.sql in order, so every deliberate
narrowing lands exactly as the migration author wrote it.

Run it whenever migrations add new GRANT/REVOKEs (or just before debugging a
fresh-stack permission failure):

    python3 scripts/generate-legacy-grants.py

The seed runs first in [db.seed] sql_paths on every local `supabase db reset`
and never executes on prod.
"""

import glob
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "supabase" / "seed" / "00-legacy-grants.sql"

DOLLAR_BODY = re.compile(r"\$([A-Za-z_]*)\$.*?\$\1\$", re.DOTALL)
LINE_COMMENT = re.compile(r"--[^\n]*")
BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
STMT = re.compile(r"(?:GRANT|REVOKE)\s[^;]*;", re.DOTALL)
DROP_FN = re.compile(
    r"DROP\s+FUNCTION\s+(?:IF\s+EXISTS\s+)?([A-Za-z_.\"]+\s*\([^)]*\))", re.IGNORECASE
)
ON_FN = re.compile(r"ON\s+FUNCTION\s+([A-Za-z_.\"]+\s*\([^)]*\))", re.IGNORECASE)


def signature(text: str) -> str:
    """Normalize `public.f( uuid , TEXT )` to `public.f(uuid,text)`.

    Deliberately literal: only a signature written the same way in both the
    DROP and the GRANT/REVOKE compares equal. A near-miss keeps the statement,
    which is the safe direction — a replayed statement for a live object is
    correct, while dropping a live one would silently change an ACL.
    """
    name, _, args = text.partition("(")
    args = args.rsplit(")", 1)[0]
    parts = [" ".join(a.split()).lower() for a in args.split(",")] if args.strip() else []
    return f"{' '.join(name.split()).lower()}({','.join(parts)})"


def clean(raw: str) -> str:
    # Strip function bodies first (GRANT text inside plpgsql must not replay),
    # then comments (prose that merely mentions REVOKE).
    return LINE_COMMENT.sub("", BLOCK_COMMENT.sub("", DOLLAR_BODY.sub("", raw)))


def extract_statements() -> list[tuple[str, str]]:
    paths = sorted(glob.glob(str(ROOT / "supabase" / "migrations" / "*.sql")))
    cleaned = {path: clean(Path(path).read_text()) for path in paths}

    # A GRANT/REVOKE for a function signature a LATER migration DROPs is dead:
    # by the time this seed replays, the object it names no longer exists.
    # Recording the last position each signature is dropped at lets those
    # statements be omitted rather than emitted as guarded no-ops.
    last_drop: dict[str, tuple[int, int]] = {}
    for index, path in enumerate(paths):
        for m in DROP_FN.finditer(cleaned[path]):
            sig = signature(m.group(1))
            here = (index, m.start())
            if last_drop.get(sig, (-1, -1)) < here:
                last_drop[sig] = here

    out: list[tuple[str, str]] = []
    for index, path in enumerate(paths):
        for m in STMT.finditer(cleaned[path]):
            stmt = " ".join(m.group(0).split())
            # Only statements that start with the keyword survive (defensive).
            if not stmt.startswith(("GRANT ", "REVOKE ")):
                continue
            target = ON_FN.search(stmt)
            if target and last_drop.get(signature(target.group(1)), (-1, -1)) > (
                index,
                m.start(),
            ):
                continue
            out.append((Path(path).name, stmt))
    return out


def main() -> None:
    stmts = extract_statements()
    lines: list[str] = []
    lines.append(
        """-- ═══════════════════════════════════════════════════════════════════════════
-- 00-legacy-grants — GENERATED by scripts/generate-legacy-grants.py. Do not
-- hand-edit; regenerate after adding migrations with GRANT/REVOKE statements.
--
-- Supabase's 2026-05-30 platform-default flip leaves fresh local stacks
-- without the creation-time grants every migration up to the flip relied on
-- (and makes the migrations' deliberate REVOKEs creation-order no-ops). This
-- seed restores the legacy blanket baseline, then replays the migrations'
-- entire top-level GRANT/REVOKE history in order — the final ACL state
-- matches what the old stack (and prod) converged to. Local-only: seeds never
-- run on prod. RLS remains the enforcement layer throughout.
-- ═══════════════════════════════════════════════════════════════════════════

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- Legacy creation-time baseline on everything that exists locally.
DO $baseline$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT c.oid::regclass AS obj
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p', 'v', 'm', 'f')
  LOOP
    EXECUTE format('GRANT ALL ON TABLE %s TO anon, authenticated, service_role', r.obj);
  END LOOP;
  FOR r IN
    SELECT c.oid::regclass AS obj
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'S'
  LOOP
    EXECUTE format('GRANT USAGE, SELECT, UPDATE ON SEQUENCE %s TO anon, authenticated, service_role', r.obj);
  END LOOP;
  FOR r IN
    SELECT p.oid::regprocedure AS obj, p.prokind
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.prokind IN ('f', 'p')
  LOOP
    EXECUTE format(
      'GRANT EXECUTE ON %s %s TO anon, authenticated, service_role',
      CASE WHEN r.prokind = 'p' THEN 'PROCEDURE' ELSE 'FUNCTION' END, r.obj);
  END LOOP;
END $baseline$;

-- Legacy defaults for anything created interactively after this seed.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;

-- ── Replay of every top-level GRANT/REVOKE across supabase/migrations/ ──────
-- Statements naming a function signature a later migration DROPs are omitted
-- entirely — the object they address no longer exists by the time this runs.
-- The rest are guarded, so an object dropped some other way is skipped too.
"""
    )
    for fname, stmt in stmts:
        assert "$g$" not in stmt, f"dollar-tag collision in {fname}: {stmt}"
        lines.append(f"-- {fname}")
        lines.append("DO $g$ BEGIN")
        lines.append(f"  {stmt}")
        lines.append(
            "EXCEPTION WHEN undefined_function OR undefined_table OR undefined_object OR undefined_column THEN NULL;"
        )
        lines.append("END $g$;")
        lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} — baseline + {len(stmts)} replayed statements")


if __name__ == "__main__":
    main()
