export { ImmersiveTimelineCarousel } from './ImmersiveTimelineCarousel'
export type { ImmersiveTimelineCarouselProps } from './ImmersiveTimelineCarousel'
export { useScrollSnap } from './useScrollSnap'
export { useResponsiveConfig, usePrefersReducedMotion } from './useResponsiveConfig'
export type { TimelineConfig } from './useResponsiveConfig'
