-- ═══════════════════════════════════════════════════════════════════════════
-- Migration: products.status — widen lifecycle vocabulary
-- Description: Migration 00060 introduced products.status with the
--              ('draft','in_review','published','deprecated') vocabulary
--              and default 'draft'. The Proposal Builder needs:
--                - 'archived'  to hide retired products without deleting
--                - default     'published' so a draft only happens by
--                              opt-in (e.g. quick-create from the
--                              ProductPickerModal sets status='draft'
--                              explicitly)
--                - NOT NULL    so the column can be relied on without
--                              null-handling
--
--              Strategy:
--                1. Backfill any NULL rows to 'published'.
--                2. Drop the old CHECK constraint (keeping it would block
--                   the new vocabulary).
--                3. Re-add a CHECK that includes both the legacy values
--                   the admin-portal still uses ('in_review','deprecated')
--                   AND the new 'archived' state.
--                4. Set NOT NULL + default 'published'.
--
--              Net effect: the partial index from 00060 keeps doing its
--              job; admin-portal code that filters by status keeps
--              working; the new picker can opt in to drafts.
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. Backfill any nulls (the column was added without NOT NULL in 00060).
UPDATE products SET status = 'published' WHERE status IS NULL;

-- 2. Drop the original CHECK constraint. The constraint name from 00060
--    is the autogenerated `products_status_check`.
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_status_check;

-- 3. Re-add a CHECK that supports BOTH legacy and new vocabulary so
--    nothing existing breaks while we let the proposal builder write
--    'archived' rows.
ALTER TABLE products
  ADD CONSTRAINT products_status_check
  CHECK (status IN ('draft', 'in_review', 'published', 'deprecated', 'archived'));

-- 4. Pin the column to NOT NULL with the new default.
ALTER TABLE products
  ALTER COLUMN status SET DEFAULT 'published',
  ALTER COLUMN status SET NOT NULL;

-- The plain b-tree index from 00060 is fine. We don't need a separate
-- partial index — every status value gets queried at some point.
