-- ═══════════════════════════════════════════════════════════════════════════
-- 00336 — Arrival Arc email templates + the design-request-claimed repair (I66)
--
-- Program: Arrival Arc (Wave 2). notification-dispatch renders email templates
-- LIVE from email_templates (00078) — an unknown template_id silently sends the
-- generic "You have a new notification from Patina" fallback, and an empty
-- subject_default independently degrades to "Notification from Patina" (I66).
-- So every row below populates BOTH subject_default AND html_content.
--
-- Three rows (00296/00309-era UPSERT idiom — ON CONFLICT (slug) DO UPDATE, so
-- template edits ship via migration and the 00125 snapshot trigger versions the
-- prior body):
--
--   1. design-request-held           (NEW — sent by accept_design_request 00330)
--   2. design-request-intro-delivered (NEW — sent by ceremony_complete 00331)
--   3. design-request-claimed        (REPAIR — invoked by claim_design_request
--      since 00286 but NEVER seeded; every claim email to date has sent generic
--      boilerplate. Live prod gap found in I66/T0.4.)
--
-- HTML: hand-adapted from the 00309 branded shell (generated by
-- scripts/emails/build.mjs — tricolor bar, Fraunces headline, Hanken Grotesk
-- body, dark-mode CSS, {{brand}} footer tokens). These three are NOT added to
-- build.mjs's DB_TEMPLATES (that script rewrites 00309/00311/00312 in place);
-- if they later join the design-system pipeline, move the source into
-- packages/email/branded/ and extend the script.
--
-- Copy: brand-voice rules — plain-spoken, truth-framed (reports what happened,
-- never impersonates the designer), no mechanics talk. Recipient is the
-- HOMEOWNER, whose surface is the Patina iOS app — so no portal CTA buttons
-- (brandDefaults' dashboard_url points at the designer portal; a wrong-portal
-- button is worse than none).
--
-- Variables: notification-dispatch enriches data with displayName /
-- displayNameComma; the RPCs send studio_name (00330/00331). Footer tokens
-- (business_address, unsub_url, prefs_url) come from brandDefaults().
--
-- No GRANT/REVOKE: email_templates is reached only by the service-role client
-- inside edge functions (00296 precedent) — the legacy-grants seed is unchanged.
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO public.email_templates
  (slug, name, description, category, subject_default, html_content, content_blocks, variables, is_active)
VALUES
  ('design-request-held',
   'Design request held',
   'Arrival Arc held state: a studio claimed the homeowner''s request; the introduction is being written. Sent by accept_design_request (00330).',
   'transactional',
   'Your request is in hand',
   $held$<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="color-scheme" content="light dark">
  <meta name="supported-color-schemes" content="light dark">
  <meta name="x-apple-disable-message-reformatting">
  <title>Your request is in hand</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400&family=Hanken+Grotesk:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
  <style>
    :root { color-scheme: light dark; supported-color-schemes: light dark; }
    html, body { margin:0 !important; padding:0 !important; height:100% !important; width:100% !important; }
    * { -ms-text-size-adjust:100%; -webkit-text-size-adjust:100%; }
    table, td { mso-table-lspace:0pt !important; mso-table-rspace:0pt !important; border-collapse:collapse !important; }
    img { -ms-interpolation-mode:bicubic; border:0; height:auto; line-height:100%; outline:none; text-decoration:none; }
    a { text-decoration:none; }
    a[x-apple-data-detectors] { color:inherit !important; text-decoration:none !important; }
    @media screen and (max-width:620px) {
      .container { width:100% !important; }
      .px { padding-left:24px !important; padding-right:24px !important; }
      .h1 { font-size:27px !important; line-height:1.18 !important; }
    }
    @media (prefers-color-scheme: dark) {
      body, .bg, .bg td { background:#14110D !important; }
      .shell { background:#1B1712 !important; border-color:#332D24 !important; }
      .ink  { color:#F2EBDD !important; }
      .ink2 { color:#D4CCBB !important; }
      .ink3 { color:#9C9484 !important; }
      .wordmark { color:#F2EBDD !important; }
      .hairbg { background:#3B342A !important; }
    }
  </style>
</head>
<body class="bg" style="margin:0; padding:0; background:#F5F0E6;">
  <div style="display:none; font-size:1px; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden; mso-hide:all; color:transparent;">{{studio_name}} has taken your request in hand — introduction on its way.&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;</div>
  <table role="presentation" class="bg" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#F5F0E6;">
    <tr><td align="center" style="padding:24px 12px;">
      <table role="presentation" class="container shell" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px; max-width:600px; background:#FCF9F2; border:1px solid #E6DDCC; border-radius:12px; overflow:hidden;">
        <tr><td style="font-size:0; line-height:0;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
            <td width="33.34%" height="4" style="background:#4E7A66; font-size:0; line-height:0;">&nbsp;</td>
            <td width="33.33%" height="4" style="background:#B08A46; font-size:0; line-height:0;">&nbsp;</td>
            <td width="33.33%" height="4" style="background:#A24E2E; font-size:0; line-height:0;">&nbsp;</td>
          </tr></table>
        </td></tr>
        <tr><td class="px" style="padding:26px 40px 0;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
            <td align="left" valign="middle" class="wordmark" style="font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:23px; font-weight:600; letter-spacing:-0.01em; color:#1F1B16;">Patina</td>
            <td align="right" valign="middle" class="ink3" style="font-family:'IBM Plex Mono', ui-monospace, SFMono-Regular, 'Courier New', monospace; font-size:11px; letter-spacing:0.14em; text-transform:uppercase; color:#8C8578;">Your request</td>
          </tr></table>
        </td></tr>
        <tr><td class="px" style="padding:22px 40px 0;">
          <div style="font-family:'IBM Plex Mono', ui-monospace, SFMono-Regular, 'Courier New', monospace; font-size:11px; font-weight:500; letter-spacing:0.16em; text-transform:uppercase; color:#4E7A66; margin:6px 0 14px;">In hand</div>
          <h1 class="h1 ink" style="margin:0 0 16px; font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:31px; font-weight:600; line-height:1.16; letter-spacing:-0.015em; color:#1F1B16;">It&rsquo;s in good hands.</h1>
          <p class="ink2" style="margin:0 0 16px; font-family:'Hanken Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size:16px; line-height:1.62; color:#4B463E;">Hi{{displayNameComma}} &mdash; <strong style="color:#1F1B16; font-weight:600;">{{studio_name}}</strong> has taken your request in hand. An introduction is on its way &mdash; written by the designer themselves, in their own words, so give it a moment.</p>
          <p class="ink2" style="margin:0 0 16px; font-family:'Hanken Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size:16px; line-height:1.62; color:#4B463E;">You&rsquo;ll find it waiting in the Patina app, along with a few times for your first conversation.</p>
          <p class="ink2" style="margin:22px 0 0; font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:16px; font-style:italic; color:#4B463E;">&mdash; The Patina team</p>
        </td></tr>
        <tr><td class="px" style="padding:34px 40px 0;">
          <div class="hairbg" style="height:1px; background:#E6DDCC; font-size:0; line-height:0;">&nbsp;</div>
        </td></tr>
        <tr><td class="px" style="padding:22px 40px 32px;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
            <td align="left" valign="top">
              <div class="ink2" style="font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:15px; color:#4B463E; margin-bottom:5px;">Patina</div>
              <div class="ink3" style="font-family:'Hanken Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size:13px; line-height:1.5; color:#8C8578;">A workshop for interior designers<br>and the makers they trust.</div>
            </td>
          </tr></table>
        </td></tr>
      </table>
      <table role="presentation" class="container" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px; max-width:600px;">
        <tr><td class="px" align="center" style="padding:18px 40px 10px; font-family:'IBM Plex Mono', ui-monospace, SFMono-Regular, 'Courier New', monospace; font-size:11px; line-height:1.8; letter-spacing:0.03em; color:#8C8578;">
          Patina &nbsp;&middot;&nbsp; {{business_address}}<br>
          <a href="{{unsub_url}}" style="color:#8C8578; text-decoration:underline;">Unsubscribe</a> &nbsp;&middot;&nbsp; <a href="{{prefs_url}}" style="color:#8C8578; text-decoration:underline;">Manage preferences</a>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>$held$,
   '[]'::jsonb,
   '["studio_name","displayNameComma","business_address","unsub_url","prefs_url","app_url"]'::jsonb,
   true),

  ('design-request-intro-delivered',
   'Design request introduction delivered',
   'Arrival Arc introduction moment: the studio introduced themselves and offered discovery times. Sent by ceremony_complete (00331).',
   'transactional',
   '{{studio_name}} introduced themselves',
   $intro$<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="color-scheme" content="light dark">
  <meta name="supported-color-schemes" content="light dark">
  <meta name="x-apple-disable-message-reformatting">
  <title>An introduction, and a few times</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400&family=Hanken+Grotesk:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
  <style>
    :root { color-scheme: light dark; supported-color-schemes: light dark; }
    html, body { margin:0 !important; padding:0 !important; height:100% !important; width:100% !important; }
    * { -ms-text-size-adjust:100%; -webkit-text-size-adjust:100%; }
    table, td { mso-table-lspace:0pt !important; mso-table-rspace:0pt !important; border-collapse:collapse !important; }
    img { -ms-interpolation-mode:bicubic; border:0; height:auto; line-height:100%; outline:none; text-decoration:none; }
    a { text-decoration:none; }
    a[x-apple-data-detectors] { color:inherit !important; text-decoration:none !important; }
    @media screen and (max-width:620px) {
      .container { width:100% !important; }
      .px { padding-left:24px !important; padding-right:24px !important; }
      .h1 { font-size:27px !important; line-height:1.18 !important; }
    }
    @media (prefers-color-scheme: dark) {
      body, .bg, .bg td { background:#14110D !important; }
      .shell { background:#1B1712 !important; border-color:#332D24 !important; }
      .ink  { color:#F2EBDD !important; }
      .ink2 { color:#D4CCBB !important; }
      .ink3 { color:#9C9484 !important; }
      .wordmark { color:#F2EBDD !important; }
      .hairbg { background:#3B342A !important; }
    }
  </style>
</head>
<body class="bg" style="margin:0; padding:0; background:#F5F0E6;">
  <div style="display:none; font-size:1px; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden; mso-hide:all; color:transparent;">{{studio_name}} introduced themselves — pick a time for your first conversation.&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;</div>
  <table role="presentation" class="bg" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#F5F0E6;">
    <tr><td align="center" style="padding:24px 12px;">
      <table role="presentation" class="container shell" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px; max-width:600px; background:#FCF9F2; border:1px solid #E6DDCC; border-radius:12px; overflow:hidden;">
        <tr><td style="font-size:0; line-height:0;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
            <td width="33.34%" height="4" style="background:#4E7A66; font-size:0; line-height:0;">&nbsp;</td>
            <td width="33.33%" height="4" style="background:#B08A46; font-size:0; line-height:0;">&nbsp;</td>
            <td width="33.33%" height="4" style="background:#A24E2E; font-size:0; line-height:0;">&nbsp;</td>
          </tr></table>
        </td></tr>
        <tr><td class="px" style="padding:26px 40px 0;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
            <td align="left" valign="middle" class="wordmark" style="font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:23px; font-weight:600; letter-spacing:-0.01em; color:#1F1B16;">Patina</td>
            <td align="right" valign="middle" class="ink3" style="font-family:'IBM Plex Mono', ui-monospace, SFMono-Regular, 'Courier New', monospace; font-size:11px; letter-spacing:0.14em; text-transform:uppercase; color:#8C8578;">Your match</td>
          </tr></table>
        </td></tr>
        <tr><td class="px" style="padding:22px 40px 0;">
          <div style="font-family:'IBM Plex Mono', ui-monospace, SFMono-Regular, 'Courier New', monospace; font-size:11px; font-weight:500; letter-spacing:0.16em; text-transform:uppercase; color:#4E7A66; margin:6px 0 14px;">Introduction</div>
          <h1 class="h1 ink" style="margin:0 0 16px; font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:31px; font-weight:600; line-height:1.16; letter-spacing:-0.015em; color:#1F1B16;">{{studio_name}} introduced themselves.</h1>
          <p class="ink2" style="margin:0 0 16px; font-family:'Hanken Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size:16px; line-height:1.62; color:#4B463E;">Hi{{displayNameComma}} &mdash; their introduction is waiting in the Patina app, written in their own words. Alongside it: a few times for your first conversation.</p>
          <p class="ink2" style="margin:0 0 16px; font-family:'Hanken Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size:16px; line-height:1.62; color:#4B463E;">Pick the one that suits &mdash; one tap books it. If none of them work, say so in the thread and you&rsquo;ll sort out a time together.</p>
          <p class="ink2" style="margin:22px 0 0; font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:16px; font-style:italic; color:#4B463E;">&mdash; The Patina team</p>
        </td></tr>
        <tr><td class="px" style="padding:34px 40px 0;">
          <div class="hairbg" style="height:1px; background:#E6DDCC; font-size:0; line-height:0;">&nbsp;</div>
        </td></tr>
        <tr><td class="px" style="padding:22px 40px 32px;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
            <td align="left" valign="top">
              <div class="ink2" style="font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:15px; color:#4B463E; margin-bottom:5px;">Patina</div>
              <div class="ink3" style="font-family:'Hanken Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size:13px; line-height:1.5; color:#8C8578;">A workshop for interior designers<br>and the makers they trust.</div>
            </td>
          </tr></table>
        </td></tr>
      </table>
      <table role="presentation" class="container" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px; max-width:600px;">
        <tr><td class="px" align="center" style="padding:18px 40px 10px; font-family:'IBM Plex Mono', ui-monospace, SFMono-Regular, 'Courier New', monospace; font-size:11px; line-height:1.8; letter-spacing:0.03em; color:#8C8578;">
          Patina &nbsp;&middot;&nbsp; {{business_address}}<br>
          <a href="{{unsub_url}}" style="color:#8C8578; text-decoration:underline;">Unsubscribe</a> &nbsp;&middot;&nbsp; <a href="{{prefs_url}}" style="color:#8C8578; text-decoration:underline;">Manage preferences</a>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>$intro$,
   '[]'::jsonb,
   '["studio_name","displayNameComma","business_address","unsub_url","prefs_url","app_url"]'::jsonb,
   true),

  ('design-request-claimed',
   'Design request claimed',
   'REPAIR (I66): invoked by claim_design_request since 00286 but never seeded — claims emailed generic boilerplate. Legacy pool-claim path (flag-off); the arc path sends design-request-held instead.',
   'transactional',
   'Your design request was accepted',
   $claimed$<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="color-scheme" content="light dark">
  <meta name="supported-color-schemes" content="light dark">
  <meta name="x-apple-disable-message-reformatting">
  <title>Your design request was accepted</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400&family=Hanken+Grotesk:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
  <style>
    :root { color-scheme: light dark; supported-color-schemes: light dark; }
    html, body { margin:0 !important; padding:0 !important; height:100% !important; width:100% !important; }
    * { -ms-text-size-adjust:100%; -webkit-text-size-adjust:100%; }
    table, td { mso-table-lspace:0pt !important; mso-table-rspace:0pt !important; border-collapse:collapse !important; }
    img { -ms-interpolation-mode:bicubic; border:0; height:auto; line-height:100%; outline:none; text-decoration:none; }
    a { text-decoration:none; }
    a[x-apple-data-detectors] { color:inherit !important; text-decoration:none !important; }
    @media screen and (max-width:620px) {
      .container { width:100% !important; }
      .px { padding-left:24px !important; padding-right:24px !important; }
      .h1 { font-size:27px !important; line-height:1.18 !important; }
    }
    @media (prefers-color-scheme: dark) {
      body, .bg, .bg td { background:#14110D !important; }
      .shell { background:#1B1712 !important; border-color:#332D24 !important; }
      .ink  { color:#F2EBDD !important; }
      .ink2 { color:#D4CCBB !important; }
      .ink3 { color:#9C9484 !important; }
      .wordmark { color:#F2EBDD !important; }
      .hairbg { background:#3B342A !important; }
    }
  </style>
</head>
<body class="bg" style="margin:0; padding:0; background:#F5F0E6;">
  <div style="display:none; font-size:1px; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden; mso-hide:all; color:transparent;">A designer accepted your design request and will be in touch.&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;</div>
  <table role="presentation" class="bg" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#F5F0E6;">
    <tr><td align="center" style="padding:24px 12px;">
      <table role="presentation" class="container shell" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px; max-width:600px; background:#FCF9F2; border:1px solid #E6DDCC; border-radius:12px; overflow:hidden;">
        <tr><td style="font-size:0; line-height:0;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
            <td width="33.34%" height="4" style="background:#4E7A66; font-size:0; line-height:0;">&nbsp;</td>
            <td width="33.33%" height="4" style="background:#B08A46; font-size:0; line-height:0;">&nbsp;</td>
            <td width="33.33%" height="4" style="background:#A24E2E; font-size:0; line-height:0;">&nbsp;</td>
          </tr></table>
        </td></tr>
        <tr><td class="px" style="padding:26px 40px 0;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
            <td align="left" valign="middle" class="wordmark" style="font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:23px; font-weight:600; letter-spacing:-0.01em; color:#1F1B16;">Patina</td>
            <td align="right" valign="middle" class="ink3" style="font-family:'IBM Plex Mono', ui-monospace, SFMono-Regular, 'Courier New', monospace; font-size:11px; letter-spacing:0.14em; text-transform:uppercase; color:#8C8578;">Your request</td>
          </tr></table>
        </td></tr>
        <tr><td class="px" style="padding:22px 40px 0;">
          <div style="font-family:'IBM Plex Mono', ui-monospace, SFMono-Regular, 'Courier New', monospace; font-size:11px; font-weight:500; letter-spacing:0.16em; text-transform:uppercase; color:#4E7A66; margin:6px 0 14px;">Accepted</div>
          <h1 class="h1 ink" style="margin:0 0 16px; font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:31px; font-weight:600; line-height:1.16; letter-spacing:-0.015em; color:#1F1B16;">A designer said yes.</h1>
          <p class="ink2" style="margin:0 0 16px; font-family:'Hanken Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size:16px; line-height:1.62; color:#4B463E;">Hi{{displayNameComma}} &mdash; a designer accepted your design request and will be in touch. You&rsquo;ll hear from them in the Patina app.</p>
          <p class="ink2" style="margin:0 0 16px; font-family:'Hanken Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size:16px; line-height:1.62; color:#4B463E;">Your scans and notes travel with the request, so they&rsquo;re already looking at the room you shared.</p>
          <p class="ink2" style="margin:22px 0 0; font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:16px; font-style:italic; color:#4B463E;">&mdash; The Patina team</p>
        </td></tr>
        <tr><td class="px" style="padding:34px 40px 0;">
          <div class="hairbg" style="height:1px; background:#E6DDCC; font-size:0; line-height:0;">&nbsp;</div>
        </td></tr>
        <tr><td class="px" style="padding:22px 40px 32px;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
            <td align="left" valign="top">
              <div class="ink2" style="font-family:'Fraunces', Georgia, 'Times New Roman', serif; font-size:15px; color:#4B463E; margin-bottom:5px;">Patina</div>
              <div class="ink3" style="font-family:'Hanken Grotesk', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; font-size:13px; line-height:1.5; color:#8C8578;">A workshop for interior designers<br>and the makers they trust.</div>
            </td>
          </tr></table>
        </td></tr>
      </table>
      <table role="presentation" class="container" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px; max-width:600px;">
        <tr><td class="px" align="center" style="padding:18px 40px 10px; font-family:'IBM Plex Mono', ui-monospace, SFMono-Regular, 'Courier New', monospace; font-size:11px; line-height:1.8; letter-spacing:0.03em; color:#8C8578;">
          Patina &nbsp;&middot;&nbsp; {{business_address}}<br>
          <a href="{{unsub_url}}" style="color:#8C8578; text-decoration:underline;">Unsubscribe</a> &nbsp;&middot;&nbsp; <a href="{{prefs_url}}" style="color:#8C8578; text-decoration:underline;">Manage preferences</a>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>$claimed$,
   '[]'::jsonb,
   '["displayNameComma","projectType","leadId","business_address","unsub_url","prefs_url","app_url"]'::jsonb,
   true)

ON CONFLICT (slug) DO UPDATE SET
  name            = EXCLUDED.name,
  description     = EXCLUDED.description,
  category        = EXCLUDED.category,
  subject_default = EXCLUDED.subject_default,
  html_content    = EXCLUDED.html_content,
  variables       = EXCLUDED.variables,
  is_active       = true,
  updated_at      = now();
